version: '3'

services:
  crawler-lingxing-mutil-channel-data:
    image: crawler-lingxing-mutil-channel-data:v1.0.0
    container_name: crawler-lingxing-mutil-channel-data
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8700:8000
    environment:
      - TZ:Asia/Shanghai
      - PYTHONPATH:/app