# -*- coding: utf-8 -*-
# @Time : 2023/01/16
# @Author : 李仕春
# @Email : 571182073@qq.com
# @File :
# @desc :

# 领星-利润报表-订单
profit_report_order_db_table = 'ods_prod.ods_gsm_lx_profit_report_order_i_d'

ods_fc_gad_lx_profit_report_order_i_w = """
create table if not exists ods_prod.ods_gsm_lx_profit_report_order_i_d
(
    dt                                 varchar(10)  not null comment 'dt',
    id                                 varchar(10)  not null comment 'ID',
    accountType                        varchar(25)  not null comment '帐户类型',
    asin                               varchar(50)  not null comment 'asin',
    commission                         varchar(50)  not null comment '平台费',
    costQuantity                       varchar(20)  not null comment '成本数量',
    country                            varchar(25)  not null comment '国家',
    countryCode                        varchar(50)  not null comment '国家编码',
    currencyCode                       varchar(50)  not null comment '货币代码',
    currencyIcon                       varchar(50)  not null comment '货币图标',
    description                        varchar(500) not null comment '描述',
    eventSource                        varchar(50)  not null comment '来源',
    fbaPerUnitFulfillmentFee           varchar(50)  not null comment 'FBA履行费用',
    fid                                varchar(50)  not null comment '结算编号',
    fulfillment                        varchar(50)  not null comment '订单类型',
    fundTransferDatetimeLocale         varchar(20)  not null comment '资金转账当地日期时间',
    fundTransferStatus                 varchar(50)  not null comment '资金转移状态',
    giftWrap                           varchar(50)  not null comment '礼品包装',
    giftWrapTax                        varchar(50)  not null comment '礼物包装税',
    giftwrapChargeback                 varchar(50)  not null comment '礼品包装拒付',
    grossProfit                        varchar(50)  not null comment '毛利润',
    hasLogisticsCostsDetail            varchar(50)  not null comment '物流成本详细信息',
    hasOtherCostsDetail                varchar(50)  not null comment '其他成本详细信息',
    hasPurchaseCostsDetail             varchar(50)  not null comment '采购成本详细信息',
    localName                          varchar(50)  not null comment 'sku信息（颜色尺码）',
    localSku                           varchar(50)  not null comment 'localSku',
    logisticsCostsTotal                varchar(50)  not null comment '物流成本总计',
    marketplaceFacilitatorVatPrincipal varchar(50)  not null comment '市场税-销售额',
    marketplaceFacilitatorVatShipping  varchar(50)  not null comment '市场税-买家运费',
    msku                               varchar(50)  not null comment 'msku',
    orderId                            varchar(50)  not null comment '亚马逊订单号',
    other                              varchar(50)  not null comment '其他',
    otherCostsTotal                    varchar(50)  not null comment '其他成本',
    otherTransactionFeesDetail         varchar(500)  not null comment '其他交易费明细,所有未识别的明细汇总',
    otherTransactionFeesTotal          varchar(50)  not null comment '其他交易费总计',
    parentAsin                         varchar(50)  not null comment '父asin',
    postedDatetimeLocale               varchar(50)  not null comment '结算时间',
    principal                          varchar(50)  not null comment '销售额',
    productSalesQuantity               varchar(50)  not null comment '订单数量',
    promotionDiscountTax               varchar(50)  not null comment '促销折扣税',
    promotionalRebates                 varchar(50)  not null comment '促销折扣',
    purchaseCostsTotal                 varchar(50)  not null comment '采购成本',
    refundCommission                   varchar(50)  not null comment '交易费用退款额',
    restockingFee                      varchar(50)  not null comment '补货费',
    salesTaxWithheld                   varchar(50)  not null comment '市场税',
    settlementStatus                   varchar(50)  not null comment '结算状态：待结算：["Open", "Pending"]已结算：["Closed"]',
    settlementTotal                    varchar(50)  not null comment '亚马逊结算小结',
    shipmentDatetimeLocale             varchar(50)  not null comment '发货时间',
    shippingCharge                     varchar(50)  not null comment '买家运费',
    shippingChargeback                 varchar(50)  not null comment '运费拒付',
    shippingDiscountTax                varchar(50)  not null comment '运费折扣税',
    shippingTax                        varchar(50)  not null comment '运费税',
    sid                                varchar(50)  not null comment '店铺sid',
    smallImageUrl                      varchar(100) not null comment '图片',
    storeName                          varchar(50)  not null comment '店铺名',
    tax                                varchar(50)  not null comment '销售税额',
    toCnyRate                          varchar(50)  not null comment '转换成人民币汇率',
    toTargetRate                       varchar(50)  not null comment '转换成目标货币汇率',
    primary key (dt, id)
)comment = '新版利润统计（订单维度）' 
    partition by key (dt) partitions 3;
                    """

ods_fc_gad_lx_profit_report_order_i_w_field_list = [
    "dt",
    "id",
    "accountType",
    "asin",
    "commission",
    "costQuantity",
    "country",
    "countryCode",
    "currencyCode",
    "currencyIcon",
    "description",
    "eventSource",
    "fbaPerUnitFulfillmentFee",
    "fid",
    "fulfillment",
    "fundTransferDatetimeLocale",
    "fundTransferStatus",
    "giftWrap",
    "giftWrapTax",
    "giftwrapChargeback",
    "grossProfit",
    "hasLogisticsCostsDetail",
    "hasOtherCostsDetail",
    "hasPurchaseCostsDetail",
    "localName",
    "localSku",
    "logisticsCostsTotal",
    "marketplaceFacilitatorVatPrincipal",
    "marketplaceFacilitatorVatShipping",
    "msku",
    "orderId",
    "other",
    "otherCostsTotal",
    "otherTransactionFeesDetail",
    "otherTransactionFeesTotal",
    "parentAsin",
    "postedDatetimeLocale",
    "principal",
    "productSalesQuantity",
    "promotionDiscountTax",
    "promotionalRebates",
    "purchaseCostsTotal",
    "refundCommission",
    "restockingFee",
    "salesTaxWithheld",
    "settlementStatus",
    "settlementTotal",
    "shipmentDatetimeLocale",
    "shippingCharge",
    "shippingChargeback",
    "shippingDiscountTax",
    "shippingTax",
    "sid",
    "smallImageUrl",
    "storeName",
    "tax",
    "toCnyRate",
    "toTargetRate"
]

# 领星-利润报表-店铺
profit_report_shop_db_table = 'ods_prod.ods_gsm_lx_profit_report_store_i_d'

ods_fc_gad_lx_profit_report_shop_i_d = """
create table if not exists ods_prod.ods_gsm_lx_profit_report_store_i_d
(
    dt                                       varchar(10)  not null comment 'dt',
    sid                                      varchar(10)  not null comment '领星店铺id',
    storeName                                varchar(30)  not null comment '店铺',
    transactionStatus                        varchar(50)  not null comment '交易状态',
    transactionStatusCode                    varchar(30)  not null comment '交易状态代码',
    totalFbaAndFbmQuantity                   varchar(30)  not null comment 'fba和fbm销量加总，用于计算占比(销量)',
    totalFbaAndFbmAmount                     varchar(30)  not null comment 'fba和fbm销售额加总，用于计算占比(销售额)',
    totalSalesQuantity                       varchar(30)  not null comment '销量',
    fbaSalesQuantity                         varchar(30)  not null comment 'FBA销量',
    fbmSalesQuantity                         varchar(30)  not null comment 'FBM销量',
    totalReshipQuantity                      varchar(30)  not null comment '补换货量',
    reshipFbmProductSalesQuantity            varchar(30)  not null comment 'FBM补（换）货量',
    reshipFbmProductSaleRefundsQuantity      varchar(30)  not null comment 'FBM补（换）货退回量',
    reshipFbaProductSalesQuantity            varchar(30)  not null comment 'FBA补（换）货量',
    reshipFbaProductSaleRefundsQuantity      varchar(30)  not null comment 'FBA补（换）货退回量',
    mcFbaFulfillmentFeesQuantity             varchar(30)  not null comment '多渠道销量',
    cgAbsQuantity                            varchar(10)  not null comment 'cgAbsQuantity',
    cgQuantity                               varchar(10)  not null comment 'cgQuantity',
    fbaInventoryCreditQuantity               varchar(30)  not null comment 'FBA库存赔偿数量',
    disposalQuantity                         varchar(30)  not null comment '销毁数量',
    removalQuantity                          varchar(30)  not null comment '移除数量',
    totalAdsSales                            varchar(30)  not null comment '广告销售额',
    adsSdSales                               varchar(30)  not null comment 'sd广告销售额',
    adsSpSales                               varchar(30)  not null comment 'sp广告销售额',
    sharedAdsSbSales                         varchar(30)  not null comment 'sb广告销售额',
    sharedAdsSbvSales                        varchar(30)  not null comment 'sbv广告销售额',
    totalAdsSalesQuantity                    varchar(30)  not null comment '广告销量',
    adsSdSalesQuantity                       varchar(30)  not null comment 'sd广告销量',
    adsSpSalesQuantity                       varchar(30)  not null comment 'sp广告销量',
    sharedAdsSbSalesQuantity                 varchar(30)  not null comment 'sb广告销量',
    sharedAdsSbvSalesQuantity                varchar(30)  not null comment 'sbv广告销量',
    totalSalesAmount                         varchar(30)  not null comment '销售额',
    fbaSaleAmount                            varchar(30)  not null comment 'FBA销售额',
    fbmSaleAmount                            varchar(30)  not null comment 'FBM销售额',
    shippingCredits                          varchar(30)  not null comment '买家运费',
    promotionalRebates                       varchar(30)  not null comment '促销折扣',
    fbaInventoryCredit                       varchar(30)  not null comment 'FBA库存赔偿',
    cashOnDelivery                           varchar(30)  not null comment 'COD',
    otherInAmount                            varchar(30)  not null comment '其他收入',
    fbaLiquidationProceeds                   varchar(30)  not null comment '清算收入',
    fbaLiquidationProceedsAdjustments        varchar(30)  not null comment '清算调整',
    amazonShippingReimbursement              varchar(30)  not null comment '亚马逊运费赔偿',
    safeTReimbursement                       varchar(30)  not null comment 'Safe-T索赔',
    netcoTransaction                         varchar(30)  not null comment 'Netco交易',
    reimbursements                           varchar(30)  not null comment '赔偿收入',
    clawbacks                                varchar(30)  not null comment '追索收入',
    sharedComminglingVatIncome               varchar(30)  not null comment '混合VAT收入',
    giftWrapCredits                          varchar(30)  not null comment '包装收入',
    guaranteeClaims                          varchar(30)  not null comment '买家交易保障索赔额',
    costOfPoIntegersGranted                  varchar(30)  not null comment '积分抵减收入',
    others                                   varchar(30)  not null comment 'others',
    totalSalesRefunds                        varchar(30)  not null comment '收入退款额',
    fbaSalesRefunds                          varchar(30)  not null comment 'FBA销售退款额',
    fbmSalesRefunds                          varchar(30)  not null comment 'FBM销售退款额',
    shippingCreditRefunds                    varchar(30)  not null comment '买家运费退款额',
    giftWrapCreditRefunds                    varchar(30)  not null comment '买家包装退款额',
    chargebacks                              varchar(30)  not null comment '买家拒付',
    costOfPoIntegersReturned                 varchar(30)  not null comment '积分抵减退回',
    promotionalRebateRefunds                 varchar(30)  not null comment '促销折扣退款额',
    totalFeeRefunds                          varchar(30)  not null comment '费用退款额',
    sellingFeeRefunds                        varchar(30)  not null comment '平台费退款额',
    fbaTransactionFeeRefunds                 varchar(30)  not null comment '发货费退款额',
    refundAdministrationFees                 varchar(30)  not null comment '交易费用退款额',
    otherTransactionFeeRefunds               varchar(30)  not null comment '其他订单费退款额',
    refundForAdvertiser                      varchar(30)  not null comment '广告退款额',
    pointsAdjusted                           varchar(30)  not null comment '积分费用',
    shippingLabelRefunds                     varchar(30)  not null comment '运输标签费退款',
    refundsQuantity                          varchar(30)  not null comment '退款量',
    refundsRate                              varchar(30)  not null comment '退款率',
    fbaReturnsQuantity                       varchar(30)  not null comment '退货量',
    fbaReturnsSaleableQuantity               varchar(30)  not null comment '退货量（可售）',
    fbaReturnsUnsaleableQuantity             varchar(30)  not null comment '退货量（不可售）',
    fbaReturnsQuantityRate                   varchar(30)  not null comment '退货率',
    platformFee                              varchar(30)  not null comment '平台费',
    totalFbaDeliveryFee                      varchar(30)  not null comment 'FBA发货费合计',
    fbaDeliveryFee                           varchar(30)  not null comment 'FBA发货费',
    sharedFbaTransactionCustomerReturnFee    varchar(30)  not null comment 'Fba交易客户退货费',
    mcFbaDeliveryFee                         varchar(30)  not null comment 'FBA发货费(多渠道)',
    otherTransactionFees                     varchar(30)  not null comment '其他订单费用',
    totalAdsCost                             varchar(30)  not null comment '广告费',
    adsSpCost                                varchar(30)  not null comment 'SP广告费',
    adsSbCost                                varchar(30)  not null comment 'SB广告费',
    adsSbvCost                               varchar(30)  not null comment 'SBV广告费',
    adsSdCost                                varchar(30)  not null comment 'SD广告费',
    sharedCostOfAdvertising                  varchar(30)  not null comment '差异分摊',
    promotionFee                             varchar(30)  not null comment '推广费',
    sharedSubscriptionFee                    varchar(30)  not null comment '订阅费',
    sharedLdFee                              varchar(30)  not null comment '秒杀费',
    sharedCouponFee                          varchar(30)  not null comment '优惠卷',
    sharedEarlyReviewerProgramFee            varchar(30)  not null comment '早期评论人计划',
    sharedVineFee                            varchar(30)  not null comment 'vine',
    totalStorageFee                          varchar(30)  not null comment 'FBA仓储费',
    fbaStorageFee                            varchar(30)  not null comment '月度仓库费',
    sharedFbaStorageFee                      varchar(30)  not null comment '月度仓储费差异',
    longTermStorageFee                       varchar(30)  not null comment '长期仓储费',
    sharedLongTermStorageFee                 varchar(30)  not null comment '长期仓储费差异',
    sharedStorageRenewalBilling              varchar(30)  not null comment '库存续订费用',
    sharedFbaDisposalFee                     varchar(30)  not null comment 'FBA销毁费',
    sharedFbaRemovalFee                      varchar(30)  not null comment 'FBA移除费',
    sharedFbaInboundTransportationProgramFee varchar(30)  not null comment '入仓手续费',
    sharedLabelingFee                        varchar(30)  not null comment '标签费',
    sharedPolybaggingFee                     varchar(30)  not null comment '塑料包装费',
    sharedBubblewrapFee                      varchar(30)  not null comment '泡沫包装费',
    sharedTapingFee                          varchar(30)  not null comment '胶带费',
    sharedAwdProcessingFee                   varchar(30)  not null comment '共享奖励处理费',
    sharedAwdTransportationFee               varchar(30)  not null comment '共享奖励运输费',
    sharedAwdStorageFee                      varchar(30)  not null comment '共享奖励存储费',
    sharedFbaCustomerReturnFee               varchar(30)  not null comment 'FBA卖家退回费',
    sharedFbaInboundDefectFee                varchar(30)  not null comment '计划外服务费',
    sharedFbaOverageFee                      varchar(30)  not null comment '超量仓储费',
    sharedAmazonPartneredCarrierShipmentFee  varchar(30)  not null comment '合作承运费',
    sharedFbaInboundConvenienceFee           varchar(30)  not null comment '合仓费',
    sharedItemFeeAdjustment                  varchar(30)  not null comment '库存调整费用',
    sharedOtherFbaInventoryFees              varchar(30)  not null comment '其他仓储费',
    fbaStorageFeeAccrual                     varchar(30)  not null comment '月仓储费-本月计提',
    fbaStorageFeeAccrualDifference           varchar(30)  not null comment '月仓储费-上月冲销',
    longTermStorageFeeAccrual                varchar(30)  not null comment '长期仓储费-本月计提',
    longTermStorageFeeAccrualDifference      varchar(30)  not null comment '长期仓储费-上月冲销',
    sharedFbaIntegerernationalInboundFee     varchar(30)  not null comment 'FBA国际物流货运费',
    adjustments                              varchar(30)  not null comment '调整费用',
    totalPlatformOtherFee                    varchar(30)  not null comment '平台其他费',
    shippingLabelPurchases                   varchar(30)  not null comment '运输标签费',
    sharedCarrierShippingLabelAdjustments    varchar(30)  not null comment '承运人装运标签调整费',
    sharedLiquidationsFees                   varchar(30)  not null comment '清算费',
    sharedManualProcessingFee                varchar(30)  not null comment '人工处理费用',
    sharedOtherServiceFees                   varchar(30)  not null comment '其他服务费',
    sharedMfnPostageFee                      varchar(30)  not null comment '共享自配送邮费',
    totalSalesTax                            varchar(30)  not null comment '销售税',
    taxCollected                             varchar(30)  not null comment 'VAT/GST',
    taxCollectedGiftWrap                     varchar(30)  not null comment '销售税-礼品包装税',
    taxCollectedShipping                     varchar(30)  not null comment '销售税-买家运费税',
    taxCollectedDiscount                     varchar(30)  not null comment '销售税-买家优惠税',
    taxCollectedProduct                      varchar(30)  not null comment '销售税-商品价格税',
    tcsIgstCollected                         varchar(30)  not null comment 'TCS-IGST',
    tcsSgstCollected                         varchar(30)  not null comment 'TCS-SGST',
    tcsCgstCollected                         varchar(30)  not null comment 'TCS-CGST',
    sharedComminglingVatExpenses             varchar(30)  not null comment '混合VAT',
    sharedTaxAdjustment                      varchar(30)  not null comment '分摊税款调整',
    salesTaxRefund                           varchar(30)  not null comment '销售税退款额',
    taxRefunded                              varchar(30)  not null comment 'VAT/GST',
    taxRefundedGiftWrap                      varchar(30)  not null comment '销售税退款额-礼品包装税',
    taxRefundedShipping                      varchar(30)  not null comment '销售税退款额-买家运费税',
    taxRefundedDiscount                      varchar(30)  not null comment '销售税退款额-买家优惠税',
    taxRefundedProduct                       varchar(30)  not null comment '销售税退款额-商品价格税',
    tcsIgstRefunded                          varchar(30)  not null comment 'TCS-IGST',
    tcsSgstRefunded                          varchar(30)  not null comment 'TCS-SGST',
    tcsCgstRefunded                          varchar(30)  not null comment 'TCS-CGST',
    salesTaxWithheld                         varchar(30)  not null comment '市场税',
    refundTaxWithheld                        varchar(30)  not null comment '市场税退款额',
    tdsSection194ONet                        varchar(30)  not null comment '混合网路费用',
    cgPriceTotal                             varchar(30)  not null comment '采购成本',
    cgPriceAbsTotal                          varchar(30)  not null comment '采购绝对成本',
    hasCgPriceDetail                         varchar(30)  not null comment '是否有采购成本明细',
    cgUnitPrice                              varchar(30)  not null comment '采购均价',
    proportionOfCg                           varchar(30)  not null comment '采购占比',
    cgTransportCostsTotal                    varchar(30)  not null comment '头程成本',
    hasCgTransportCostsDetail                varchar(30)  not null comment '是否有物流（头程）成本明细',
    cgTransportUnitCosts                     varchar(30)  not null comment '头程均价',
    proportionOfCgTransport                  varchar(30)  not null comment '头程占比',
    totalCost                                varchar(30)  not null comment '合计成本',
    proportionOfTotalCost                    varchar(30)  not null comment '合计成本占比',
    cgOtherCostsTotal                        varchar(30)  not null comment '其他成本',
    cgOtherUnitCosts                         varchar(30)  not null comment '其他均价',
    hasCgOtherCostsDetail                    varchar(30)  not null comment '是否有其他成本明细',
    proportionOfCgOtherCosts                 varchar(30)  not null comment '其他成本占比',
    grossProfit                              varchar(30)  not null comment '毛利润',
    grossRate                                varchar(30)  not null comment '毛利率',
    grossProfitIncome                        varchar(30)  not null comment '毛利润总额',
    grossProfitTax                           varchar(30)  not null comment '毛利税',
    otherFeeStr                              json         not null comment '其他费信息',
    customOrderFee                           varchar(30)  not null comment '自定义订单费用',
    customOrderFeePrincipal                  varchar(30)  not null comment '定制订单费用本金',
    customOrderFeeCommission                 varchar(30)  not null comment '定制订单费用佣金',
    roi                                      varchar(30)  not null comment '投资回报率',
    postedDateDayLocale                      varchar(50)  not null comment '发布日期（本地）',
    minPostedDateDayLocale                   varchar(50)  not null comment '最小发布日期（本地）',
    maxPostedDateDayLocale                   varchar(50)  not null comment '最大发布日期（本地）',
    postedDateLocale                         varchar(30)  not null comment '本地时间，年月日',
    countryCode                              varchar(30)  not null comment '国家编码',
    country                                  varchar(30)  not null comment '国家中文名',
    sellerPrincipalRealname                  varchar(100) not null comment '卖家负责人真实姓名',
    currencyCode                             varchar(30)  not null comment '币种',
    currencyIcon                             varchar(30)  not null comment '币种符号',
    deferredSettlementAmount                 varchar(30)  not null comment '延期结算金额',
    sharedOtherFbaTransactionFees            varchar(30)  not null comment '分摊其他FBA交易费用',
    otherFbaTransactionFees                  varchar(30)  not null comment '其他FBA交易费用',
    sharedMcFbaFulfillmentFees               varchar(30)  not null comment '分摊MC FBA履行费用',
    mcFbaFulfillmentFees                     varchar(30)  not null comment 'MC FBA履行费用',
    sharedOtherTransactionFees               varchar(30)  not null comment '分摊其他交易费用',
    salesTotal                               varchar(30)  not null comment '销售总额',
    settlementSubtotal                       varchar(30)  not null comment '结算小计',
    otherFeeStr_1024469                      varchar(30)  not null comment '多平台头程回冲',
    primary key (dt, sid, transactionStatusCode)
) comment = '领星-利润报表-店铺维度-李仕春'
    partition by key (dt) partitions 3;
"""

ods_fc_gad_lx_profit_report_shop_i_d_field_list = {
    'dt': 'dt',
    'sid': 'sid',
    'storeName': 'storeName',
    'transactionStatus': 'transactionStatus',
    'transactionStatusCode': 'transactionStatusCode',
    'totalFbaAndFbmQuantity': 'totalFbaAndFbmQuantity',
    'totalFbaAndFbmAmount': 'totalFbaAndFbmAmount',
    'totalSalesQuantity': 'totalSalesQuantity',
    'fbaSalesQuantity': 'fbaSalesQuantity',
    'fbmSalesQuantity': 'fbmSalesQuantity',
    'totalReshipQuantity': 'totalReshipQuantity',
    'reshipFbmProductSalesQuantity': 'reshipFbmProductSalesQuantity',
    'reshipFbmProductSaleRefundsQuantity': 'reshipFbmProductSaleRefundsQuantity',
    'reshipFbaProductSalesQuantity': 'reshipFbaProductSalesQuantity',
    'reshipFbaProductSaleRefundsQuantity': 'reshipFbaProductSaleRefundsQuantity',
    'mcFbaFulfillmentFeesQuantity': 'mcFbaFulfillmentFeesQuantity',
    'cgAbsQuantity': 'cgAbsQuantity',
    'cgQuantity': 'cgQuantity',
    'fbaInventoryCreditQuantity': 'fbaInventoryCreditQuantity',
    'disposalQuantity': 'disposalQuantity',
    'removalQuantity': 'removalQuantity',
    'totalAdsSales': 'totalAdsSales',
    'adsSdSales': 'adsSdSales',
    'adsSpSales': 'adsSpSales',
    'sharedAdsSbSales': 'sharedAdsSbSales',
    'sharedAdsSbvSales': 'sharedAdsSbvSales',
    'totalAdsSalesQuantity': 'totalAdsSalesQuantity',
    'adsSdSalesQuantity': 'adsSdSalesQuantity',
    'adsSpSalesQuantity': 'adsSpSalesQuantity',
    'sharedAdsSbSalesQuantity': 'sharedAdsSbSalesQuantity',
    'sharedAdsSbvSalesQuantity': 'sharedAdsSbvSalesQuantity',
    'totalSalesAmount': 'totalSalesAmount',
    'fbaSaleAmount': 'fbaSaleAmount',
    'fbmSaleAmount': 'fbmSaleAmount',
    'shippingCredits': 'shippingCredits',
    'promotionalRebates': 'promotionalRebates',
    'fbaInventoryCredit': 'fbaInventoryCredit',
    'cashOnDelivery': 'cashOnDelivery',
    'otherInAmount': 'otherInAmount',
    'fbaLiquidationProceeds': 'fbaLiquidationProceeds',
    'fbaLiquidationProceedsAdjustments': 'fbaLiquidationProceedsAdjustments',
    'amazonShippingReimbursement': 'amazonShippingReimbursement',
    'safeTReimbursement': 'safeTReimbursement',
    'netcoTransaction': 'netcoTransaction',
    'reimbursements': 'reimbursements',
    'clawbacks': 'clawbacks',
    'sharedComminglingVatIncome': 'sharedComminglingVatIncome',
    'giftWrapCredits': 'giftWrapCredits',
    'guaranteeClaims': 'guaranteeClaims',
    'costOfPoIntegersGranted': 'costOfPoIntegersGranted',
    'others': 'others',
    'totalSalesRefunds': 'totalSalesRefunds',
    'fbaSalesRefunds': 'fbaSalesRefunds',
    'fbmSalesRefunds': 'fbmSalesRefunds',
    'shippingCreditRefunds': 'shippingCreditRefunds',
    'giftWrapCreditRefunds': 'giftWrapCreditRefunds',
    'chargebacks': 'chargebacks',
    'costOfPoIntegersReturned': 'costOfPoIntegersReturned',
    'promotionalRebateRefunds': 'promotionalRebateRefunds',
    'totalFeeRefunds': 'totalFeeRefunds',
    'sellingFeeRefunds': 'sellingFeeRefunds',
    'fbaTransactionFeeRefunds': 'fbaTransactionFeeRefunds',
    'refundAdministrationFees': 'refundAdministrationFees',
    'otherTransactionFeeRefunds': 'otherTransactionFeeRefunds',
    'refundForAdvertiser': 'refundForAdvertiser',
    'pointsAdjusted': 'pointsAdjusted',
    'shippingLabelRefunds': 'shippingLabelRefunds',
    'refundsQuantity': 'refundsQuantity',
    'refundsRate': 'refundsRate',
    'fbaReturnsQuantity': 'fbaReturnsQuantity',
    'fbaReturnsSaleableQuantity': 'fbaReturnsSaleableQuantity',
    'fbaReturnsUnsaleableQuantity': 'fbaReturnsUnsaleableQuantity',
    'fbaReturnsQuantityRate': 'fbaReturnsQuantityRate',
    'platformFee': 'platformFee',
    'totalFbaDeliveryFee': 'totalFbaDeliveryFee',
    'fbaDeliveryFee': 'fbaDeliveryFee',
    'sharedFbaTransactionCustomerReturnFee': 'sharedFbaTransactionCustomerReturnFee',
    'mcFbaDeliveryFee': 'mcFbaDeliveryFee',
    'otherTransactionFees': 'otherTransactionFees',
    'totalAdsCost': 'totalAdsCost',
    'adsSpCost': 'adsSpCost',
    'adsSbCost': 'adsSbCost',
    'adsSbvCost': 'adsSbvCost',
    'adsSdCost': 'adsSdCost',
    'sharedCostOfAdvertising': 'sharedCostOfAdvertising',
    'promotionFee': 'promotionFee',
    'sharedSubscriptionFee': 'sharedSubscriptionFee',
    'sharedLdFee': 'sharedLdFee',
    'sharedCouponFee': 'sharedCouponFee',
    'sharedEarlyReviewerProgramFee': 'sharedEarlyReviewerProgramFee',
    'sharedVineFee': 'sharedVineFee',
    'totalStorageFee': 'totalStorageFee',
    'fbaStorageFee': 'fbaStorageFee',
    'sharedFbaStorageFee': 'sharedFbaStorageFee',
    'longTermStorageFee': 'longTermStorageFee',
    'sharedLongTermStorageFee': 'sharedLongTermStorageFee',
    'sharedStorageRenewalBilling': 'sharedStorageRenewalBilling',
    'sharedFbaDisposalFee': 'sharedFbaDisposalFee',
    'sharedFbaRemovalFee': 'sharedFbaRemovalFee',
    'sharedFbaInboundTransportationProgramFee': 'sharedFbaInboundTransportationProgramFee',
    'sharedLabelingFee': 'sharedLabelingFee',
    'sharedPolybaggingFee': 'sharedPolybaggingFee',
    'sharedBubblewrapFee': 'sharedBubblewrapFee',
    'sharedTapingFee': 'sharedTapingFee',
    'sharedAwdProcessingFee': 'sharedAwdProcessingFee',
    'sharedAwdTransportationFee': 'sharedAwdTransportationFee',
    'sharedAwdStorageFee': 'sharedAwdStorageFee',
    'sharedFbaCustomerReturnFee': 'sharedFbaCustomerReturnFee',
    'sharedFbaInboundDefectFee': 'sharedFbaInboundDefectFee',
    'sharedFbaOverageFee': 'sharedFbaOverageFee',
    'sharedAmazonPartneredCarrierShipmentFee': 'sharedAmazonPartneredCarrierShipmentFee',
    'sharedFbaInboundConvenienceFee': 'sharedFbaInboundConvenienceFee',
    'sharedItemFeeAdjustment': 'sharedItemFeeAdjustment',
    'sharedOtherFbaInventoryFees': 'sharedOtherFbaInventoryFees',
    'fbaStorageFeeAccrual': 'fbaStorageFeeAccrual',
    'fbaStorageFeeAccrualDifference': 'fbaStorageFeeAccrualDifference',
    'longTermStorageFeeAccrual': 'longTermStorageFeeAccrual',
    'longTermStorageFeeAccrualDifference': 'longTermStorageFeeAccrualDifference',
    'sharedFbaIntegerernationalInboundFee': 'sharedFbaIntegerernationalInboundFee',
    'adjustments': 'adjustments',
    'totalPlatformOtherFee': 'totalPlatformOtherFee',
    'shippingLabelPurchases': 'shippingLabelPurchases',
    'sharedCarrierShippingLabelAdjustments': 'sharedCarrierShippingLabelAdjustments',
    'sharedLiquidationsFees': 'sharedLiquidationsFees',
    'sharedManualProcessingFee': 'sharedManualProcessingFee',
    'sharedOtherServiceFees': 'sharedOtherServiceFees',
    'sharedMfnPostageFee': 'sharedMfnPostageFee',
    'totalSalesTax': 'totalSalesTax',
    'taxCollected': 'taxCollected',
    'taxCollectedGiftWrap': 'taxCollectedGiftWrap',
    'taxCollectedShipping': 'taxCollectedShipping',
    'taxCollectedDiscount': 'taxCollectedDiscount',
    'taxCollectedProduct': 'taxCollectedProduct',
    'tcsIgstCollected': 'tcsIgstCollected',
    'tcsSgstCollected': 'tcsSgstCollected',
    'tcsCgstCollected': 'tcsCgstCollected',
    'sharedComminglingVatExpenses': 'sharedComminglingVatExpenses',
    'sharedTaxAdjustment': 'sharedTaxAdjustment',
    'salesTaxRefund': 'salesTaxRefund',
    'taxRefunded': 'taxRefunded',
    'taxRefundedGiftWrap': 'taxRefundedGiftWrap',
    'taxRefundedShipping': 'taxRefundedShipping',
    'taxRefundedDiscount': 'taxRefundedDiscount',
    'taxRefundedProduct': 'taxRefundedProduct',
    'tcsIgstRefunded': 'tcsIgstRefunded',
    'tcsSgstRefunded': 'tcsSgstRefunded',
    'tcsCgstRefunded': 'tcsCgstRefunded',
    'salesTaxWithheld': 'salesTaxWithheld',
    'refundTaxWithheld': 'refundTaxWithheld',
    'tdsSection194ONet': 'tdsSection194ONet',
    'cgPriceTotal': 'cgPriceTotal',
    'cgPriceAbsTotal': 'cgPriceAbsTotal',
    'hasCgPriceDetail': 'hasCgPriceDetail',
    'cgUnitPrice': 'cgUnitPrice',
    'proportionOfCg': 'proportionOfCg',
    'cgTransportCostsTotal': 'cgTransportCostsTotal',
    'hasCgTransportCostsDetail': 'hasCgTransportCostsDetail',
    'cgTransportUnitCosts': 'cgTransportUnitCosts',
    'proportionOfCgTransport': 'proportionOfCgTransport',
    'totalCost': 'totalCost',
    'proportionOfTotalCost': 'proportionOfTotalCost',
    'cgOtherCostsTotal': 'cgOtherCostsTotal',
    'cgOtherUnitCosts': 'cgOtherUnitCosts',
    'hasCgOtherCostsDetail': 'hasCgOtherCostsDetail',
    'proportionOfCgOtherCosts': 'proportionOfCgOtherCosts',
    'grossProfit': 'grossProfit',
    'grossRate': 'grossRate',
    'grossProfitIncome': 'grossProfitIncome',
    'grossProfitTax': 'grossProfitTax',
    'otherFeeStr': 'otherFeeStr',
    'customOrderFee': 'customOrderFee',
    'customOrderFeePrincipal': 'customOrderFeePrincipal',
    'customOrderFeeCommission': 'customOrderFeeCommission',
    'roi': 'roi',
    'postedDateDayLocale': 'postedDateDayLocale',
    'minPostedDateDayLocale': 'minPostedDateDayLocale',
    'maxPostedDateDayLocale': 'maxPostedDateDayLocale',
    'postedDateLocale': 'postedDateLocale',
    'countryCode': 'countryCode',
    'country': 'country',
    'sellerPrincipalRealname': 'sellerPrincipalRealname',
    'currencyCode': 'currencyCode',
    'currencyIcon': 'currencyIcon',
    'deferredSettlementAmount': 'deferredSettlementAmount',
    'sharedOtherFbaTransactionFees': 'sharedOtherFbaTransactionFees',
    'otherFbaTransactionFees': 'otherFbaTransactionFees',
    'sharedMcFbaFulfillmentFees': 'sharedMcFbaFulfillmentFees',
    'mcFbaFulfillmentFees': 'mcFbaFulfillmentFees',
    'sharedOtherTransactionFees': 'sharedOtherTransactionFees',
    'salesTotal': 'salesTotal',
    'settlementSubtotal': 'settlementSubtotal',
    'otherFeeStr_1024469': 'otherFeeStr_1024469',
}

# 领星-亚马逊结算中心
ods_gsm_lx_amz_settlement_summary = "ods_prod.ods_gsm_lx_amz_settlement_summary_i_d"
ods_fc_gad_lx_settlement_summary_i_d = """
create table if not exists ods_prod.ods_gsm_lx_amz_settlement_summary_i_d
(
    dt                             varchar(15)  not null comment 'dt(结算开始时间)',
    id                             varchar(30)  not null comment '结算编号',
    sid                            varchar(15)  not null comment '店铺id',
    storeName                      varchar(50)  not null comment '店铺名',
    countryCode                    varchar(10)  not null comment '国家',
    customerCountryCode            varchar(10)  not null comment '国家code',
    sellerId                       varchar(50)  not null comment '亚马逊账号id',
    accountType                    varchar(30)  not null comment '报告类型',
    processingStatus               varchar(30)  not null comment '结算状态：Open 待结算;Pending 结算中;Closed 已结算',
    fundTransferStatus             varchar(30)  not null comment '转账状态：Succeeded 已转账;Failed 失败;Processing 转账中;Unknown 未知',
    reconciliationResult           varchar(30)  not null comment '对账结果',
    reconciliationResultMap        varchar(255) not null comment '对账详情',
    originalTotalCurrencyCode      varchar(15)  not null comment '应收币种',
    originalTotalCurrencyAmount    varchar(15)  not null comment '应收金额',
    convertedTotalCurrencyCode     varchar(15)  not null comment '转账币种',
    convertedTotalCurrencyAmount   varchar(15)  not null comment '转账金额',
    comment                        varchar(15)  not null comment '备注',
    financialEventGroupStartLocale varchar(50)  not null comment '结算开始时间',
    financialEventGroupEndLocale   varchar(50)  not null comment '结算结束时间',
    fundTransferDate               varchar(50)  not null comment '转账日期',
    fundTransferDateLocale         varchar(50)  not null comment '转账日期-当地',
    settlementId                   varchar(50)  not null comment 'settlementId',
    accountTail                    varchar(50)  not null comment '银行尾号',
    traceId                        varchar(50)  not null comment '追踪编号',
    financialEventGroupId          varchar(100) not null comment '财务事件组id',
    sale                           varchar(255) not null comment '销售',
    refund                         varchar(255) not null comment '退款',
    pay                            varchar(255) not null comment '支出',
    transfer                       varchar(255) not null comment '转账',
    bucket                         varchar(50)  not null comment 'bucket',
    s3FileKey                      varchar(255)  not null comment 's3_file_key',
    originCurrencyIcon             varchar(15)  not null comment '应收币种符号',
    convertCurrencyIcon            varchar(15)  not null comment '转账币种符号',
    accountInfo                    varchar(50)  not null comment '店铺账号信息',
    primary key (dt, id)
) comment = '领星-财务-亚马逊结算汇总'
    partition by key (dt) partitions 3;
"""
ods_fc_gad_lx_settlement_summary_i_d_field_list = [
    "dt",
    "id",
    "sid",
    "storeName",
    "countryCode",
    "customerCountryCode",
    "sellerId",
    "accountType",
    "processingStatus",
    "fundTransferStatus",
    "reconciliationResult",
    "reconciliationResultMap",
    "originalTotalCurrencyCode",
    "originalTotalCurrencyAmount",
    "convertedTotalCurrencyCode",
    "convertedTotalCurrencyAmount",
    "comment",
    "financialEventGroupStartLocale",
    "financialEventGroupEndLocale",
    "fundTransferDate",
    "fundTransferDateLocale",
    "settlementId",
    "accountTail",
    "traceId",
    "financialEventGroupId",
    "sale",
    "refund",
    "pay",
    "transfer",
    "bucket",
    "s3FileKey",
    "originCurrencyIcon",
    "convertCurrencyIcon",
    "accountInfo",
]

# 领星-利润报表-msku
profit_report_statement_data_table = 'ods_prod.ods_gsm_lx_profit_statement_msku_i_d'
ods_gsm_lx_profit_msku_statement_i_d = """
CREATE TABLE if not exists ods_prod.ods_gsm_lx_profit_statement_msku_i_d
(
    dt                                             varchar(15)  NOT NULL COMMENT '当前时间',
    totalFbaAndFbmQuantity                         varchar(20)  NOT NULL COMMENT 'fba和fbm销量加总，用于计算占比(销量)',
    totalFbaAndFbmAmount                           varchar(20)  NOT NULL COMMENT 'fba和fbm销售额加总，用于计算占比(销售额)',
    totalSalesQuantity                             varchar(20)  NOT NULL COMMENT '销量',
    fbaSalesQuantity                               varchar(20)  NOT NULL COMMENT 'FBA销量',
    fbmSalesQuantity                               varchar(20)  NOT NULL COMMENT 'FBM销量',
    totalReshipQuantity                            varchar(20)  NOT NULL COMMENT '补（换）数量',
    reshipFbmProductSalesQuantity                  varchar(20)  NOT NULL COMMENT 'fbm 补（换）数量',
    reshipFbmProductSaleRefundsQuantity            varchar(20)  NOT NULL COMMENT 'fbm 补（换）退回数量',
    reshipFbaProductSalesQuantity                  varchar(20)  NOT NULL COMMENT 'fba 补（换）数量',
    reshipFbaProductSaleRefundsQuantity            varchar(20)  NOT NULL COMMENT 'fba 补（换）退回数量',
    mcFbaFulfillmentFeesQuantity                   varchar(20)  NOT NULL COMMENT '多渠道销量',
    cgAbsQuantity                                  varchar(20)  NOT NULL COMMENT 'cgAbsQuantity',
    cgQuantity                                     varchar(20)  NOT NULL COMMENT 'cgQuantity',
    fbaInventoryCreditQuantity                     varchar(20)  NOT NULL COMMENT 'FBA库存赔偿数量',
    disposalQuantity                               varchar(20)  NOT NULL COMMENT '销毁数量',
    removalQuantity                                varchar(20)  NOT NULL COMMENT '移除数量',
    totalAdsSales                                  varchar(20)  NOT NULL COMMENT '广告销售额',
    adsSdSales                                     varchar(20)  NOT NULL COMMENT 'sd广告销售额',
    adsSpSales                                     varchar(20)  NOT NULL COMMENT 'SP广告销售额',
    sharedAdsSbSales                               varchar(20)  NOT NULL COMMENT 'SB广告销售额',
    sharedAdsSbvSales                              varchar(20)  NOT NULL COMMENT 'sbv广告销售额',
    totalAdsSalesQuantity                          varchar(20)  NOT NULL COMMENT '广告销量',
    adsSdSalesQuantity                             varchar(20)  NOT NULL COMMENT 'sd广告销量',
    adsSpSalesQuantity                             varchar(20)  NOT NULL COMMENT 'SP广告销量',
    sharedAdsSbSalesQuantity                       varchar(20)  NOT NULL COMMENT 'SB广告销量',
    sharedAdsSbvSalesQuantity                      varchar(20)  NOT NULL COMMENT 'sbv广告销量',
    totalSalesAmount                               varchar(20)  NOT NULL COMMENT '销售额',
    fbaSaleAmount                                  varchar(20)  NOT NULL COMMENT 'FBA销售额',
    fbmSaleAmount                                  varchar(20)  NOT NULL COMMENT 'FBM销售额',
    shippingCredits                                varchar(20)  NOT NULL COMMENT '卖家运费',
    promotionalRebates                             varchar(20)  NOT NULL COMMENT '促销折扣',
    fbaInventoryCredit                             varchar(20)  NOT NULL COMMENT 'FBA库存赔偿',
    cashOnDelivery                                 varchar(20)  NOT NULL COMMENT 'COD',
    otherInAmount                                  varchar(20)  NOT NULL COMMENT '其他收入',
    fbaLiquidationProceeds                         varchar(20)  NOT NULL COMMENT '清算收入',
    fbaLiquidationProceedsAdjustments              varchar(20)  NOT NULL COMMENT '清算调整',
    amazonShippingReimbursement                    varchar(20)  NOT NULL COMMENT '亚马逊运费赔偿',
    safeTReimbursement                             varchar(20)  NOT NULL COMMENT 'Safe-T索赔',
    netcoTransaction                               varchar(20)  NOT NULL COMMENT 'Netco交易',
    reimbursements                                 varchar(20)  NOT NULL COMMENT '赔偿收入',
    clawbacks                                      varchar(20)  NOT NULL COMMENT '追索收入',
    sharedComminglingVatIncome                     varchar(20)  NOT NULL COMMENT '混合VAT收入',
    giftWrapCredits                                varchar(20)  NOT NULL COMMENT '包装收入',
    guaranteeClaims                                varchar(20)  NOT NULL COMMENT '买家交易保障索赔额',
    costOfPoIntegersGranted                        varchar(20)  NOT NULL COMMENT '积分抵减收入',
    others                                         varchar(20)  NOT NULL COMMENT 'others',
    totalSalesRefunds                              varchar(20)  NOT NULL COMMENT '收入退款额',
    fbaSalesRefunds                                varchar(20)  NOT NULL COMMENT 'FBA销售退款额',
    fbmSalesRefunds                                varchar(20)  NOT NULL COMMENT 'FBM销售退款额',
    shippingCreditRefunds                          varchar(20)  NOT NULL COMMENT '买家运费退款额',
    giftWrapCreditRefunds                          varchar(20)  NOT NULL COMMENT '买家包装退款额',
    chargebacks                                    varchar(20)  NOT NULL COMMENT '买家拒付',
    costOfPoIntegersReturned                       varchar(20)  NOT NULL COMMENT '积分抵减退回',
    promotionalRebateRefunds                       varchar(20)  NOT NULL COMMENT '促销折扣退款额',
    totalFeeRefunds                                varchar(20)  NOT NULL COMMENT '费用退款额',
    sellingFeeRefunds                              varchar(20)  NOT NULL COMMENT '平台费退款额',
    fbaTransactionFeeRefunds                       varchar(20)  NOT NULL COMMENT '发货费退款额',
    refundAdministrationFees                       varchar(20)  NOT NULL COMMENT '交易费用退款额',
    otherTransactionFeeRefunds                     varchar(20)  NOT NULL COMMENT '其他订单费退款额',
    refundForAdvertiser                            varchar(20)  NOT NULL COMMENT '广告退款额',
    pointsAdjusted                                 varchar(20)  NOT NULL COMMENT '积分费用',
    shippingLabelRefunds                           varchar(20)  NOT NULL COMMENT '运输标签费退款',
    refundsQuantity                                varchar(20)  NOT NULL COMMENT '退款量',
    refundsRate                                    varchar(20)  NOT NULL COMMENT '退款率',
    fbaReturnsQuantity                             varchar(20)  NOT NULL COMMENT '退货量',
    fbaReturnsSaleableQuantity                     varchar(20)  NOT NULL COMMENT '退货量（可售）',
    fbaReturnsUnsaleableQuantity                   varchar(20)  NOT NULL COMMENT '退货量（不可售）',
    fbaReturnsQuantityRate                         varchar(20)  NOT NULL COMMENT '退货率',
    platformFee                                    varchar(20)  NOT NULL COMMENT '平台费',
    totalFbaDeliveryFee                            varchar(20)  NOT NULL COMMENT 'FBA发货费',
    fbaDeliveryFee                                 varchar(20)  NOT NULL COMMENT 'FBA',
    mcFbaDeliveryFee                               varchar(20)  NOT NULL COMMENT 'FBA发货费(多渠道)',
    otherTransactionFees                           varchar(20)  NOT NULL COMMENT '其他订单费用',
    totalAdsCost                                   varchar(20)  NOT NULL COMMENT '广告费',
    adsSpCost                                      varchar(20)  NOT NULL COMMENT 'SP广告',
    adsSbCost                                      varchar(20)  NOT NULL COMMENT 'SB广告',
    adsSbvCost                                     varchar(20)  NOT NULL COMMENT 'SBV广告',
    adsSdCost                                      varchar(20)  NOT NULL COMMENT 'SD广告',
    sharedCostOfAdvertising                        varchar(20)  NOT NULL COMMENT '差异分摊',
    promotionFee                                   varchar(20)  NOT NULL COMMENT '推广费',
    sharedSubscriptionFee                          varchar(20)  NOT NULL COMMENT '订阅费',
    sharedLdFee                                    varchar(20)  NOT NULL COMMENT '秒杀费',
    sharedCouponFee                                varchar(20)  NOT NULL COMMENT '优惠券',
    sharedEarlyReviewerProgramFee                  varchar(20)  NOT NULL COMMENT '早期评论人计划',
    sharedVineFee                                  varchar(20)  NOT NULL COMMENT 'vine',
    totalStorageFee                                varchar(20)  NOT NULL COMMENT 'FBA仓储费',
    fbaStorageFee                                  varchar(20)  NOT NULL COMMENT '月仓储费',
    sharedFbaStorageFee                            varchar(20)  NOT NULL COMMENT '月仓储费差异',
    longTermStorageFee                             varchar(20)  NOT NULL COMMENT '长期仓储费',
    sharedLongTermStorageFee                       varchar(20)  NOT NULL COMMENT '长期仓储费差异',
    sharedStorageRenewalBilling                    varchar(20)  NOT NULL COMMENT '库存续订费用',
    sharedFbaDisposalFee                           varchar(20)  NOT NULL COMMENT 'FBA销毁费',
    sharedFbaRemovalFee                            varchar(20)  NOT NULL COMMENT 'FBA移除费',
    sharedFbaInboundTransportationProgramFee       varchar(20)  NOT NULL COMMENT '入仓手续费',
    sharedLabelingFee                              varchar(20)  NOT NULL COMMENT '标签费',
    sharedPolybaggingFee                           varchar(20)  NOT NULL COMMENT '塑料包装费',
    sharedBubblewrapFee                            varchar(20)  NOT NULL COMMENT '泡沫包装费',
    sharedTapingFee                                varchar(20)  NOT NULL COMMENT 'sharedTapingFee',
    sharedFbaCustomerReturnFee                     varchar(20)  NOT NULL COMMENT 'FBA卖家退回费',
    sharedFbaInboundDefectFee                      varchar(20)  NOT NULL COMMENT '计划外服务费',
    sharedFbaOverageFee                            varchar(20)  NOT NULL COMMENT '超量仓储费',
    sharedAmazonPartneredCarrierShipmentFee        varchar(20)  NOT NULL COMMENT '合作承运费',
    sharedFbaInboundConvenienceFee                 varchar(20)  NOT NULL COMMENT '合仓费',
    sharedItemFeeAdjustment                        varchar(20)  NOT NULL COMMENT '库存调整费用',
    sharedOtherFbaInventoryFees                    varchar(20)  NOT NULL COMMENT '其他仓储费',
    fbaStorageFeeAccrual                           varchar(20)  NOT NULL COMMENT '月仓储费-本月计提',
    fbaStorageFeeAccrualDifference                 varchar(20)  NOT NULL COMMENT '月仓储费-上月冲销',
    longTermStorageFeeAccrual                      varchar(20)  NOT NULL COMMENT '长期仓储费-本月计提',
    longTermStorageFeeAccrualDifference            varchar(20)  NOT NULL COMMENT '长期仓储费-上月冲销',
    sharedFbaIntegerernationalInboundFee           varchar(20)  NOT NULL COMMENT 'FBA国际物流货运费',
    adjustments                                    varchar(20)  NOT NULL COMMENT '调整费用',
    totalPlatformOtherFee                          varchar(20)  NOT NULL COMMENT '平台其他费',
    shippingLabelPurchases                         varchar(20)  NOT NULL COMMENT '运输标签费',
    sharedCarrierShippingLabelAdjustments          varchar(20)  NOT NULL COMMENT '承运人装运标签调整费',
    sharedLiquidationsFees                         varchar(20)  NOT NULL COMMENT '清算费',
    sharedManualProcessingFee                      varchar(20)  NOT NULL COMMENT '人工处理费用',
    sharedOtherServiceFees                         varchar(20)  NOT NULL COMMENT '其他服务费',
    totalSalesTax                                  varchar(20)  NOT NULL COMMENT '销售税',
    taxCollected                                   varchar(20)  NOT NULL COMMENT '销售税-VAT/GST',
    tcsIgstCollected                               varchar(20)  NOT NULL COMMENT 'TCS-IGST',
    tcsSgstCollected                               varchar(20)  NOT NULL COMMENT 'TCS-SGST',
    tcsCgstCollected                               varchar(20)  NOT NULL COMMENT 'TCS-CGST',
    sharedComminglingVatExpenses                   varchar(20)  NOT NULL COMMENT '混合VAT',
    sharedTaxAdjustment                            varchar(20)  NOT NULL COMMENT '分摊税款调整',
    salesTaxRefund                                 varchar(20)  NOT NULL COMMENT '销售税退款额',
    taxRefunded                                    varchar(20)  NOT NULL COMMENT '销售税退款额-VAT/GST',
    tcsIgstRefunded                                varchar(20)  NOT NULL COMMENT 'TCS-IGST',
    tcsSgstRefunded                                varchar(20)  NOT NULL COMMENT 'TCS-SGST',
    tcsCgstRefunded                                varchar(20)  NOT NULL COMMENT 'TCS-CGST',
    salesTaxWithheld                               varchar(20)  NOT NULL COMMENT '市场税',
    refundTaxWithheld                              varchar(20)  NOT NULL COMMENT '市场税退款额',
    tdsSection194ONet                              varchar(20)  NOT NULL COMMENT '混合网络费',
    cgPriceTotal                                   varchar(20)  NOT NULL COMMENT '采购成本',
    cgPriceAbsTotal                                varchar(20)  NOT NULL COMMENT '采购绝对成本',
    hasCgPriceDetail                               varchar(20)  NOT NULL COMMENT '是否有采购成本明细',
    cgUnitPrice                                    varchar(20)  NOT NULL COMMENT '采购均价',
    proportionOfCg                                 varchar(20)  NOT NULL COMMENT '采购占比',
    cgTransportCostsTotal                          varchar(20)  NOT NULL COMMENT '头程成本',
    hasCgTransportCostsDetail                      varchar(20)  NOT NULL COMMENT '是否有物流（头程）成本明细',
    cgTransportUnitCosts                           varchar(20)  NOT NULL COMMENT '头程均价',
    proportionOfCgTransport                        varchar(20)  NOT NULL COMMENT '头程占比',
    totalCost                                      varchar(20)  NOT NULL COMMENT '合计成本',
    proportionOfTotalCost                          varchar(20)  NOT NULL COMMENT '合计成本占比',
    cgOtherCostsTotal                              varchar(20)  NOT NULL COMMENT '其他成本',
    cgOtherUnitCosts                               varchar(20)  NOT NULL COMMENT '其他均价',
    hasCgOtherCostsDetail                          varchar(20)  NOT NULL COMMENT '是否有其他成本明细',
    proportionOfCgOtherCosts                       varchar(20)  NOT NULL COMMENT '其他成本占比',
    grossProfit                                    varchar(20)  NOT NULL COMMENT '利润-毛利润',
    grossRate                                      varchar(20)  NOT NULL COMMENT '利润-毛利率',
    grossProfitIncome                              varchar(20)  NOT NULL COMMENT '毛利润总额',
    otherFeeStr                                    varchar(600) NOT NULL COMMENT '其他费信息',
    customOrderFee                                 varchar(20)  NOT NULL COMMENT '自定义订单费用',
    customOrderFeePrincipal                        varchar(20)  NOT NULL COMMENT 'customOrderFeePrincipal',
    customOrderFeeCommission                       varchar(20)  NOT NULL COMMENT 'customOrderFeeCommission',
    id                                             varchar(20)  NOT NULL COMMENT 'id',
    sid                                            varchar(10)  NOT NULL COMMENT '店铺id',
    reportDateMonth                                varchar(10)  NOT NULL COMMENT 'reportDateMonth',
    postedDateLocale                               varchar(10)  NOT NULL COMMENT '本地时间，年月日',
    isDisplayDetail                                varchar(10)  NOT NULL COMMENT 'isDisplayDetail',
    smallImageUrl                                  varchar(300) NOT NULL COMMENT '图片',
    msku                                           varchar(60)  NOT NULL COMMENT 'msku',
    asin                                           varchar(80)  NOT NULL COMMENT 'asin',
    parentAsin                                     varchar(80)  NOT NULL COMMENT '父类asin',
    storeName                                      varchar(80)  NOT NULL COMMENT '店铺名',
    country                                        varchar(30)  NOT NULL COMMENT '国家',
    countryCode                                    varchar(20)  NOT NULL COMMENT '国家币种',
    localName                                      varchar(80)  NOT NULL COMMENT '颜色；尺码',
    localSku                                       varchar(80)  NOT NULL COMMENT '本地sku',
    itemName                                       varchar(300) NOT NULL COMMENT '名称',
    model                                          varchar(70)  NOT NULL COMMENT '型号',
    principalRealname                              varchar(150) NOT NULL COMMENT '负责人',
    productDeveloperRealname                       varchar(150) NOT NULL COMMENT '开发负责人',
    categoryName                                   varchar(20)  NOT NULL COMMENT '鞋类',
    brandName                                      varchar(30)  NOT NULL COMMENT '品牌名',
    currencyCode                                   varchar(8)   NOT NULL COMMENT '币种',
    currencyIcon                                   varchar(8)   NOT NULL COMMENT '币种符号',
    listingTagIds                                  text         NOT NULL COMMENT '列表id',
    customized_other_fee                           varchar(30)  NOT NULL COMMENT '自定义_其他费',
    customized_direct_shipping_fee                 varchar(30)  NOT NULL COMMENT '自定义_直邮发货运费',
    customized_fbm_order_fee                       varchar(30)  NOT NULL COMMENT '自定义_FBM订单发货成本',
    customized_fbm_order_return_fee                varchar(30)  NOT NULL COMMENT '自定义_FBM订单退货成本',
    customized_fba_adjustment_fee                  varchar(30)  NOT NULL COMMENT '自定义_FBA广告费用调整',
    customized_buyout_subsidy                      varchar(30)  NOT NULL COMMENT '自定义_出清补贴',
    customized_new_product_subsidy                 varchar(30)  NOT NULL COMMENT '自定义_新品补贴',
    customized_provision_price                     varchar(30)  NOT NULL COMMENT '自定义_跌价准备金计提',
    customized_provision_price_decreases           varchar(30)  NOT NULL COMMENT '自定义_跌价准备金回冲',
    customized_settlement_price_difference_subsidy varchar(30)  NOT NULL COMMENT '自定义_特殊结算价差价补贴',
    customized_inbound_warehouse_outbound_fees     varchar(30)  NOT NULL COMMENT '自定义_入境外仓出库操作费',
    taxCollectedGiftWrap                           varchar(10)  NOT NULL COMMENT '税费_礼品包装税',
    taxCollectedShipping                           varchar(10)  NOT NULL COMMENT '税费_买家运费税',
    taxCollectedDiscount                           varchar(10)  NOT NULL COMMENT '税费_促销折扣税',
    taxCollectedProduct                            varchar(10)  NOT NULL COMMENT '税费_商品价格税',
    taxRefundedGiftWrap                            varchar(10)  NOT NULL COMMENT '税费_礼品包装税(退款额)',
    taxRefundedShipping                            varchar(10)  NOT NULL COMMENT '税费_买家运费税(退款额)',
    taxRefundedDiscount                            varchar(10)  NOT NULL COMMENT '税费_促销折扣税(退款额)',
    taxRefundedProduct                             varchar(10)  NOT NULL COMMENT '税费_商品价格税(退款额)',
    customized_multi_platform_headway_backflush    varchar(30)  NOT NULL COMMENT '自定义_多平台头程回冲',
    customized_multi_platform_tailrace_backflush   varchar(30)  NOT NULL COMMENT '自定义_多平台尾程回冲',
    customized_multi_platform_cost_backflush       varchar(30)  NOT NULL COMMENT '自定义_多平台货本回冲',
    customized_subsidy_peak_storage_fees           varchar(30)  NOT NULL COMMENT '自定义_旺季仓储费补贴',
    customized_subsidy_promotion_fees              varchar(30)  NOT NULL COMMENT '自定义_推广费补贴',
    customized_amazon_seller_growth_fee            varchar(30)  NOT NULL COMMENT '自定义_亚马逊卖家成长服务费',
    customized_hero_product_commission_fee         varchar(30)  NOT NULL COMMENT '自定义_极致大单品抽成',
    PRIMARY KEY (dt, msku, sid)
) COMMENT ='领星-利润报表(msku维度)-张致富'
    partition by key (dt) partitions 3;
                    """

ods_fc_gad_lx_profit_msku_statement_i_d_field_list = ['dt', 'totalFbaAndFbmQuantity', 'totalFbaAndFbmAmount',
                                                      'totalSalesQuantity', 'fbaSalesQuantity', 'fbmSalesQuantity',
                                                      'totalReshipQuantity', 'reshipFbmProductSalesQuantity',
                                                      'reshipFbmProductSaleRefundsQuantity',
                                                      'reshipFbaProductSalesQuantity',
                                                      'reshipFbaProductSaleRefundsQuantity',
                                                      'mcFbaFulfillmentFeesQuantity', 'cgAbsQuantity', 'cgQuantity',
                                                      'fbaInventoryCreditQuantity', 'disposalQuantity',
                                                      'removalQuantity', 'totalAdsSales', 'adsSdSales', 'adsSpSales',
                                                      'sharedAdsSbSales', 'sharedAdsSbvSales', 'totalAdsSalesQuantity',
                                                      'adsSdSalesQuantity', 'adsSpSalesQuantity',
                                                      'sharedAdsSbSalesQuantity', 'sharedAdsSbvSalesQuantity',
                                                      'totalSalesAmount', 'fbaSaleAmount', 'fbmSaleAmount',
                                                      'shippingCredits', 'promotionalRebates', 'fbaInventoryCredit',
                                                      'cashOnDelivery', 'otherInAmount', 'fbaLiquidationProceeds',
                                                      'fbaLiquidationProceedsAdjustments',
                                                      'amazonShippingReimbursement', 'safeTReimbursement',
                                                      'netcoTransaction', 'reimbursements', 'clawbacks',
                                                      'sharedComminglingVatIncome', 'giftWrapCredits',
                                                      'guaranteeClaims', 'costOfPoIntegersGranted', 'others',
                                                      'totalSalesRefunds', 'fbaSalesRefunds', 'fbmSalesRefunds',
                                                      'shippingCreditRefunds', 'giftWrapCreditRefunds', 'chargebacks',
                                                      'costOfPoIntegersReturned', 'promotionalRebateRefunds',
                                                      'totalFeeRefunds', 'sellingFeeRefunds',
                                                      'fbaTransactionFeeRefunds', 'refundAdministrationFees',
                                                      'otherTransactionFeeRefunds', 'refundForAdvertiser',
                                                      'pointsAdjusted', 'shippingLabelRefunds', 'refundsQuantity',
                                                      'refundsRate', 'fbaReturnsQuantity', 'fbaReturnsSaleableQuantity',
                                                      'fbaReturnsUnsaleableQuantity', 'fbaReturnsQuantityRate',
                                                      'platformFee', 'totalFbaDeliveryFee', 'fbaDeliveryFee',
                                                      'mcFbaDeliveryFee', 'otherTransactionFees', 'totalAdsCost',
                                                      'adsSpCost', 'adsSbCost', 'adsSbvCost', 'adsSdCost',
                                                      'sharedCostOfAdvertising', 'promotionFee',
                                                      'sharedSubscriptionFee', 'sharedLdFee', 'sharedCouponFee',
                                                      'sharedEarlyReviewerProgramFee', 'sharedVineFee',
                                                      'totalStorageFee', 'fbaStorageFee', 'sharedFbaStorageFee',
                                                      'longTermStorageFee', 'sharedLongTermStorageFee',
                                                      'sharedStorageRenewalBilling', 'sharedFbaDisposalFee',
                                                      'sharedFbaRemovalFee', 'sharedFbaInboundTransportationProgramFee',
                                                      'sharedLabelingFee', 'sharedPolybaggingFee',
                                                      'sharedBubblewrapFee', 'sharedTapingFee',
                                                      'sharedFbaCustomerReturnFee', 'sharedFbaInboundDefectFee',
                                                      'sharedFbaOverageFee', 'sharedAmazonPartneredCarrierShipmentFee',
                                                      'sharedFbaInboundConvenienceFee', 'sharedItemFeeAdjustment',
                                                      'sharedOtherFbaInventoryFees', 'fbaStorageFeeAccrual',
                                                      'fbaStorageFeeAccrualDifference', 'longTermStorageFeeAccrual',
                                                      'longTermStorageFeeAccrualDifference',
                                                      'sharedFbaIntegerernationalInboundFee', 'adjustments',
                                                      'totalPlatformOtherFee', 'shippingLabelPurchases',
                                                      'sharedCarrierShippingLabelAdjustments', 'sharedLiquidationsFees',
                                                      'sharedManualProcessingFee', 'sharedOtherServiceFees',
                                                      'totalSalesTax', 'taxCollected', 'tcsIgstCollected',
                                                      'tcsSgstCollected', 'tcsCgstCollected',
                                                      'sharedComminglingVatExpenses', 'sharedTaxAdjustment',
                                                      'salesTaxRefund', 'taxRefunded', 'tcsIgstRefunded',
                                                      'tcsSgstRefunded', 'tcsCgstRefunded', 'salesTaxWithheld',
                                                      'refundTaxWithheld', 'tdsSection194ONet', 'cgPriceTotal',
                                                      'cgPriceAbsTotal', 'hasCgPriceDetail', 'cgUnitPrice',
                                                      'proportionOfCg', 'cgTransportCostsTotal',
                                                      'hasCgTransportCostsDetail', 'cgTransportUnitCosts',
                                                      'proportionOfCgTransport', 'totalCost', 'proportionOfTotalCost',
                                                      'cgOtherCostsTotal', 'cgOtherUnitCosts', 'hasCgOtherCostsDetail',
                                                      'proportionOfCgOtherCosts', 'grossProfit', 'grossRate',
                                                      'grossProfitIncome', 'otherFeeStr', 'customOrderFee',
                                                      'customOrderFeePrincipal', 'customOrderFeeCommission', 'id',
                                                      'sid', 'reportDateMonth', 'postedDateLocale', 'isDisplayDetail',
                                                      'smallImageUrl', 'msku', 'asin', 'parentAsin', 'storeName',
                                                      'country', 'countryCode', 'localName', 'localSku', 'itemName',
                                                      'model', 'principalRealname', 'productDeveloperRealname',
                                                      'categoryName', 'brandName', 'currencyCode', 'currencyIcon',
                                                      'listingTagIds', 'customized_other_fee',
                                                      'customized_direct_shipping_fee', 'customized_fbm_order_fee',
                                                      'customized_fbm_order_return_fee',
                                                      'customized_fba_adjustment_fee', 'customized_buyout_subsidy',
                                                      'customized_new_product_subsidy', 'customized_provision_price',
                                                      'customized_provision_price_decreases',
                                                      'customized_settlement_price_difference_subsidy',
                                                      'customized_inbound_warehouse_outbound_fees',
                                                      'taxCollectedGiftWrap',
                                                      'taxCollectedShipping', 'taxCollectedDiscount',
                                                      'taxCollectedProduct', 'taxRefundedGiftWrap',
                                                      'taxRefundedShipping', 'taxRefundedDiscount',
                                                      'taxRefundedProduct',
                                                      'customized_multi_platform_headway_backflush',
                                                      'customized_multi_platform_tailrace_backflush',
                                                      'customized_multi_platform_cost_backflush',
                                                      'customized_subsidy_peak_storage_fees',
                                                      'customized_subsidy_promotion_fees',
                                                      'customized_amazon_seller_growth_fee',
                                                      'customized_hero_product_commission_fee'
                                                      ]

profit_report_staetment_cost_db_table = 'ods_prod.ods_gsm_lx_profit_statement_msku_cost_detail_i_d'

ods_gsm_lx_profit_msku_statement_cost_detail_i_d = """
create table if not exists ods_prod.ods_gsm_lx_profit_statement_msku_cost_detail_i_d
(
    dt                                             varchar(15) not null comment '当前时间',
    sid                                            varchar(20) not null comment '店铺',
    msku                                           varchar(60) not null comment 'msku',
    currencyCode                                   varchar(20) not null comment '币种',
    other_cost_fba_amazon_quantity                 varchar(20) not null comment '其他成本-FBA亚马逊销售订单数量',
    other_cost_fba_amazon_amount                   varchar(20) not null comment '其他成本-FBA亚马逊销售订单销额',
    other_cost_fba_multichannel_quantity           varchar(20) not null comment '其他成本-FBA多渠道销售订单数量',
    other_cost_fba_multichannel_amount             varchar(20) not null comment '其他成本-FBA多渠道销售订单数销额',
    other_cost_fba_remove_quantity                 varchar(20) not null comment '其他成本-FBA移除数量',
    other_cost_fba_remove_amount                   varchar(20) not null comment '其他成本-FBA移除销额',
    other_cost_fba_replacement_quantity            varchar(20) not null comment '其他成本-FBA补发货销售数量',
    other_cost_fba_replacement_amount              varchar(20) not null comment '其他成本-FBA补发货销售销额',
    other_cost_fba_stock_out_quantity              varchar(20) not null comment '其他成本-FBA盘点出库数量',
    other_cost_fba_stock_out_amount                varchar(20) not null comment '其他成本-FBA盘点出库销额',
    other_cost_fba_unsingle_return_quantity        varchar(20) not null comment '其他成本-FBA无源单销售退货数量',
    other_cost_fba_unsingle_return_amount          varchar(20) not null comment '其他成本-FBA无源单销售退货销额',
    other_cost_fba_stock_in_quantity               varchar(20) not null comment '其他成本-FBA盘点入库数量',
    other_cost_fba_stock_in_amount                 varchar(20) not null comment '其他成本-FBA盘点入库销额',
    other_cost_fba_single_return_quantity          varchar(20) not null comment '其他成本-FBA有源单销售退货数量',
    other_cost_fba_single_return_amount            varchar(20) not null comment '其他成本-FBA有源单销售退货销额',
    other_cost_amazon_sale_outstock_quantity       varchar(20) not null comment '其他成本-自发货亚马逊销售出库数量',
    other_cost_amazon_sale_outstock_amount         varchar(20) not null comment '其他成本-自发货亚马逊销售出库销额',
    cg_price_fba_amazon_quantity                   varchar(20) not null comment '采购成本-FBA亚马逊销售订单数量',
    cg_price_fba_amazon_amount                     varchar(20) not null comment '采购成本-FBA亚马逊销售订单销额',
    cg_price_fba_multichannel_quantity             varchar(20) not null comment '采购成本-FBA多渠道销售订单数量',
    cg_price_fba_multichannel_amount               varchar(20) not null comment '采购成本-FBA多渠道销售订单数销额',
    cg_price_fba_remove_quantity                   varchar(20) not null comment '采购成本-FBA移除数量',
    cg_price_fba_remove_amount                     varchar(20) not null comment '采购成本-FBA移除销额',
    cg_price_fba_replacement_quantity              varchar(20) not null comment '采购成本-FBA补发货销售数量',
    cg_price_fba_replacement_amount                varchar(20) not null comment '采购成本-FBA补发货销售销额',
    cg_price_fba_stock_out_quantity                varchar(20) not null comment '采购成本-FBA盘点出库数量',
    cg_price_fba_stock_out_amount                  varchar(20) not null comment '采购成本-FBA盘点出库销额',
    cg_price_fba_unsingle_return_quantity          varchar(20) not null comment '采购成本-FBA无源单销售退货数量',
    cg_price_fba_unsingle_return_amount            varchar(20) not null comment '采购成本-FBA无源单销售退货销额',
    cg_price_fba_stock_in_quantity                 varchar(20) not null comment '采购成本-FBA盘点入库数量',
    cg_price_fba_stock_in_amount                   varchar(20) not null comment '采购成本-FBA盘点入库销额',
    cg_price_fba_single_return_quantity            varchar(20) not null comment '采购成本-FBA有源单销售退货数量',
    cg_price_fba_single_return_amount              varchar(20) not null comment '采购成本-FBA有源单销售退货销额',
    cg_price_amazon_sale_outstock_quantity         varchar(20) not null comment '采购成本-自发货亚马逊销售出库数量',
    cg_price_amazon_sale_outstock_amount           varchar(20) not null comment '采购成本-自发货亚马逊销售出库销额',
    cg_tansport_cost_fba_amazon_quantity           varchar(20) not null comment '头程成本-FBA亚马逊销售订单数量',
    cg_tansport_cost_amazon_amount                 varchar(20) not null comment '头程成本-FBA亚马逊销售订单销额',
    cg_tansport_cost_fba_multichannel_quantity     varchar(20) not null comment '头程成本-FBA多渠道销售订单数量',
    cg_tansport_cost_fba_multichannel_amount       varchar(20) not null comment '头程成本-FBA多渠道销售订单数销额',
    cg_tansport_cost_fba_remove_quantity           varchar(20) not null comment '头程成本-FBA移除数量',
    cg_tansport_cost_fba_remove_amount             varchar(20) not null comment '头程成本-FBA移除销额',
    cg_tansport_cost_fba_replacement_quantity      varchar(20) not null comment '头程成本-FBA补发货销售数量',
    cg_tansport_cost_fba_replacement_amount        varchar(20) not null comment '头程成本-FBA补发货销售销额',
    cg_tansport_cost_fba_stock_out_quantity        varchar(20) not null comment '头程成本-FBA盘点出库数量',
    cg_tansport_cost_fba_stock_out_amount          varchar(20) not null comment '头程成本-FBA盘点出库销额',
    cg_tansport_cost_fba_unsingle_return_quantity  varchar(20) not null comment '头程成本-FBA无源单销售退货数量',
    cg_tansport_cost_fba_unsingle_return_amount    varchar(20) not null comment '头程成本-FBA无源单销售退货销额',
    cg_tansport_cost_fba_stock_in_quantity         varchar(20) not null comment '头程成本-FBA盘点入库数量',
    cg_tansport_cost_fba_stock_in_amount           varchar(20) not null comment '头程成本-FBA盘点入库销额',
    cg_tansport_cost_fba_single_return_quantity    varchar(20) not null comment '头程成本-FBA有源单销售退货数量',
    cg_tansport_cost_fba_single_return_amount      varchar(20) not null comment '头程成本-FBA有源单销售退货销额',
    cg_tansport_cost_amazon_sale_outstock_quantity varchar(20) not null comment '头程成本-自发货亚马逊销售出库数量',
    cg_tansport_cost_amazon_sale_outstock_amount   varchar(20) not null comment '头程成本-自发货亚马逊销售出库销额',
    primary key (dt, msku, sid)
) comment ='利润报表(msku-cost 维度)'
    partition by key (dt) partitions 3;
                    """
ods_gsm_lx_profit_msku_statement_cost_detail_i_d_field_list = ['dt', 'sid', 'msku', 'currencyCode',
                                                               'other_cost_fba_amazon_quantity',
                                                               'other_cost_fba_amazon_amount',
                                                               'other_cost_fba_multichannel_quantity',
                                                               'other_cost_fba_multichannel_amount',
                                                               'other_cost_fba_remove_quantity',
                                                               'other_cost_fba_remove_amount',
                                                               'other_cost_fba_replacement_quantity',
                                                               'other_cost_fba_replacement_amount',
                                                               'other_cost_fba_stock_out_quantity',
                                                               'other_cost_fba_stock_out_amount',
                                                               'other_cost_fba_unsingle_return_quantity',
                                                               'other_cost_fba_unsingle_return_amount',
                                                               'other_cost_fba_stock_in_quantity',
                                                               'other_cost_fba_stock_in_amount',
                                                               'other_cost_fba_single_return_quantity',
                                                               'other_cost_fba_single_return_amount',
                                                               'other_cost_amazon_sale_outstock_quantity',
                                                               'other_cost_amazon_sale_outstock_amount',
                                                               'cg_price_fba_amazon_quantity',
                                                               'cg_price_fba_amazon_amount',
                                                               'cg_price_fba_multichannel_quantity',
                                                               'cg_price_fba_multichannel_amount',
                                                               'cg_price_fba_remove_quantity',
                                                               'cg_price_fba_remove_amount',
                                                               'cg_price_fba_replacement_quantity',
                                                               'cg_price_fba_replacement_amount',
                                                               'cg_price_fba_stock_out_quantity',
                                                               'cg_price_fba_stock_out_amount',
                                                               'cg_price_fba_unsingle_return_quantity',
                                                               'cg_price_fba_unsingle_return_amount',
                                                               'cg_price_fba_stock_in_quantity',
                                                               'cg_price_fba_stock_in_amount',
                                                               'cg_price_fba_single_return_quantity',
                                                               'cg_price_fba_single_return_amount',
                                                               'cg_price_amazon_sale_outstock_quantity',
                                                               'cg_price_amazon_sale_outstock_amount',
                                                               'cg_tansport_cost_fba_amazon_quantity',
                                                               'cg_tansport_cost_amazon_amount',
                                                               'cg_tansport_cost_fba_multichannel_quantity',
                                                               'cg_tansport_cost_fba_multichannel_amount',
                                                               'cg_tansport_cost_fba_remove_quantity',
                                                               'cg_tansport_cost_fba_remove_amount',
                                                               'cg_tansport_cost_fba_replacement_quantity',
                                                               'cg_tansport_cost_fba_replacement_amount',
                                                               'cg_tansport_cost_fba_stock_out_quantity',
                                                               'cg_tansport_cost_fba_stock_out_amount',
                                                               'cg_tansport_cost_fba_unsingle_return_quantity',
                                                               'cg_tansport_cost_fba_unsingle_return_amount',
                                                               'cg_tansport_cost_fba_stock_in_quantity',
                                                               'cg_tansport_cost_fba_stock_in_amount',
                                                               'cg_tansport_cost_fba_single_return_quantity',
                                                               'cg_tansport_cost_fba_single_return_amount',
                                                               'cg_tansport_cost_amazon_sale_outstock_quantity',
                                                               'cg_tansport_cost_amazon_sale_outstock_amount']

ods_gsm_lx_ad_invoice_record = 'ods_prod.ods_gsm_lx_ad_invoice_record_i_d'
ods_gsm_lx_ad_invoice_record_i_d = """
create table if not exists ods_prod.ods_gsm_lx_ad_invoice_record_i_d
(
    dt                 varchar(10) comment 'dt',
    invoiceId          varchar(50) comment '发票唯一ID',
    status             varchar(50) comment '状态',
    paymentMethod      varchar(50) comment '付款类型',
    fromDate           varchar(50) comment '周期始点',
    toDate             varchar(50) comment '周期节点',
    currencyIcon       varchar(50) comment '汇率图标',
    currencyCode       varchar(50) comment '汇率编码',
    amount             varchar(50) comment '账单金额',
    costAmount         varchar(50) comment '账单金额',
    taxAmount          varchar(50) comment '税后账单金额',
    otherAllocationFee varchar(50) comment '其他费均摊',
    invoiceDate        varchar(50) comment '开具时间',
    sid                varchar(50) comment 'SID',
    storeName          varchar(50) comment '店铺名称',
    country            varchar(50) comment '国家',
    primary key (dt, invoiceId, sid)
) comment '领星-财务-广告发票记录-杨洋' partition by key (dt) partitions 3;
"""
ods_gsm_lx_ad_invoice_record_i_d_field_list = [
    "dt",
    "invoiceId",
    "status",
    "paymentMethod",
    "fromDate",
    "toDate",
    "currencyIcon",
    "currencyCode",
    "amount",
    "costAmount",
    "taxAmount",
    "otherAllocationFee",
    "invoiceDate",
    "sid",
    "storeName",
    "country"
]

ods_gsm_lx_ad_invoice_record_detail = 'ods_prod.ods_gsm_lx_ad_invoice_record_detail_i_d'
ods_gsm_lx_ad_invoice_record_detail_i_d = """
create table if not exists ods_prod.ods_gsm_lx_ad_invoice_record_detail_i_d
(
    dt                 varchar(50) comment '开具时间',
    invoiceId          varchar(50) comment '发票编号',
    sid                varchar(50) comment 'SID',
    campaignName       varchar(50) comment '广告活动名称',
    campaignId         varchar(50) comment '广告活动ID',
    adsType            varchar(50) comment '广告类型',
    priceType          varchar(50) comment '计费方式',
    costEventCount     varchar(50) comment '点击',
    currencyIcon       varchar(50) comment '汇率图标',
    costAmount         varchar(50) comment '费用',
    costPerUnit        varchar(50) comment '平均点击单价',
    otherAllocationFee varchar(50) comment '其他费分摊',
    items              varchar(50) comment '承担商品',
    customItems        varchar(50) comment '自定义',
    primary key (dt, invoiceId, sid, campaignId)
) comment '领星-财务-广告发票记录详情-杨洋' partition by key (dt) partitions 3;
"""
ods_gsm_lx_ad_invoice_record_detail_i_d_field_list = [
    "dt",
    "invoiceId",
    "sid",
    "campaignName",
    "campaignId",
    "adsType",
    "priceType",
    "costEventCount",
    "currencyIcon",
    "costAmount",
    "costPerUnit",
    "otherAllocationFee",
    "items",
    "customItems"
]

# 领星-利润报表店铺-cost明细数据
ods_gsm_lx_profit_shop_cost_detail = 'ods_prod.ods_gsm_lx_profit_shop_cost_detail_i_d'
ods_gsm_lx_profit_shop_cost_detail_i_d = """
create table if not exists ods_prod.ods_gsm_lx_profit_shop_cost_detail_i_d
(
    dt                                             varchar(15) not null comment '当前时间',
    sid                                            varchar(20) not null comment '店铺',
    currency_code                                   varchar(20) not null comment '币种',
    other_cost_fba_amazon_quantity                 varchar(20) not null comment '其他成本-FBA亚马逊销售订单数量',
    other_cost_fba_amazon_amount                   varchar(20) not null comment '其他成本-FBA亚马逊销售订单销额',
    other_cost_fba_multichannel_quantity           varchar(20) not null comment '其他成本-FBA多渠道销售订单数量',
    other_cost_fba_multichannel_amount             varchar(20) not null comment '其他成本-FBA多渠道销售订单数销额',
    other_cost_fba_remove_quantity                 varchar(20) not null comment '其他成本-FBA移除数量',
    other_cost_fba_remove_amount                   varchar(20) not null comment '其他成本-FBA移除销额',
    other_cost_fba_replacement_quantity            varchar(20) not null comment '其他成本-FBA补发货销售数量',
    other_cost_fba_replacement_amount              varchar(20) not null comment '其他成本-FBA补发货销售销额',
    other_cost_fba_stock_out_quantity              varchar(20) not null comment '其他成本-FBA盘点出库数量',
    other_cost_fba_stock_out_amount                varchar(20) not null comment '其他成本-FBA盘点出库销额',
    other_cost_fba_unsingle_return_quantity        varchar(20) not null comment '其他成本-FBA无源单销售退货数量',
    other_cost_fba_unsingle_return_amount          varchar(20) not null comment '其他成本-FBA无源单销售退货销额',
    other_cost_fba_stock_in_quantity               varchar(20) not null comment '其他成本-FBA盘点入库数量',
    other_cost_fba_stock_in_amount                 varchar(20) not null comment '其他成本-FBA盘点入库销额',
    other_cost_fba_single_return_quantity          varchar(20) not null comment '其他成本-FBA有源单销售退货数量',
    other_cost_fba_single_return_amount            varchar(20) not null comment '其他成本-FBA有源单销售退货销额',
    other_cost_amazon_sale_outstock_quantity       varchar(20) not null comment '其他成本-自发货亚马逊销售出库数量',
    other_cost_amazon_sale_outstock_amount         varchar(20) not null comment '其他成本-自发货亚马逊销售出库销额',
    cg_price_fba_amazon_quantity                   varchar(20) not null comment '采购成本-FBA亚马逊销售订单数量',
    cg_price_fba_amazon_amount                     varchar(20) not null comment '采购成本-FBA亚马逊销售订单销额',
    cg_price_fba_multichannel_quantity             varchar(20) not null comment '采购成本-FBA多渠道销售订单数量',
    cg_price_fba_multichannel_amount               varchar(20) not null comment '采购成本-FBA多渠道销售订单数销额',
    cg_price_fba_remove_quantity                   varchar(20) not null comment '采购成本-FBA移除数量',
    cg_price_fba_remove_amount                     varchar(20) not null comment '采购成本-FBA移除销额',
    cg_price_fba_replacement_quantity              varchar(20) not null comment '采购成本-FBA补发货销售数量',
    cg_price_fba_replacement_amount                varchar(20) not null comment '采购成本-FBA补发货销售销额',
    cg_price_fba_stock_out_quantity                varchar(20) not null comment '采购成本-FBA盘点出库数量',
    cg_price_fba_stock_out_amount                  varchar(20) not null comment '采购成本-FBA盘点出库销额',
    cg_price_fba_unsingle_return_quantity          varchar(20) not null comment '采购成本-FBA无源单销售退货数量',
    cg_price_fba_unsingle_return_amount            varchar(20) not null comment '采购成本-FBA无源单销售退货销额',
    cg_price_fba_stock_in_quantity                 varchar(20) not null comment '采购成本-FBA盘点入库数量',
    cg_price_fba_stock_in_amount                   varchar(20) not null comment '采购成本-FBA盘点入库销额',
    cg_price_fba_single_return_quantity            varchar(20) not null comment '采购成本-FBA有源单销售退货数量',
    cg_price_fba_single_return_amount              varchar(20) not null comment '采购成本-FBA有源单销售退货销额',
    cg_price_amazon_sale_outstock_quantity         varchar(20) not null comment '采购成本-自发货亚马逊销售出库数量',
    cg_price_amazon_sale_outstock_amount           varchar(20) not null comment '采购成本-自发货亚马逊销售出库销额',
    cg_tansport_cost_fba_amazon_quantity           varchar(20) not null comment '头程成本-FBA亚马逊销售订单数量',
    cg_tansport_cost_amazon_amount                 varchar(20) not null comment '头程成本-FBA亚马逊销售订单销额',
    cg_tansport_cost_fba_multichannel_quantity     varchar(20) not null comment '头程成本-FBA多渠道销售订单数量',
    cg_tansport_cost_fba_multichannel_amount       varchar(20) not null comment '头程成本-FBA多渠道销售订单数销额',
    cg_tansport_cost_fba_remove_quantity           varchar(20) not null comment '头程成本-FBA移除数量',
    cg_tansport_cost_fba_remove_amount             varchar(20) not null comment '头程成本-FBA移除销额',
    cg_tansport_cost_fba_replacement_quantity      varchar(20) not null comment '头程成本-FBA补发货销售数量',
    cg_tansport_cost_fba_replacement_amount        varchar(20) not null comment '头程成本-FBA补发货销售销额',
    cg_tansport_cost_fba_stock_out_quantity        varchar(20) not null comment '头程成本-FBA盘点出库数量',
    cg_tansport_cost_fba_stock_out_amount          varchar(20) not null comment '头程成本-FBA盘点出库销额',
    cg_tansport_cost_fba_unsingle_return_quantity  varchar(20) not null comment '头程成本-FBA无源单销售退货数量',
    cg_tansport_cost_fba_unsingle_return_amount    varchar(20) not null comment '头程成本-FBA无源单销售退货销额',
    cg_tansport_cost_fba_stock_in_quantity         varchar(20) not null comment '头程成本-FBA盘点入库数量',
    cg_tansport_cost_fba_stock_in_amount           varchar(20) not null comment '头程成本-FBA盘点入库销额',
    cg_tansport_cost_fba_single_return_quantity    varchar(20) not null comment '头程成本-FBA有源单销售退货数量',
    cg_tansport_cost_fba_single_return_amount      varchar(20) not null comment '头程成本-FBA有源单销售退货销额',
    cg_tansport_cost_amazon_sale_outstock_quantity varchar(20) not null comment '头程成本-自发货亚马逊销售出库数量',
    cg_tansport_cost_amazon_sale_outstock_amount   varchar(20) not null comment '头程成本-自发货亚马逊销售出库销额',
    primary key (dt, sid)
) comment ='领星-利润报表店铺cost明细数据-李仕春'
    partition by key (dt) partitions 3;
"""
ods_gsm_lx_profit_shop_cost_detail_list = [
    "dt",
    "sid",
    "currency_code",
    "other_cost_fba_amazon_quantity",
    "other_cost_fba_amazon_amount",
    "other_cost_fba_multichannel_quantity",
    "other_cost_fba_multichannel_amount",
    "other_cost_fba_remove_quantity",
    "other_cost_fba_remove_amount",
    "other_cost_fba_replacement_quantity",
    "other_cost_fba_replacement_amount",
    "other_cost_fba_stock_out_quantity",
    "other_cost_fba_stock_out_amount",
    "other_cost_fba_unsingle_return_quantity",
    "other_cost_fba_unsingle_return_amount",
    "other_cost_fba_stock_in_quantity",
    "other_cost_fba_stock_in_amount",
    "other_cost_fba_single_return_quantity",
    "other_cost_fba_single_return_amount",
    "other_cost_amazon_sale_outstock_quantity",
    "other_cost_amazon_sale_outstock_amount",
    "cg_price_fba_amazon_quantity",
    "cg_price_fba_amazon_amount",
    "cg_price_fba_multichannel_quantity",
    "cg_price_fba_multichannel_amount",
    "cg_price_fba_remove_quantity",
    "cg_price_fba_remove_amount",
    "cg_price_fba_replacement_quantity",
    "cg_price_fba_replacement_amount",
    "cg_price_fba_stock_out_quantity",
    "cg_price_fba_stock_out_amount",
    "cg_price_fba_unsingle_return_quantity",
    "cg_price_fba_unsingle_return_amount",
    "cg_price_fba_stock_in_quantity",
    "cg_price_fba_stock_in_amount",
    "cg_price_fba_single_return_quantity",
    "cg_price_fba_single_return_amount",
    "cg_price_amazon_sale_outstock_quantity",
    "cg_price_amazon_sale_outstock_amount",
    "cg_tansport_cost_fba_amazon_quantity",
    "cg_tansport_cost_amazon_amount",
    "cg_tansport_cost_fba_multichannel_quantity",
    "cg_tansport_cost_fba_multichannel_amount",
    "cg_tansport_cost_fba_remove_quantity",
    "cg_tansport_cost_fba_remove_amount",
    "cg_tansport_cost_fba_replacement_quantity",
    "cg_tansport_cost_fba_replacement_amount",
    "cg_tansport_cost_fba_stock_out_quantity",
    "cg_tansport_cost_fba_stock_out_amount",
    "cg_tansport_cost_fba_unsingle_return_quantity",
    "cg_tansport_cost_fba_unsingle_return_amount",
    "cg_tansport_cost_fba_stock_in_quantity",
    "cg_tansport_cost_fba_stock_in_amount",
    "cg_tansport_cost_fba_single_return_quantity",
    "cg_tansport_cost_fba_single_return_amount",
    "cg_tansport_cost_amazon_sale_outstock_quantity",
    "cg_tansport_cost_amazon_sale_outstock_amount"
]

# 领星-利润报表订单-transaction视图数据
ods_gsm_lx_profit_report_order_transaction_table = 'ods_prod.ods_gsm_lx_profit_report_order_transaction_i_d'
ods_gsm_lx_profit_report_order_transaction_i_d = """
create table if not exists ods_prod.ods_gsm_lx_profit_report_order_transaction_i_d
(
    dt                             varchar(10) not null comment 'dt(下单时间)',
    costQuantityType200            varchar(30) not null comment '成本数量类型200',
    costQuantityType201            varchar(30) not null comment '成本数量类型201',
    costQuantityType202            varchar(30) not null comment '成本数量类型202',
    costQuantityType380101         varchar(30) not null comment '成本数量类型380101',
    fbaEstimateCostQuantity        varchar(30) not null comment 'FBA预估成本数量',
    quantity                       varchar(30) not null comment '数量',
    costQuantity                   varchar(30) not null comment '成本数量',
    productSalesQuantity           varchar(30) not null comment '销售金额数量',
    productSales                   varchar(30) not null comment '销售额',
    productSalesTax                varchar(30) not null comment '销售税',
    shippingCredits                varchar(30) not null comment '买家运费',
    shippingCreditsTax             varchar(30) not null comment '买家运费税',
    giftwrapCredits                varchar(30) not null comment '礼品包装',
    giftwrapCreditsTax             varchar(30) not null comment '礼品包装税',
    amazonPointFee                 varchar(30) not null comment '积分',
    promotionalRebates             varchar(30) not null comment '促销折扣',
    promotionalRebatesTax          varchar(30) not null comment '促销折扣费',
    salesTaxCollected              varchar(30) not null comment '代扣代缴增值税',
    lowValueGoods                  varchar(30) not null comment '低价值商品税',
    marketplaceWithheldTax         varchar(30) not null comment '市场预扣税',
    tcsCgst                        varchar(30) not null comment 'TCS_CGST',
    tcsSgst                        varchar(30) not null comment 'TCS_SGST',
    tcsIgst                        varchar(30) not null comment 'TCS_IGST',
    sellingFees                    varchar(30) not null comment '平台费',
    fbaFees                        varchar(30) not null comment 'FBA费',
    otherTransactionFees           varchar(30) not null comment '其他交易费',
    hiddenTax                      varchar(30) not null comment '隐藏税',
    other                          varchar(30) not null comment '其他',
    settlementTotal                varchar(30) not null comment '亚马逊结算小计',
    purchaseCostsTotal             varchar(30) not null comment '采购成本',
    purchaseCostsDetail            json        not null comment '采购成本明细',
    purchaseCostsDetailWeb         json        not null comment '采购成本明细网页',
    logisticsCostsTotal            varchar(30) not null comment '头程成本',
    logisticsCostsDetail           json        not null comment '头程成本明细',
    logisticsCostsDetailWeb        json        not null comment '头程成本明细网页',
    otherCostsTotal                varchar(30) not null comment '其他成本',
    otherCostsDetail               varchar(30) not null comment '其他成本明细',
    otherCostsDetailWeb            varchar(30) not null comment '其他成本明细网页',
    settlementGrossProfit          varchar(30) not null comment '结算订单毛利润',
    settlementGrossProfitRate      varchar(30) not null comment '结算订单毛利率',
    customOrderFeeTotal            varchar(30) not null comment '站外推广费',
    customOrderFee                 varchar(30) not null comment '站外订单费',
    customOrderFeeCommission       varchar(30) not null comment '站外订单费佣金',
    fbaEstimatePurchaseCostAmount  varchar(30) not null comment 'FBA预估采购成本金额',
    fbaEstimateLogisticsCostAmount varchar(30) not null comment 'FBA预估物流成本金额',
    fbaEstimateOtherCostAmount     varchar(30) not null comment 'FBA预估其他成本金额',
    minPostedDateDayLocale         varchar(50) not null comment '最小发布日期（本地）',
    maxPostedDateDayLocale         varchar(50) not null comment '最大发布日期（本地）',
    sid                            varchar(10) not null comment '店铺id',
    storeName                      varchar(50) not null comment '店铺名称',
    country                        varchar(30) not null comment '国家',
    countryCode                    varchar(10) not null comment '国家编码',
    postedDatetimeLocale           varchar(30) not null comment '结算时间',
    currencyCode                   varchar(15) not null comment '币种',
    currencyIcon                   varchar(10) not null comment '币种符号',
    fid                            varchar(30) not null comment '结算编号',
    settlementId                   varchar(50) not null comment 'Settlement ID',
    orderId                        varchar(50) not null comment '订单号',
    eventSource                    varchar(50) not null comment '费用类型',
    description                    varchar(50) not null comment '描述',
    accountType                    varchar(50) not null comment '账单类型',
    msku                           varchar(50) not null comment 'msku',
    fnsku                          varchar(50) not null comment 'fnsku',
    asin                           varchar(50) not null comment 'asin',
    parentAsin                     varchar(50) not null comment '父ASIN',
    localName                      varchar(50) not null comment '品名',
    localSku                       varchar(50) not null comment 'SKU',
    fulfillment                    varchar(50) not null comment '订单类型',
    toCnyRate                      varchar(30) not null comment '到人民币汇率',
    toTargetRate                   varchar(30) not null comment '到目标汇率',
    trsCostsRate                   varchar(30) not null comment 'TRS成本率',
    cgPrice                        varchar(30) not null comment '采购价格',
    cgTransportCosts               varchar(30) not null comment '采购运输成本',
    settlementStatus               varchar(30) not null comment '结算状态',
    fundTransferStatus             varchar(30) not null comment '转账状态',
    fundTransferDatetimeLocale     varchar(50) not null comment '转账时间',
    shipmentDatetimeLocale         varchar(50) not null comment '发货时间',
    smallImageUrl                  varchar(100) not null comment '图片',
    principalRealname              varchar(50) not null comment 'Listing负责人',
    productDeveloperRealname       varchar(50) not null comment '开发负责人',
    orderDatetimeLocale            varchar(50) not null comment '下单时间',
    paymentDatetimeLocale          varchar(50) not null comment '付款时间',
    promotionId                    varchar(30) not null comment '促销编码',
    originOrderNo                  varchar(50) not null comment '原始订单号',
    transactionStatus              varchar(30) not null comment '交易状态',
    transactionStatusCode          varchar(30) not null comment '交易状态代码',
    primary key (dt,orderId,msku,transactionStatusCode)
)comment '领星-利润报表-订单transaction视图-李仕春'
partition by key (dt) partitions 3;
"""
ods_gsm_lx_profit_report_order_transaction_dict = {
    'dt': 'dt',
    'costQuantityType200': 'costQuantityType200',
    'costQuantityType201': 'costQuantityType201',
    'costQuantityType202': 'costQuantityType202',
    'costQuantityType380101': 'costQuantityType380101',
    'fbaEstimateCostQuantity': 'fbaEstimateCostQuantity',
    'quantity': 'quantity',
    'costQuantity': 'costQuantity',
    'productSalesQuantity': 'productSalesQuantity',
    'productSales': 'productSales',
    'productSalesTax': 'productSalesTax',
    'shippingCredits': 'shippingCredits',
    'shippingCreditsTax': 'shippingCreditsTax',
    'giftwrapCredits': 'giftwrapCredits',
    'giftwrapCreditsTax': 'giftwrapCreditsTax',
    'amazonPointFee': 'amazonPointFee',
    'promotionalRebates': 'promotionalRebates',
    'promotionalRebatesTax': 'promotionalRebatesTax',
    'salesTaxCollected': 'salesTaxCollected',
    'lowValueGoods': 'lowValueGoods',
    'marketplaceWithheldTax': 'marketplaceWithheldTax',
    'tcsCgst': 'tcsCgst',
    'tcsSgst': 'tcsSgst',
    'tcsIgst': 'tcsIgst',
    'sellingFees': 'sellingFees',
    'fbaFees': 'fbaFees',
    'otherTransactionFees': 'otherTransactionFees',
    'hiddenTax': 'hiddenTax',
    'other': 'other',
    'settlementTotal': 'settlementTotal',
    'purchaseCostsTotal': 'purchaseCostsTotal',
    'purchaseCostsDetail': 'purchaseCostsDetail',
    'purchaseCostsDetailWeb': 'purchaseCostsDetailWeb',
    'logisticsCostsTotal': 'logisticsCostsTotal',
    'logisticsCostsDetail': 'logisticsCostsDetail',
    'logisticsCostsDetailWeb': 'logisticsCostsDetailWeb',
    'otherCostsTotal': 'otherCostsTotal',
    'otherCostsDetail': 'otherCostsDetail',
    'otherCostsDetailWeb': 'otherCostsDetailWeb',
    'settlementGrossProfit': 'settlementGrossProfit',
    'settlementGrossProfitRate': 'settlementGrossProfitRate',
    'customOrderFeeTotal': 'customOrderFeeTotal',
    'customOrderFee': 'customOrderFee',
    'customOrderFeeCommission': 'customOrderFeeCommission',
    'fbaEstimatePurchaseCostAmount': 'fbaEstimatePurchaseCostAmount',
    'fbaEstimateLogisticsCostAmount': 'fbaEstimateLogisticsCostAmount',
    'fbaEstimateOtherCostAmount': 'fbaEstimateOtherCostAmount',
    'minPostedDateDayLocale': 'minPostedDateDayLocale',
    'maxPostedDateDayLocale': 'maxPostedDateDayLocale',
    'sid': 'sid',
    'storeName': 'storeName',
    'country': 'country',
    'countryCode': 'countryCode',
    'postedDatetimeLocale': 'postedDatetimeLocale',
    'currencyCode': 'currencyCode',
    'currencyIcon': 'currencyIcon',
    'fid': 'fid',
    'settlementId': 'settlementId',
    'orderId': 'orderId',
    'eventSource': 'eventSource',
    'description': 'description',
    'accountType': 'accountType',
    'msku': 'msku',
    'fnsku': 'fnsku',
    'asin': 'asin',
    'parentAsin': 'parentAsin',
    'localName': 'localName',
    'localSku': 'localSku',
    'fulfillment': 'fulfillment',
    'toCnyRate': 'toCnyRate',
    'toTargetRate': 'toTargetRate',
    'trsCostsRate': 'trsCostsRate',
    'cgPrice': 'cgPrice',
    'cgTransportCosts': 'cgTransportCosts',
    'settlementStatus': 'settlementStatus',
    'fundTransferStatus': 'fundTransferStatus',
    'fundTransferDatetimeLocale': 'fundTransferDatetimeLocale',
    'shipmentDatetimeLocale': 'shipmentDatetimeLocale',
    'smallImageUrl': 'smallImageUrl',
    'principalRealname': 'principalRealname',
    'productDeveloperRealname': 'productDeveloperRealname',
    'orderDatetimeLocale': 'orderDatetimeLocale',
    'paymentDatetimeLocale': 'paymentDatetimeLocale',
    'promotionId': 'promotionId',
    'originOrderNo': 'originOrderNo',
    'transactionStatus': 'transactionStatus',
    'transactionStatusCode': 'transactionStatusCode',
}
