version: '3'

services:
  crawler-lingxing-finance-data:
    image: crawler-lingxing-finance-data:v2.3.0
    container_name: crawler-lingxing-finance-data
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8204:8000
    environment:
      - TZ:Asia/Shanghai
      - PYTHONPATH:/app