# -*- coding: utf-8 -*-
# @Time    : 2024/8/14 9:30
# @Author  : gu tao
# @Email   : 1370391119@qq.com
# @File    : 
# @Software: 数据库sql语句配置文件

# ODS-GES-AUASIAN-AAF物流数据-辜涛:
ods_scg_wld_logistics_trace_db_table = "ods_prod.ods_scg_wld_logistics_trace_table_i_d"

ods_scg_wld_logistics_trace_table_i_d = """
                        CREATE TABLE IF NOT EXISTS ods_prod.`ods_scg_wld_logistics_trace_table_i_d`
                        (
                            `dt`                   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '下单日期',
                            `id`                   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT 'id',
                            `logistics_provider`   varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '物流商',
                            `shipment_id`          varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'FBA单号',
                            `shipment_number`      varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '快递单号',
                            `service`              varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '物流渠道',
                            `to_warehouse_code`    varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '地址库编码',
                            `to_address_name`      varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收件人',
                            `to_address_country`   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '国家',
                            `parcel_count`         varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '件数',
                            `declaration_value`    varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '价值',
                            `client_weight`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '客户重量',
                            `client_volume`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '客户体积',
                            `actual_weight`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '实重',
                            `actual_volume`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '体积',
                            `actual_volume_weight` varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '材重',
                            `chargeable_weight`    varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收费重',
                            `sell_charge_amount`   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '销售费用金额',
                            `is_insurance`         varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '购买保险',
                            `elec`                 varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '带电',
                            `exportwith`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '报关方式',
                            `importwith`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '清关方式',
                            `taxwith`              varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '交税方式',
                            `vat_number`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT 'VAT号',
                            `deliverywith`         varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '交货条款',
                            `outer_carrier`        varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '承运',
                            `courier_number`       varchar(225) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '快递单号',
                            `printed`              varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '打标状态',
                            `remark`               varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
                            `last_tracking`        varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最后路由',
                            `depot_id`             varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '仓库id',
                            `created`              varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '下单时间',
                            `picking_time`         varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '拣货时间',
                            `delivered_time`       varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '签收时间',
                            `logistics_state`       varchar(20) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '物流状态(all,cancelled)',
                            PRIMARY KEY (`logistics_provider`, `shipment_number`,`shipment_id`) /*T![clustered_index] CLUSTERED */
                        ) ENGINE = InnoDB
                          DEFAULT CHARSET = utf8mb4
                          COLLATE = utf8mb4_general_ci COMMENT ='ODS-物流数据-辜涛';
                    """

truncate_ods_scg_wld_logistics_trace_table_i_d = "TRUNCATE TABLE ods_prod.ods_scg_wld_logistics_trace_table_i_d"

ods_scg_wld_logistics_trace_table_i_d_field_list = [
    "dt",
    "id",
    "logistics_provider",
    "shipment_id",
    "shipment_number",
    "service",
    "to_warehouse_code",
    "to_address_name",
    "to_address_country",
    "parcel_count",
    "declaration_value",
    "client_weight",
    "client_volume",
    "actual_weight",
    "actual_volume",
    "actual_volume_weight",
    "chargeable_weight",
    "sell_charge_amount",
    "is_insurance",
    "elec",
    "exportwith",
    "importwith",
    "taxwith",
    "vat_number",
    "deliverywith",
    "outer_carrier",
    "courier_number",
    "printed",
    "remark",
    "last_tracking",
    "depot_id",
    "created",
    "picking_time",
    "delivered_time",
    "logistics_state",
]

# ODS-GES-AUASIAN-AAF-view物流数据-辜涛:
ods_scg_wld_logistics_trace_db_view = "ods_prod.ods_scg_wld_logistics_trace_view_i_d"

ods_scg_wld_logistics_trace_view_i_d = """
                        CREATE TABLE IF NOT EXISTS ods_prod.`ods_scg_wld_logistics_trace_view_i_d`
                        (
                                `id`                     varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'id',
                                `logistics_provider`     varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '物流商',
                                `shipment_id`            varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'FBA单号',
                                `sailing_date`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '开航日期',
                                `customs_clearance_date` varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '清关日期',
                                `fetch_date`             varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '提取日期',
                                `send_date`              varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '派送日期',
                                `receipt_date`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '签收日期',
                            PRIMARY KEY (`logistics_provider`, `id`) /*T![clustered_index] CLUSTERED */
                        ) ENGINE = InnoDB
                          DEFAULT CHARSET = utf8mb4
                          COLLATE = utf8mb4_general_ci COMMENT ='ODS-物流数据-view-辜涛';
                    """

truncate_ods_scg_wld_logistics_trace_view_i_d = "TRUNCATE TABLE ods_prod.ods_scg_wld_logistics_trace_view_i_d"

ods_scg_wld_logistics_trace_view_i_d_field_list = [
    "id",
    "logistics_provider",
    "shipment_id",
    "sailing_date",
    "customs_clearance_date",
    "fetch_date",
    "send_date",
    "receipt_date",
]

# ODS-K5-tw-天伟物流数据-辜涛:
ods_scg_wld_tw_logistics_trace_db_table = "ods_prod.ods_scg_wld_tw_logistics_trace_table_i_d"

ods_scg_wld_tw_logistics_trace_table_i_d = """
                        CREATE TABLE IF NOT EXISTS ods_prod.`ods_scg_wld_tw_logistics_trace_table_i_d`
                        (
                            `Tracking_number`       varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT '运单号',
                            `Transfer_order_number` varchar(20) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '转单号',
                            `order_number`          varchar(20) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '订单号',
                            `Customer_order_number` varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '客户订单号',
                            `Receiving_channels`    varchar(10) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收货渠道',
                            `destination`           varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '目的地',
                            `parcel_count`          varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '件数',
                            `article_name`          varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '品名',
                            `Declared_value`        varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '申报价值',
                            `Tracking_status`       varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '运单状态',
                            `Warehousing_time`      varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '入仓时间',
                            `remark`                varchar(200) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '备注',
                            `Recipient_name`        varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收件人名称',
                            `Volume`                varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '材积',
                            `Solid_weight`          varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '实重',
                            `Settlement_weight`     varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '结算重',
                            `zip_code`              varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '邮编',
                            `operate`               varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '操作',
                            `logistics_state_code`  varchar(10) COLLATE utf8mb4_general_ci NOT NULL COMMENT '物流状态(默认0)',
                            PRIMARY KEY (`Tracking_number`, `Transfer_order_number`, `order_number`) /*T![clustered_index] CLUSTERED */
                        ) ENGINE = InnoDB
                          DEFAULT CHARSET = utf8mb4
                          COLLATE = utf8mb4_general_ci COMMENT ='ODS-天伟物流数据-辜涛';
                    """

truncate_ods_scg_wld_tw_logistics_trace_table_i_d = "TRUNCATE TABLE ods_prod.ods_scg_wld_tw_logistics_trace_table_i_d"

ods_scg_wld_tw_logistics_trace_table_i_d_field_list = [
    "Tracking_number",
    "Transfer_order_number",
    "order_number",
    "Customer_order_number",
    "Receiving_channels",
    "destination",
    "parcel_count",
    "article_name",
    "Declared_value",
    "Tracking_status",
    "Warehousing_time",
    "remark",
    "Recipient_name",
    "Volume",
    "Solid_weight",
    "Settlement_weight",
    "zip_code",
    "operate",
    "logistics_state_code",
]


# 致富
ods_scg_wld_logistics_ahc_table = "ods_prod.ods_scg_wld_logistics_ahc_i_d"

ods_scg_wld_logistics_ahc_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_ahc_i_d
(
    dt            varchar(10)  not null comment '轨迹时间',
    zztm          varchar(20)  not null comment '轨迹时间',
    orderret      varchar(30)  not null comment '状态',
    orderno       varchar(40)  not null comment '系统订单号',
    qsdate        varchar(40)  not null comment '',
    dest          varchar(40)  not null comment '目的地',
    jcnt          varchar(20)  not null comment '件数',
    postno        varchar(20)  not null comment '收件邮编',
    zyday         varchar(20)  not null comment '',
    zycodehover   text  not null comment '转运单号',
    podfile       varchar(20)  not null comment '',
    ysjweit       varchar(20)  not null comment '材重',
    sendmobi      varchar(40)  not null comment '',
    yczweit       varchar(20)  not null comment '实重',
    ycbmqty       varchar(20)  not null comment '方数',
    addnm         varchar(20)  not null comment '仓库代码',
    sedprovinces  varchar(40)  not null comment '省份/州',
    sendbyaddress varchar(400) not null comment '地址',
    gsfile        varchar(20)  not null comment '',
    apimk         varchar(20)  not null comment '',
    delcompanynm  varchar(80)  not null comment '收货公司名',
    phone         varchar(30)  not null comment '收货人电话',
    contactsby    varchar(100)  not null comment '收货人名',
    channelprice  varchar(20)  not null comment '价格渠道',
    packno        varchar(80)  not null comment '运单号',
    sjdate        varchar(20)  not null comment '送货日期',
    tszl          varchar(20)  not null comment '',
    sedcity       varchar(100)  not null comment '城市/州',
    expresstype   varchar(20)  not null comment '快递类型',
    orgname       varchar(20)  not null comment '发货仓库',
    bxflg         VARCHAR(5) COMMENT '保险标志',
    supcode       VARCHAR(50) COMMENT '客户单号',
    publicmk      VARCHAR(20) COMMENT '',
    sendby        VARCHAR(20) COMMENT '',
    kdzt          VARCHAR(30) COMMENT '快递状态',
    bgtype        VARCHAR(30) COMMENT '报关方式',
    address3      VARCHAR(200) COMMENT '地址3',
    qgtype        VARCHAR(30) COMMENT '清关方式',
    address2      VARCHAR(200) COMMENT '地址2',
    yjfweit       VARCHAR(30) COMMENT '计费重',
    address1      VARCHAR(255) COMMENT '地址1',
    cnt           VARCHAR(30) COMMENT '',
    channelname   VARCHAR(60) COMMENT '渠道类型',
    sjtime        VARCHAR(20) COMMENT '送货时间/收件时间',
    sdcompanynm   VARCHAR(60) COMMENT '承运公司名称',
    primary key (dt, orderno, packno)
) comment ='快驿通-物流数据-张致富'
    partition by KEY (dt) partitions 3;
"""
ods_scg_wld_logistics_ahc_i_d_field_list = [
    'dt',
    'zztm',
    'orderret',
    'orderno',
    'qsdate',
    'dest',
    'jcnt',
    'postno',
    'zyday',
    'zycodehover',
    'podfile',
    'ysjweit',
    'sendmobi',
    'yczweit',
    'ycbmqty',
    'addnm',
    'sedprovinces',
    'sendbyaddress',
    'gsfile',
    'apimk',
    'delcompanynm',
    'phone',
    'contactsby',
    'channelprice',
    'packno',
    'sjdate',
    'tszl',
    'sedcity',
    'expresstype',
    'orgname',
    'bxflg',
    'supcode',
    'publicmk',
    'sendby',
    'kdzt',
    'bgtype',
    'address3',
    'qgtype',
    'address2',
    'yjfweit',
    'address1',
    'cnt',
    'channelname',
    'sjtime',
    'sdcompanynm',
]
ods_scg_wld_logistics_ahc_cost_table = "ods_prod.ods_scg_wld_logistics_ahc_cost_i_d"

ods_scg_wld_logistics_ahc_cost_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_ahc_cost_i_d
(
    yjcode   VARCHAR(50)  COMMENT '预检码',
    orderno  VARCHAR(50) COMMENT '系统订单号',
    prounit  VARCHAR(10) COMMENT '单位',
    oldprice VARCHAR(50) COMMENT '旧单价',
    cmp      VARCHAR(255) COMMENT '计算公式',
    amt      VARCHAR(50) COMMENT '原币金额',
    chargenm VARCHAR(255) COMMENT '费用类型',
    oldamt   VARCHAR(50) COMMENT '旧金额',
    url      VARCHAR(255) COMMENT '链接',
    costno   VARCHAR(20) COMMENT '成本编号',
    rate     VARCHAR(50) COMMENT '汇率',
    price    VARCHAR(50) COMMENT '单价',
    qty      VARCHAR(50) COMMENT '数量',
    yamt     VARCHAR(50) COMMENT '本位币金额',
    currency VARCHAR(10) COMMENT '货币',
    primary key (orderno, chargenm)
) comment ='快驿通-物流数据-张致富';
"""
ods_scg_wld_logistics_ahc_cost_i_d_field_list = [
    'yjcode',
    'orderno',
    'prounit',
    'oldprice',
    'cmp',
    'amt',
    'chargenm',
    'oldamt',
    'url',
    'costno',
    'rate',
    'price',
    'qty',
    'yamt',
    'currency',
]
ods_scg_wld_logistics_ahc_track_table = "ods_prod.ods_scg_wld_logistics_ahc_track_i_d"

ods_scg_wld_logistics_ahc_track_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_ahc_track_i_d
(
    orderno         VARCHAR(50) COMMENT '系统订单号',
    packno          VARCHAR(50) COMMENT '运单号',
    departure_date  VARCHAR(30) COMMENT '开航日期',
    clearance_date  VARCHAR(30) COMMENT '清关日期',
    extraction_date VARCHAR(30) COMMENT '提取日期',
    delivery_date   VARCHAR(30) COMMENT '派送日期',
    signing_date    VARCHAR(30) COMMENT '签收日期',
    primary key (orderno)
) comment ='快驿通-物流轨迹查询-张致富';
"""
ods_scg_wld_logistics_ahc_track_i_d_field_list = [
    'orderno',
    'packno',
    'departure_date',
    'clearance_date',
    'extraction_date',
    'delivery_date',
    'signing_date',
]

ods_scg_wld_logistics_ahc_cost_i_d_field_list = [
    'yjcode',
    'orderno',
    'prounit',
    'oldprice',
    'cmp',
    'amt',
    'chargenm',
    'oldamt',
    'url',
    'costno',
    'rate',
    'price',
    'qty',
    'yamt',
    'currency',
]
ods_scg_wld_logistics_zto_table = "ods_prod.ods_scg_wld_logistics_zto_i_d"

ods_scg_wld_logistics_zto_i_d = """
CREATE TABLE if not exists ods_prod.ods_scg_wld_logistics_zto_i_d
(
    dt                   varchar(10) COMMENT '收货时间',
    overdaysflag         varchar(5) COMMENT '超期标志',
    consigneetel         VARCHAR(20) COMMENT '',
    feepayaccountnumber  VARCHAR(50) COMMENT '',
    tracknumber          VARCHAR(400) COMMENT '转单号',
    tracknumberflag      varchar(20) COMMENT '',
    createdate           varchar(20) COMMENT '制单日期',
    deliverydate         varchar(20) COMMENT '提交日期',
    selleruserid         VARCHAR(20) COMMENT '销售员',
    orderdeclarecurrency VARCHAR(10) COMMENT '',
    number               VARCHAR(10) COMMENT '收货实重',
    declaretypepkid      VARCHAR(20) COMMENT '报关类型',
    forecastweight       VARCHAR(20) COMMENT '预测重量',
    clientname           VARCHAR(100) COMMENT '客户名称',
    sourcetype           VARCHAR(20) COMMENT '来源类型',
    rsubmissionflag      VARCHAR(20) COMMENT '提交标志',
    submissiontime       VARCHAR(20) COMMENT '',
    notifyzipcode        VARCHAR(20) COMMENT '',
    poanumber            VARCHAR(50) COMMENT 'POA编号',
    forecastmweight      VARCHAR(20) COMMENT '预测毛重',
    systemnumber         VARCHAR(50) COMMENT '系统编号',
    forecastsquare       VARCHAR(20) COMMENT '预测体积',
    showtracknumberflag  VARCHAR(20) COMMENT '',
    clientweight         VARCHAR(50) COMMENT '收货结算重',
    consigneeaddresstype VARCHAR(20) COMMENT '收件人地址类型',
    notifymoble          VARCHAR(20) COMMENT '通知手机号',
    taxpaytype           VARCHAR(20) COMMENT '税费支付类型',
    packingannex         VARCHAR(255) COMMENT '包装附件',
    editdate             VARCHAR(20) COMMENT '最后修改时间',
    consigneeprovince    VARCHAR(50) COMMENT '收件人省份',
    status               VARCHAR(50) COMMENT '状态',
    pickupnumber         VARCHAR(50) COMMENT '取件编号',
    freight              VARCHAR(50) COMMENT '运费',
    consigneecorpname    VARCHAR(100) COMMENT '收件人公司名称',
    errornote            VARCHAR(255) COMMENT '错误备注',
    taxpayzipcode        VARCHAR(20) COMMENT '税费支付邮政编码',
    senderaddresstype    VARCHAR(20) COMMENT '发件人地址类型',
    notifyprovince       VARCHAR(50) COMMENT '通知省份',
    ismagnet             VARCHAR(20) COMMENT '磁性标志',
    showaccountpkid      VARCHAR(20) COMMENT '显示账户ID',
    customernumber2      VARCHAR(50) COMMENT '客户编号2',
    pkid                 VARCHAR(20) not null COMMENT '主键ID',
    customernumber1      VARCHAR(50) not null COMMENT '客户参考号',
    density              VARCHAR(20) COMMENT '密度',
    notifyaddress1       VARCHAR(255) COMMENT '通知地址1',
    notifyaddress2       VARCHAR(255) COMMENT '通知地址2',
    notifyaddress3       VARCHAR(255) COMMENT '通知地址3',
    collectionpayment    VARCHAR(50) COMMENT '到付',
    feepaypostcode       VARCHAR(20) COMMENT '费用支付邮政编码',
    notifyfax            VARCHAR(20) COMMENT '通知传真',
    notifytel            VARCHAR(20) COMMENT '通知电话',
    showsystemnumber     VARCHAR(50) COMMENT '显示系统编号',
    goodstypecode        VARCHAR(20) COMMENT '货物类型',
    weightratio          VARCHAR(20) COMMENT '重量比例',
    residential          VARCHAR(20) COMMENT '住宅标志',
    consigneeaddress1    VARCHAR(255) COMMENT '收件人地址1',
    consigneeaddress2    VARCHAR(255) COMMENT '收件人地址2',
    printnumber          VARCHAR(20) COMMENT '打印次数',
    channelid            VARCHAR(100) COMMENT '收货渠道',
    showsplitsourcepkid  VARCHAR(20) COMMENT '显示分割源ID',
    taxpayaccountnumber  VARCHAR(50) COMMENT '税费支付账号',
    showcustomernumber1  VARCHAR(50) COMMENT '显示客户编号1',
    consigneename        VARCHAR(100) COMMENT '收件人姓名',
    clientcode           VARCHAR(50) COMMENT '客户代码',
    taxpaycountrycode    VARCHAR(10) COMMENT '税费支付国家代码',
    countrycode          VARCHAR(20) COMMENT '国家代码',
    inrweight            VARCHAR(50) COMMENT '收货实重',
    showsplitordertype   VARCHAR(20) COMMENT '显示分割订单类型',
    feepaycountrycode    VARCHAR(10) COMMENT '费用支付国家代码',
    pickupstatus         VARCHAR(20) COMMENT '取件状态',
    totalvalue           VARCHAR(20) COMMENT '总价值',
    numberForCal         VARCHAR(20) COMMENT '总件数',
    createusername       VARCHAR(50) COMMENT '制单人',
    ispaperless          VARCHAR(20) COMMENT '无纸化标志',
    showclientid         VARCHAR(50) COMMENT '显示客户ID',
    fbanumber            VARCHAR(100) COMMENT 'FBA ID',
    notifycity           VARCHAR(50) COMMENT '通知城市',
    feepaytype           VARCHAR(20) COMMENT '费用支付类型',
    showwaybillnumber    VARCHAR(50) COMMENT '运单号',
    notifycorpname       VARCHAR(100) COMMENT '通知公司名称',
    consigneecity        VARCHAR(50) COMMENT '收件人城市',
    square               VARCHAR(50) COMMENT '收货方数',
    otherfees            VARCHAR(50) COMMENT '其他费用',
    senderemail          VARCHAR(100) COMMENT '发件人邮箱',
    consigneezipcode     VARCHAR(20) COMMENT '邮编',
    checkflag            VARCHAR(20) COMMENT '检查标志',
    note                 VARCHAR(255) COMMENT '备注',
    showisproblem        VARCHAR(20) COMMENT '显示问题标志',
    clientrectype        VARCHAR(20) COMMENT '客户结算类型',
    inweight             VARCHAR(50) COMMENT '货结算重',
    waybillnumber        VARCHAR(50) COMMENT '运单号',
    notifyname           VARCHAR(100) COMMENT '通知姓名',
    inmweight            VARCHAR(50) COMMENT '内部毛重',
    borderAnnexName      VARCHAR(255) COMMENT '边境附件名称',
    overduedate          VARCHAR(20) COMMENT '逾期日期',
    isinsurance          VARCHAR(20) COMMENT '保险标志',
    showdeductiontype    VARCHAR(20) COMMENT '显示扣除类型',
    deductiontype        VARCHAR(20) COMMENT '扣除类型',
    isbattery            VARCHAR(20) COMMENT '电池标志',
    showeditformatpkid   VARCHAR(20) COMMENT '显示编辑格式ID',
    feepayname           VARCHAR(100) COMMENT '费用支付名称',
    receiptdate          VARCHAR(30) COMMENT '收货时间',
    receiptbatchnumber   VARCHAR(30) COMMENT '收货批次号',
    consigneeemail       VARCHAR(100) COMMENT '收件人邮箱',
    producttypepkid      VARCHAR(50) COMMENT '物品类别',
    insurancevalue       VARCHAR(50) COMMENT '保险价值',
    annex                VARCHAR(255) COMMENT '附件',
    label                VARCHAR(255) COMMENT '标签',
    forecastdate         VARCHAR(20) COMMENT '预报时间',
    isproblem            VARCHAR(20) COMMENT '问题标志',
    sitecode             VARCHAR(20) COMMENT '收货站点',
    taxpayname           VARCHAR(100) COMMENT '税费支付名称',
    fbawarehousecode     VARCHAR(50) COMMENT 'FBA仓库代码',
    primary key (dt, fbanumber, pkid)
) comment ='中通-物流数据-张致富';
"""
ods_scg_wld_logistics_zto_i_d_field_list = [
    'dt',
    'overdaysflag',
    'consigneetel',
    'feepayaccountnumber',
    'tracknumber',
    'tracknumberflag',
    'createdate',
    'deliverydate',
    'selleruserid',
    'orderdeclarecurrency',
    'number',
    'declaretypepkid',
    'forecastweight',
    'clientname',
    'sourcetype',
    'rsubmissionflag',
    'submissiontime',
    'notifyzipcode',
    'poanumber',
    'forecastmweight',
    'systemnumber',
    'forecastsquare',
    'showtracknumberflag',
    'clientweight',
    'consigneeaddresstype',
    'notifymoble',
    'taxpaytype',
    'packingannex',
    'editdate',
    'consigneeprovince',
    'status',
    'pickupnumber',
    'freight',
    'consigneecorpname',
    'errornote',
    'taxpayzipcode',
    'senderaddresstype',
    'notifyprovince',
    'ismagnet',
    'showaccountpkid',
    'customernumber2',
    'pkid',
    'customernumber1',
    'density',
    'notifyaddress1',
    'notifyaddress2',
    'notifyaddress3',
    'collectionpayment',
    'feepaypostcode',
    'notifyfax',
    'notifytel',
    'showsystemnumber',
    'goodstypecode',
    'weightratio',
    'residential',
    'consigneeaddress1',
    'consigneeaddress2',
    'printnumber',
    'channelid',
    'showsplitsourcepkid',
    'taxpayaccountnumber',
    'showcustomernumber1',
    'consigneename',
    'clientcode',
    'taxpaycountrycode',
    'countrycode',
    'inrweight',
    'showsplitordertype',
    'feepaycountrycode',
    'pickupstatus',
    'totalvalue',
    'numberForCal',
    'createusername',
    'ispaperless',
    'showclientid',
    'fbanumber',
    'notifycity',
    'feepaytype',
    'showwaybillnumber',
    'notifycorpname',
    'consigneecity',
    'square',
    'otherfees',
    'senderemail',
    'consigneezipcode',
    'checkflag',
    'note',
    'showisproblem',
    'clientrectype',
    'inweight',
    'waybillnumber',
    'notifyname',
    'inmweight',
    'borderAnnexName',
    'overduedate',
    'isinsurance',
    'showdeductiontype',
    'deductiontype',
    'isbattery',
    'showeditformatpkid',
    'feepayname',
    'receiptdate',
    'receiptbatchnumber',
    'consigneeemail',
    'producttypepkid',
    'insurancevalue',
    'annex',
    'label',
    'forecastdate',
    'isproblem',
    'sitecode',
    'taxpayname',
    'fbawarehousecode',
]

ods_scg_wld_logistics_zto_track_table = "ods_prod.ods_scg_wld_logistics_zto_track_i_d"

ods_scg_wld_logistics_zto_track_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_zto_track_i_d
(
    pkid            VARCHAR(50) COMMENT '系统单号',
    departure_date  VARCHAR(30) COMMENT '开航日期',
    clearance_date  VARCHAR(30) COMMENT '清关日期',
    extraction_date VARCHAR(30) COMMENT '提取日期',
    delivery_date   VARCHAR(30) COMMENT '派送日期',
    signing_date    VARCHAR(30) COMMENT '签收日期',
    primary key (pkid)
) comment ='中通-物流轨迹查询-张致富';
"""
ods_scg_wld_logistics_zto_track_i_d_field_list = [
    'pkid',
    'departure_date',
    'clearance_date',
    'extraction_date',
    'delivery_date',
    'signing_date',
]
