# -*- coding: utf-8 -*-
# @Time    : 2024/12/17 16:32
# @Author  : Night
# @File    : db_model.py
# @Description:
ods_cd_sl_vis_product_operation_inventory_i_d_db_table = "ods_prod.ods_cd_sl_vis_product_operation_inventory_i_d"

ods_cd_sl_vis_product_operation_inventory_i_d = """
create table if not exists ods_prod.ods_cd_sl_vis_product_operation_inventory_i_d
(
    dt                              varchar(10)  not null comment '统计日期',
    store                           varchar(30)  not null comment '公司店铺名',
    addItemNum                      varchar(30)  not null comment '',
    addRate                         varchar(30)  not null comment '',
    addUserNum                      varchar(30)  not null comment '',
    bctNewUser                      varchar(30)  not null comment '',
    brandStoreName                  varchar(30)  not null comment '品牌名称',
    brandStoreSn                    varchar(30)  not null comment '品牌SN',
    brandUserStrategyCostAmt        varchar(30)  not null comment '',
    brandUserStrategyGoodsActureAmt varchar(30)  not null comment '',
    brandUserStrategyRoi            varchar(30)  not null comment '',
    cartConvRate                    varchar(30)  not null comment '',
    channel                         varchar(30)  not null comment '',
    channelName                     varchar(30)  not null comment '',
    clickNum                        varchar(30)  not null comment '点击次数',
    couponAmt                       varchar(30)  not null comment '优惠券金额',
    ctr                             varchar(30)  not null comment '',
    discountRange                   varchar(30)  not null comment '',
    discountRangeName               varchar(30)  not null comment '打折',
    exchangeGoodsAmt                varchar(30)  not null comment '',
    exchangeItemNum                 varchar(30)  not null comment '',
    exchangeItemRate                varchar(30)  not null comment '',
    firstCateId                     varchar(30)  not null comment '',
    firstCateName                   varchar(30)  not null comment '',
    firstShelfTime                  varchar(30)  not null comment '首次上架时间',
    goodsActureAmt                  varchar(30)  not null comment '销售额',
    goodsActureNum                  varchar(30)  not null comment '销售量',
    goodsName                       varchar(200)  not null comment '商品名称',
    goodsNo                         varchar(30)  not null comment '',
    imgUrl                          varchar(200) not null comment '图片链接',
    impressionClickRate             varchar(30)  not null comment '曝光-点击率',
    impressionNum                   varchar(30)  not null comment '',
    impressionUv                    varchar(30)  not null comment '曝光UV',
    interestedUserMerNum            varchar(30)  not null comment '兴趣人次',
    interestedUserNum               varchar(30)  not null comment '兴趣人数',
    itemUnitPrice                   varchar(30)  not null comment '件单价',
    leavingNum                      varchar(30)  not null comment '在售库存',
    lighthouseStartTime             varchar(30)  not null comment '',
    lighthouseTypeList              varchar(200) not null comment '',
    mainStyleName                   varchar(30)  not null comment '鞋类',
    merchandiseLikeRate             varchar(30)  not null comment '',
    merchandiseLikeUserNum          varchar(30)  not null comment '',
    merchandiseNo                   varchar(30)  not null comment '',
    minMarketPrice                  varchar(30)  not null comment '最低市场价',
    minPayPrice                     varchar(30)  not null comment '最低到手价',
    minVipshopPrice                 varchar(30)  not null comment '最低唯品价',
    onSellLeavingNum                varchar(30)  not null comment '在售库存',
    onSellValueOfPay                varchar(30)  not null comment '在售到手价货值',
    onSellValueOfVipshop            varchar(30)  not null comment '在售唯品价货值',
    osn                             varchar(30)  not null comment '款号',
    pageMerDetailConvRate           varchar(30)  not null comment '购买转化率(客户数/商详UV)',
    pageMerDetailPv                 varchar(30)  not null comment '',
    prodSpuId                       varchar(30)  not null comment 'P_SPU_ID',
    productSellAge                  varchar(30)  not null comment '售龄',
    rejectAndReturnGoodsAmt         varchar(30)  not null comment '拒退金额',
    rejectAndReturnItemNum          varchar(30)  not null comment '拒退件数',
    rejectAndReturnItemRate         varchar(30)  not null comment '拒退率',
    rejectGoodsAmt                  varchar(30)  not null comment '拒收金额',
    rejectItemNum                   varchar(30)  not null comment '拒收件数',
    rejectItemRate                  varchar(30)  not null comment '换货率(换货件数/销售量)',
    resultGoodsActureAmt            varchar(30)  not null comment '销售额(不含拒退)',
    resultGoodsActureNum            varchar(30)  not null comment '销售量(不含拒退)',
    returnGoodsAmt                  varchar(30)  not null comment '退货金额',
    returnItemNum                   varchar(30)  not null comment '退货件数',
    returnItemRate                  varchar(30)  not null comment '退货率(退货件数/销售量)',
    salesRateOfNum                  varchar(30)  not null comment '货量售卖比',
    secCateId                       varchar(30)  not null comment '',
    secCateName                     varchar(30)  not null comment '鞋类分类',
    status                          varchar(30)  not null comment '状态',
    suitSeason                      varchar(30)  not null comment '',
    svipGoodsActureAmt              varchar(30)  not null comment '',
    svipUserNum                     varchar(30)  not null comment '',
    thirdCateId                     varchar(30)  not null comment '三级分类Id',
    thirdCateName                   varchar(30)  not null comment '三级分类名称',
    userNum                         varchar(30)  not null comment '客户数',
    userStrategyCostAmt             varchar(30)  not null comment '',
    userStrategyGoodsActureAmt      varchar(30)  not null comment '',
    userStrategyRoi                 varchar(30)  not null comment '',
    userUnitPrice                   varchar(30)  not null comment 'ARPU(销售额/客户数)',
    uv                              varchar(30)  not null comment '商详UV',
    valueOfImpressionUv             varchar(30)  not null comment '曝光UV价值',
    valueOfUv                       varchar(30)  not null comment '商详UV价值(销售额/商详UV)',
    wxkStrategyCostAmt              varchar(30)  not null comment '',
    wxkStrategyGoodsActureAmt       varchar(30)  not null comment '',
    wxkStrategyRoi                  varchar(30)  not null comment '',
    primary key (dt, store, osn)
) comment ='唯品会-货品运营-商品明细-张致富'
    partition by key (dt) partitions 3;
"""
ods_cd_sl_vis_product_operation_inventory_i_d_field_list = [
    'dt',
    'store',
    'addItemNum',
    'addRate',
    'addUserNum',
    'bctNewUser',
    'brandStoreName',
    'brandStoreSn',
    'brandUserStrategyCostAmt',
    'brandUserStrategyGoodsActureAmt',
    'brandUserStrategyRoi',
    'cartConvRate',
    'channel',
    'channelName',
    'clickNum',
    'couponAmt',
    'ctr',
    'discountRange',
    'discountRangeName',
    'exchangeGoodsAmt',
    'exchangeItemNum',
    'exchangeItemRate',
    'firstCateId',
    'firstCateName',
    'firstShelfTime',
    'goodsActureAmt',
    'goodsActureNum',
    'goodsName',
    'goodsNo',
    'imgUrl',
    'impressionClickRate',
    'impressionNum',
    'impressionUv',
    'interestedUserMerNum',
    'interestedUserNum',
    'itemUnitPrice',
    'leavingNum',
    'lighthouseStartTime',
    'lighthouseTypeList',
    'mainStyleName',
    'merchandiseLikeRate',
    'merchandiseLikeUserNum',
    'merchandiseNo',
    'minMarketPrice',
    'minPayPrice',
    'minVipshopPrice',
    'onSellLeavingNum',
    'onSellValueOfPay',
    'onSellValueOfVipshop',
    'osn',
    'pageMerDetailConvRate',
    'pageMerDetailPv',
    'prodSpuId',
    'productSellAge',
    'rejectAndReturnGoodsAmt',
    'rejectAndReturnItemNum',
    'rejectAndReturnItemRate',
    'rejectGoodsAmt',
    'rejectItemNum',
    'rejectItemRate',
    'resultGoodsActureAmt',
    'resultGoodsActureNum',
    'returnGoodsAmt',
    'returnItemNum',
    'returnItemRate',
    'salesRateOfNum',
    'secCateId',
    'secCateName',
    'status',
    'suitSeason',
    'svipGoodsActureAmt',
    'svipUserNum',
    'thirdCateId',
    'thirdCateName',
    'userNum',
    'userStrategyCostAmt',
    'userStrategyGoodsActureAmt',
    'userStrategyRoi',
    'userUnitPrice',
    'uv',
    'valueOfImpressionUv',
    'valueOfUv',
    'wxkStrategyCostAmt',
    'wxkStrategyGoodsActureAmt',
    'wxkStrategyRoi',
]
