# -*- coding: utf-8 -*-
# @Time    : 2024/8/14 9:30
# @Author  : gu tao
# @Email   : 1370391119@qq.com
# @File    : 
# @Software: 数据库sql语句配置文件

# ODS-GES-AUASIAN-AAF物流数据-辜涛:
ods_scg_wld_logistics_trace_db_table = "ods_prod.ods_scg_wld_logistics_trace_table_i_d"

ods_scg_wld_logistics_trace_table_i_d = """
                        CREATE TABLE IF NOT EXISTS ods_prod.`ods_scg_wld_logistics_trace_table_i_d`
                        (
                            `dt`                   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '下单日期',
                            `id`                   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT 'id',
                            `logistics_provider`   varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '物流商',
                            `shipment_id`          varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'FBA单号',
                            `shipment_number`      varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '快递单号',
                            `service`              varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '物流渠道',
                            `to_warehouse_code`    varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '地址库编码',
                            `to_address_name`      varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收件人',
                            `to_address_country`   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '国家',
                            `parcel_count`         varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '件数',
                            `declaration_value`    varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '价值',
                            `client_weight`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '客户重量',
                            `client_volume`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '客户体积',
                            `actual_weight`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '实重',
                            `actual_volume`        varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '体积',
                            `actual_volume_weight` varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '材重',
                            `chargeable_weight`    varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收费重',
                            `sell_charge_amount`   varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '销售费用金额',
                            `is_insurance`         varchar(500) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '购买保险',
                            `elec`                 varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '带电',
                            `exportwith`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '报关方式',
                            `importwith`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '清关方式',
                            `taxwith`              varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '交税方式',
                            `vat_number`           varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT 'VAT号',
                            `deliverywith`         varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '交货条款',
                            `outer_carrier`        varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '承运',
                            `courier_number`       varchar(225) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '快递单号',
                            `printed`              varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '打标状态',
                            `remark`               varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '备注',
                            `last_tracking`        varchar(512) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '最后路由',
                            `depot_id`             varchar(50) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '仓库id',
                            `created`              varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '下单时间',
                            `picking_time`         varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '拣货时间',
                            `delivered_time`       varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '签收时间',
                            `logistics_state`       varchar(20) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '物流状态(all,cancelled)',
                            PRIMARY KEY (`logistics_provider`, `shipment_number`,`shipment_id`) /*T![clustered_index] CLUSTERED */
                        ) ENGINE = InnoDB
                          DEFAULT CHARSET = utf8mb4
                          COLLATE = utf8mb4_general_ci COMMENT ='ODS-物流数据-辜涛';
                    """

truncate_ods_scg_wld_logistics_trace_table_i_d = "TRUNCATE TABLE ods_prod.ods_scg_wld_logistics_trace_table_i_d"

ods_scg_wld_logistics_trace_table_i_d_field_list = [
    "dt",
    "id",
    "logistics_provider",
    "shipment_id",
    "shipment_number",
    "service",
    "to_warehouse_code",
    "to_address_name",
    "to_address_country",
    "parcel_count",
    "declaration_value",
    "client_weight",
    "client_volume",
    "actual_weight",
    "actual_volume",
    "actual_volume_weight",
    "chargeable_weight",
    "sell_charge_amount",
    "is_insurance",
    "elec",
    "exportwith",
    "importwith",
    "taxwith",
    "vat_number",
    "deliverywith",
    "outer_carrier",
    "courier_number",
    "printed",
    "remark",
    "last_tracking",
    "depot_id",
    "created",
    "picking_time",
    "delivered_time",
    "logistics_state",
]

# ODS-GES-AUASIAN-AAF-view物流数据-辜涛:
ods_scg_wld_logistics_trace_db_view = "ods_prod.ods_scg_wld_logistics_trace_view_i_d"

ods_scg_wld_logistics_trace_view_i_d = """
                        CREATE TABLE IF NOT EXISTS ods_prod.`ods_scg_wld_logistics_trace_view_i_d`
                        (
                                `id`                     varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'id',
                                `logistics_provider`     varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '物流商',
                                `shipment_id`            varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'FBA单号',
                                `created`                 varchar(50) COLLATE utf8mb4_general_ci NOT NULL COMMENT '下单时间',
                                `sailing_date`           varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '开航日期',
                                `customs_clearance_date` varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '清关日期',
                                `fetch_date`             varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '提取日期',
                                `send_date`              varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '派送日期',
                                `receipt_date`           varchar(50) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '签收日期',
                            PRIMARY KEY (`logistics_provider`, `shipment_id`) /*T![clustered_index] CLUSTERED */
                        ) ENGINE = InnoDB
                          DEFAULT CHARSET = utf8mb4
                          COLLATE = utf8mb4_general_ci COMMENT ='ODS-物流数据-view-辜涛';
                    """

truncate_ods_scg_wld_logistics_trace_view_i_d = "TRUNCATE TABLE ods_prod.ods_scg_wld_logistics_trace_view_i_d"

ods_scg_wld_logistics_trace_view_i_d_field_list = [
    "id",
    "logistics_provider",
    "shipment_id",
    "created",
    "sailing_date",
    "customs_clearance_date",
    "fetch_date",
    "send_date",
    "receipt_date",
]

# ODS-K5-tw-天伟物流数据-辜涛:
ods_scg_wld_tw_logistics_trace_db_table = "ods_prod.ods_scg_wld_tw_logistics_trace_table_i_d"

ods_scg_wld_tw_logistics_trace_table_i_d = """
                        CREATE TABLE IF NOT EXISTS ods_prod.`ods_scg_wld_tw_logistics_trace_table_i_d`
                        (
                            `Tracking_number`       varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT '运单号',
                            `Transfer_order_number` varchar(20) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '转单号',
                            `order_number`          varchar(20) COLLATE utf8mb4_general_ci  NOT NULL COMMENT '订单号',
                            `Customer_order_number` varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '客户订单号',
                            `Receiving_channels`    varchar(10) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收货渠道',
                            `destination`           varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '目的地',
                            `parcel_count`          varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '件数',
                            `article_name`          varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '品名',
                            `Declared_value`        varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '申报价值',
                            `Tracking_status`       varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '运单状态',
                            `Warehousing_time`      varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '入仓时间',
                            `remark`                varchar(200) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '备注',
                            `Recipient_name`        varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '收件人名称',
                            `Volume`                varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '材积',
                            `Solid_weight`          varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '实重',
                            `Settlement_weight`     varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '结算重',
                            `zip_code`              varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '邮编',
                            `operate`               varchar(20) COLLATE utf8mb4_general_ci  DEFAULT NULL COMMENT '操作',
                            `logistics_state_code`  varchar(10) COLLATE utf8mb4_general_ci NOT NULL COMMENT '物流状态(默认0)',
                            PRIMARY KEY (`Tracking_number`, `Transfer_order_number`, `order_number`) /*T![clustered_index] CLUSTERED */
                        ) ENGINE = InnoDB
                          DEFAULT CHARSET = utf8mb4
                          COLLATE = utf8mb4_general_ci COMMENT ='ODS-天伟物流数据-辜涛';
                    """

truncate_ods_scg_wld_tw_logistics_trace_table_i_d = "TRUNCATE TABLE ods_prod.ods_scg_wld_tw_logistics_trace_table_i_d"

ods_scg_wld_tw_logistics_trace_table_i_d_field_list = [
    "Tracking_number",
    "Transfer_order_number",
    "order_number",
    "Customer_order_number",
    "Receiving_channels",
    "destination",
    "parcel_count",
    "article_name",
    "Declared_value",
    "Tracking_status",
    "Warehousing_time",
    "remark",
    "Recipient_name",
    "Volume",
    "Solid_weight",
    "Settlement_weight",
    "zip_code",
    "operate",
    "logistics_state_code",
]

# 致富
ods_scg_wld_logistics_ahc_table = "ods_prod.ods_scg_wld_logistics_ahc_i_d"

ods_scg_wld_logistics_ahc_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_ahc_i_d
(
    dt            varchar(10)  not null comment '送货时间',
    zztm          varchar(20)  not null comment '轨迹时间',
    orderret      varchar(30)  not null comment '状态',
    orderno       varchar(40)  not null comment '系统订单号',
    qsdate        varchar(40)  not null comment '',
    dest          varchar(40)  not null comment '目的地',
    jcnt          varchar(20)  not null comment '件数',
    postno        varchar(20)  not null comment '收件邮编',
    zyday         varchar(20)  not null comment '',
    zycodehover   text         not null comment '转运单号',
    podfile       varchar(20)  not null comment '',
    ysjweit       varchar(20)  not null comment '材重',
    sendmobi      varchar(40)  not null comment '',
    yczweit       varchar(20)  not null comment '实重',
    ycbmqty       varchar(20)  not null comment '方数',
    addnm         varchar(20)  not null comment '仓库代码',
    sedprovinces  varchar(40)  not null comment '省份/州',
    sendbyaddress varchar(400) not null comment '地址',
    gsfile        varchar(20)  not null comment '',
    apimk         varchar(20)  not null comment '',
    delcompanynm  varchar(80)  not null comment '收货公司名',
    phone         varchar(30)  not null comment '收货人电话',
    contactsby    varchar(100) not null comment '收货人名',
    channelprice  varchar(20)  not null comment '价格渠道',
    packno        varchar(80)  not null comment '运单号',
    sjdate        varchar(20)  not null comment '送货日期',
    tszl          varchar(20)  not null comment '',
    sedcity       varchar(100) not null comment '城市/州',
    expresstype   varchar(20)  not null comment '快递类型',
    orgname       varchar(20)  not null comment '发货仓库',
    bxflg         VARCHAR(5) COMMENT '保险标志',
    supcode       VARCHAR(50) COMMENT '客户单号',
    publicmk      VARCHAR(20) COMMENT '',
    sendby        VARCHAR(20) COMMENT '',
    kdzt          VARCHAR(30) COMMENT '快递状态',
    bgtype        VARCHAR(30) COMMENT '报关方式',
    address3      VARCHAR(200) COMMENT '地址3',
    qgtype        VARCHAR(30) COMMENT '清关方式',
    address2      VARCHAR(200) COMMENT '地址2',
    yjfweit       VARCHAR(30) COMMENT '计费重',
    address1      VARCHAR(255) COMMENT '地址1',
    cnt           VARCHAR(30) COMMENT '',
    channelname   VARCHAR(60) COMMENT '渠道类型',
    sjtime        VARCHAR(20) COMMENT '送货时间/收件时间',
    sdcompanynm   VARCHAR(60) COMMENT '承运公司名称',
    primary key (dt, orderno, packno)
) comment ='快驿通-物流数据-张致富'
    partition by KEY (dt) partitions 3;
"""
ods_scg_wld_logistics_ahc_i_d_field_list = [
    'dt',
    'zztm',
    'orderret',
    'orderno',
    'qsdate',
    'dest',
    'jcnt',
    'postno',
    'zyday',
    'zycodehover',
    'podfile',
    'ysjweit',
    'sendmobi',
    'yczweit',
    'ycbmqty',
    'addnm',
    'sedprovinces',
    'sendbyaddress',
    'gsfile',
    'apimk',
    'delcompanynm',
    'phone',
    'contactsby',
    'channelprice',
    'packno',
    'sjdate',
    'tszl',
    'sedcity',
    'expresstype',
    'orgname',
    'bxflg',
    'supcode',
    'publicmk',
    'sendby',
    'kdzt',
    'bgtype',
    'address3',
    'qgtype',
    'address2',
    'yjfweit',
    'address1',
    'cnt',
    'channelname',
    'sjtime',
    'sdcompanynm',
]
ods_scg_wld_logistics_ahc_cost_table = "ods_prod.ods_scg_wld_logistics_ahc_cost_i_d"

ods_scg_wld_logistics_ahc_cost_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_ahc_cost_i_d
(
    yjcode   VARCHAR(50)  COMMENT '预检码',
    orderno  VARCHAR(50) COMMENT '系统订单号',
    prounit  VARCHAR(10) COMMENT '单位',
    oldprice VARCHAR(50) COMMENT '旧单价',
    cmp      VARCHAR(255) COMMENT '计算公式',
    amt      VARCHAR(50) COMMENT '原币金额',
    chargenm VARCHAR(255) COMMENT '费用类型',
    oldamt   VARCHAR(50) COMMENT '旧金额',
    url      VARCHAR(255) COMMENT '链接',
    costno   VARCHAR(20) COMMENT '成本编号',
    rate     VARCHAR(50) COMMENT '汇率',
    price    VARCHAR(50) COMMENT '单价',
    qty      VARCHAR(50) COMMENT '数量',
    yamt     VARCHAR(50) COMMENT '本位币金额',
    currency VARCHAR(10) COMMENT '货币',
    primary key (orderno, chargenm)
) comment ='快驿通-物流数据-张致富';
"""
ods_scg_wld_logistics_ahc_cost_i_d_field_list = [
    'yjcode',
    'orderno',
    'prounit',
    'oldprice',
    'cmp',
    'amt',
    'chargenm',
    'oldamt',
    'url',
    'costno',
    'rate',
    'price',
    'qty',
    'yamt',
    'currency',
]
ods_scg_wld_logistics_ahc_track_table = "ods_prod.ods_scg_wld_logistics_ahc_track_i_d"

ods_scg_wld_logistics_ahc_track_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_ahc_track_i_d
(
    orderno         VARCHAR(50) COMMENT '系统订单号',
    packno          VARCHAR(50) COMMENT '运单号',
    departure_date  VARCHAR(30) COMMENT '开航日期',
    clearance_date  VARCHAR(30) COMMENT '清关日期',
    extraction_date VARCHAR(30) COMMENT '提取日期',
    delivery_date   VARCHAR(30) COMMENT '派送日期',
    signing_date    VARCHAR(30) COMMENT '签收日期',
    primary key (orderno)
) comment ='快驿通-物流轨迹查询-张致富';
"""
ods_scg_wld_logistics_ahc_track_i_d_field_list = [
    'orderno',
    'packno',
    'departure_date',
    'clearance_date',
    'extraction_date',
    'delivery_date',
    'signing_date',
]

ods_scg_wld_logistics_ahc_cost_i_d_field_list = [
    'yjcode',
    'orderno',
    'prounit',
    'oldprice',
    'cmp',
    'amt',
    'chargenm',
    'oldamt',
    'url',
    'costno',
    'rate',
    'price',
    'qty',
    'yamt',
    'currency',
]
ods_scg_wld_logistics_zto_table = "ods_prod.ods_scg_wld_logistics_zto_i_d"

ods_scg_wld_logistics_zto_i_d = """
CREATE TABLE if not exists ods_prod.ods_scg_wld_logistics_zto_i_d
(
    dt                   varchar(10) COMMENT '收货时间',
    overdaysflag         varchar(5) COMMENT '超期标志',
    consigneetel         VARCHAR(20) COMMENT '',
    feepayaccountnumber  VARCHAR(50) COMMENT '',
    tracknumber          VARCHAR(400) COMMENT '转单号',
    tracknumberflag      varchar(20) COMMENT '',
    createdate           varchar(20) COMMENT '制单日期',
    deliverydate         varchar(20) COMMENT '提交日期',
    selleruserid         VARCHAR(20) COMMENT '销售员',
    orderdeclarecurrency VARCHAR(10) COMMENT '',
    number               VARCHAR(10) COMMENT '收货实重',
    declaretypepkid      VARCHAR(20) COMMENT '报关类型',
    forecastweight       VARCHAR(20) COMMENT '预测重量',
    clientname           VARCHAR(100) COMMENT '客户名称',
    sourcetype           VARCHAR(20) COMMENT '来源类型',
    rsubmissionflag      VARCHAR(20) COMMENT '提交标志',
    submissiontime       VARCHAR(20) COMMENT '',
    notifyzipcode        VARCHAR(20) COMMENT '',
    poanumber            VARCHAR(50) COMMENT 'POA编号',
    forecastmweight      VARCHAR(20) COMMENT '预测毛重',
    systemnumber         VARCHAR(50) COMMENT '系统编号',
    forecastsquare       VARCHAR(20) COMMENT '预测体积',
    showtracknumberflag  VARCHAR(20) COMMENT '',
    clientweight         VARCHAR(50) COMMENT '收货结算重',
    consigneeaddresstype VARCHAR(20) COMMENT '收件人地址类型',
    notifymoble          VARCHAR(20) COMMENT '通知手机号',
    taxpaytype           VARCHAR(20) COMMENT '税费支付类型',
    packingannex         VARCHAR(255) COMMENT '包装附件',
    editdate             VARCHAR(20) COMMENT '最后修改时间',
    consigneeprovince    VARCHAR(50) COMMENT '收件人省份',
    status               VARCHAR(50) COMMENT '状态',
    pickupnumber         VARCHAR(50) COMMENT '取件编号',
    freight              VARCHAR(50) COMMENT '运费',
    consigneecorpname    VARCHAR(100) COMMENT '收件人公司名称',
    errornote            VARCHAR(255) COMMENT '错误备注',
    taxpayzipcode        VARCHAR(20) COMMENT '税费支付邮政编码',
    senderaddresstype    VARCHAR(20) COMMENT '发件人地址类型',
    notifyprovince       VARCHAR(50) COMMENT '通知省份',
    ismagnet             VARCHAR(20) COMMENT '磁性标志',
    showaccountpkid      VARCHAR(20) COMMENT '显示账户ID',
    customernumber2      VARCHAR(50) COMMENT '客户编号2',
    pkid                 VARCHAR(20) not null COMMENT '主键ID',
    customernumber1      VARCHAR(50) not null COMMENT '客户参考号',
    density              VARCHAR(20) COMMENT '密度',
    notifyaddress1       VARCHAR(255) COMMENT '通知地址1',
    notifyaddress2       VARCHAR(255) COMMENT '通知地址2',
    notifyaddress3       VARCHAR(255) COMMENT '通知地址3',
    collectionpayment    VARCHAR(50) COMMENT '到付',
    feepaypostcode       VARCHAR(20) COMMENT '费用支付邮政编码',
    notifyfax            VARCHAR(20) COMMENT '通知传真',
    notifytel            VARCHAR(20) COMMENT '通知电话',
    showsystemnumber     VARCHAR(50) COMMENT '显示系统编号',
    goodstypecode        VARCHAR(20) COMMENT '货物类型',
    weightratio          VARCHAR(20) COMMENT '重量比例',
    residential          VARCHAR(20) COMMENT '住宅标志',
    consigneeaddress1    VARCHAR(255) COMMENT '收件人地址1',
    consigneeaddress2    VARCHAR(255) COMMENT '收件人地址2',
    printnumber          VARCHAR(20) COMMENT '打印次数',
    channelid            VARCHAR(100) COMMENT '收货渠道',
    showsplitsourcepkid  VARCHAR(20) COMMENT '显示分割源ID',
    taxpayaccountnumber  VARCHAR(50) COMMENT '税费支付账号',
    showcustomernumber1  VARCHAR(50) COMMENT '显示客户编号1',
    consigneename        VARCHAR(100) COMMENT '收件人姓名',
    clientcode           VARCHAR(50) COMMENT '客户代码',
    taxpaycountrycode    VARCHAR(10) COMMENT '税费支付国家代码',
    countrycode          VARCHAR(20) COMMENT '国家代码',
    inrweight            VARCHAR(50) COMMENT '收货实重',
    showsplitordertype   VARCHAR(20) COMMENT '显示分割订单类型',
    feepaycountrycode    VARCHAR(10) COMMENT '费用支付国家代码',
    pickupstatus         VARCHAR(20) COMMENT '取件状态',
    totalvalue           VARCHAR(20) COMMENT '总价值',
    numberForCal         VARCHAR(20) COMMENT '总件数',
    createusername       VARCHAR(50) COMMENT '制单人',
    ispaperless          VARCHAR(20) COMMENT '无纸化标志',
    showclientid         VARCHAR(50) COMMENT '显示客户ID',
    fbanumber            VARCHAR(100) COMMENT 'FBA ID',
    notifycity           VARCHAR(50) COMMENT '通知城市',
    feepaytype           VARCHAR(20) COMMENT '费用支付类型',
    showwaybillnumber    VARCHAR(50) COMMENT '运单号',
    notifycorpname       VARCHAR(100) COMMENT '通知公司名称',
    consigneecity        VARCHAR(50) COMMENT '收件人城市',
    square               VARCHAR(50) COMMENT '收货方数',
    otherfees            VARCHAR(50) COMMENT '其他费用',
    senderemail          VARCHAR(100) COMMENT '发件人邮箱',
    consigneezipcode     VARCHAR(20) COMMENT '邮编',
    checkflag            VARCHAR(20) COMMENT '检查标志',
    note                 VARCHAR(255) COMMENT '备注',
    showisproblem        VARCHAR(20) COMMENT '显示问题标志',
    clientrectype        VARCHAR(20) COMMENT '客户结算类型',
    inweight             VARCHAR(50) COMMENT '货结算重',
    waybillnumber        VARCHAR(50) COMMENT '运单号',
    notifyname           VARCHAR(100) COMMENT '通知姓名',
    inmweight            VARCHAR(50) COMMENT '内部毛重',
    borderAnnexName      VARCHAR(255) COMMENT '边境附件名称',
    overduedate          VARCHAR(20) COMMENT '逾期日期',
    isinsurance          VARCHAR(20) COMMENT '保险标志',
    showdeductiontype    VARCHAR(20) COMMENT '显示扣除类型',
    deductiontype        VARCHAR(20) COMMENT '扣除类型',
    isbattery            VARCHAR(20) COMMENT '电池标志',
    showeditformatpkid   VARCHAR(20) COMMENT '显示编辑格式ID',
    feepayname           VARCHAR(100) COMMENT '费用支付名称',
    receiptdate          VARCHAR(30) COMMENT '收货时间',
    receiptbatchnumber   VARCHAR(30) COMMENT '收货批次号',
    consigneeemail       VARCHAR(100) COMMENT '收件人邮箱',
    producttypepkid      VARCHAR(50) COMMENT '物品类别',
    insurancevalue       VARCHAR(50) COMMENT '保险价值',
    annex                VARCHAR(255) COMMENT '附件',
    label                VARCHAR(255) COMMENT '标签',
    forecastdate         VARCHAR(20) COMMENT '预报时间',
    isproblem            VARCHAR(20) COMMENT '问题标志',
    sitecode             VARCHAR(20) COMMENT '收货站点',
    taxpayname           VARCHAR(100) COMMENT '税费支付名称',
    fbawarehousecode     VARCHAR(50) COMMENT 'FBA仓库代码',
    primary key (fbanumber, pkid)
) comment ='中通-物流数据-张致富';
"""
ods_scg_wld_logistics_zto_i_d_field_list = [
    'dt',
    'overdaysflag',
    'consigneetel',
    'feepayaccountnumber',
    'tracknumber',
    'tracknumberflag',
    'createdate',
    'deliverydate',
    'selleruserid',
    'orderdeclarecurrency',
    'number',
    'declaretypepkid',
    'forecastweight',
    'clientname',
    'sourcetype',
    'rsubmissionflag',
    'submissiontime',
    'notifyzipcode',
    'poanumber',
    'forecastmweight',
    'systemnumber',
    'forecastsquare',
    'showtracknumberflag',
    'clientweight',
    'consigneeaddresstype',
    'notifymoble',
    'taxpaytype',
    'packingannex',
    'editdate',
    'consigneeprovince',
    'status',
    'pickupnumber',
    'freight',
    'consigneecorpname',
    'errornote',
    'taxpayzipcode',
    'senderaddresstype',
    'notifyprovince',
    'ismagnet',
    'showaccountpkid',
    'customernumber2',
    'pkid',
    'customernumber1',
    'density',
    'notifyaddress1',
    'notifyaddress2',
    'notifyaddress3',
    'collectionpayment',
    'feepaypostcode',
    'notifyfax',
    'notifytel',
    'showsystemnumber',
    'goodstypecode',
    'weightratio',
    'residential',
    'consigneeaddress1',
    'consigneeaddress2',
    'printnumber',
    'channelid',
    'showsplitsourcepkid',
    'taxpayaccountnumber',
    'showcustomernumber1',
    'consigneename',
    'clientcode',
    'taxpaycountrycode',
    'countrycode',
    'inrweight',
    'showsplitordertype',
    'feepaycountrycode',
    'pickupstatus',
    'totalvalue',
    'numberForCal',
    'createusername',
    'ispaperless',
    'showclientid',
    'fbanumber',
    'notifycity',
    'feepaytype',
    'showwaybillnumber',
    'notifycorpname',
    'consigneecity',
    'square',
    'otherfees',
    'senderemail',
    'consigneezipcode',
    'checkflag',
    'note',
    'showisproblem',
    'clientrectype',
    'inweight',
    'waybillnumber',
    'notifyname',
    'inmweight',
    'borderAnnexName',
    'overduedate',
    'isinsurance',
    'showdeductiontype',
    'deductiontype',
    'isbattery',
    'showeditformatpkid',
    'feepayname',
    'receiptdate',
    'receiptbatchnumber',
    'consigneeemail',
    'producttypepkid',
    'insurancevalue',
    'annex',
    'label',
    'forecastdate',
    'isproblem',
    'sitecode',
    'taxpayname',
    'fbawarehousecode',
]

ods_scg_wld_logistics_zto_track_table = "ods_prod.ods_scg_wld_logistics_zto_track_i_d"

ods_scg_wld_logistics_zto_track_i_d = """
create table if not exists ods_prod.ods_scg_wld_logistics_zto_track_i_d
(
    pkid            VARCHAR(50) COMMENT '系统单号',
    departure_date  VARCHAR(30) COMMENT '开航日期',
    clearance_date  VARCHAR(30) COMMENT '清关日期',
    extraction_date VARCHAR(30) COMMENT '提取日期',
    delivery_date   VARCHAR(30) COMMENT '派送日期',
    signing_date    VARCHAR(30) COMMENT '签收日期',
    primary key (pkid)
) comment ='中通-物流轨迹查询-张致富';
"""
ods_scg_wld_logistics_zto_track_i_d_field_list = [
    'pkid',
    'departure_date',
    'clearance_date',
    'extraction_date',
    'delivery_date',
    'signing_date',
]
# 亚豹海外仓
ods_scg_wld_yabao_dropshipping_order_table = "ods_prod.ods_scg_wld_yabao_dropshipping_order_i_d"

ods_scg_wld_yabao_dropshipping_order_i_d = """
create table if not exists ods_prod.ods_scg_wld_yabao_dropshipping_order_i_d
(
    dt              varchar(10) comment '创建时间',
    Code            varchar(30) comment '运输方式',
    ConsigneeName   varchar(30) comment '收件人姓名',
    CountryCode     varchar(20) comment '国家',
    CountryName     varchar(30) comment '目的地国家',
    CreateTime      varchar(30) comment '创建时间',
    CsRefNo         varchar(200) comment '参考号',
    DeductionWeight varchar(10) comment '计费重量',
    DeliveryTime    varchar(20) comment '出库时间',
    LabelUrl        varchar(80) comment '文件链接',
    MarkColor       varchar(30) comment '',
    OrderMainID     varchar(10) comment '订单详情id',
    OrderNo         varchar(30) comment '订单号',
    OrderStatus     varchar(20) comment '订单状态(4.已出库)',
    PlatformName    varchar(30) comment '',
    PlatformStatus  varchar(30) comment '',
    Quantity        varchar(5) comment '数量',
    RN              varchar(5) comment '',
    SKU             varchar(30) comment 'SKU',
    StockCode       varchar(20) comment '仓库编码',
    StockName       varchar(60) comment '仓库编',
    TotalAmount     varchar(20) comment '总费用',
    TrackingNo      varchar(40) comment '跟踪号',
    VQuantity       varchar(20) comment '数量',
    Zipcode         varchar(30) comment '邮编',
    primary key (dt,OrderNo)
) comment ='亚豹海外仓-代发订单已出库-张致富';
"""
ods_scg_wld_yabao_dropshipping_order_i_d_field_list = [
    'dt',
    'Code',
    'ConsigneeName',
    'CountryCode',
    'CountryName',
    'CreateTime',
    'CsRefNo',
    'DeductionWeight',
    'DeliveryTime',
    'LabelUrl',
    'MarkColor',
    'OrderMainID',
    'OrderNo',
    'OrderStatus',
    'PlatformName',
    'PlatformStatus',
    'Quantity',
    'RN',
    'SKU',
    'StockCode',
    'StockName',
    'TotalAmount',
    'TrackingNo',
    'VQuantity',
    'Zipcode',
]

ods_scg_wld_yabao_dropshipping_order_detail_table = "ods_prod.ods_scg_wld_yabao_dropshipping_order_detail_i_d"

ods_scg_wld_yabao_dropshipping_order_detail_i_d = """
create table if not exists ods_prod.ods_scg_wld_yabao_dropshipping_order_detail_i_d
(

    OrderMainID varchar(10) comment '订单详情id',
    CnName      varchar(30) comment '鞋类',
    EnName      varchar(30) comment '英文鞋类',
    HsCode      varchar(30) comment '',
    Origin      varchar(30) comment '',
    Price       varchar(5) comment '单价',
    Quantity    varchar(5) comment '数量',
    RealVolume  varchar(30) comment '长*宽*高(CM)',
    RealWeight  varchar(20) comment '体积重',
    SKU         varchar(60) comment 'SKU',
    Volume      varchar(30) comment '长*宽*高(CM)',
    Weight      varchar(20) comment '体积重',
    primary key (OrderMainID, SKU)
) comment ='亚豹海外仓-代发订单已出库详情-张致富';
"""
ods_scg_wld_yabao_dropshipping_order_detail_i_d_field_list = [
    'OrderMainID',
    'CnName',
    'EnName',
    'HsCode',
    'Origin',
    'Price',
    'Quantity',
    'RealVolume',
    'RealWeight',
    'SKU',
    'Volume',
    'Weight',
]

ods_scg_wld_yabao_inbound_order_list_table = "ods_prod.ods_scg_wld_yabao_inbound_order_list_i_d"

ods_scg_wld_yabao_inbound_order_list_i_d = """
create table if not exists ods_prod.ods_scg_wld_yabao_inbound_order_list_i_d
(
    dt              varchar(10) comment '创建时间',
    ActualBoxNumber varchar(10) comment '总箱数',
    ActualQty       varchar(10) comment '已上架数量',
    ApproveStatus   varchar(20) comment '',
    ApproveTime     varchar(30) comment '',
    ApproveUser     varchar(30) comment '',
    BoxNumber       varchar(200) comment '收货箱数',
    Code            varchar(30) comment '仓库',
    CreateTime      varchar(20) comment '创建日期',
    CreateUser      varchar(30) comment '创建人',
    CustomerID      varchar(30) comment '客户id',
    DeliveryStyle   varchar(20) comment '',
    EnName          varchar(30) comment '',
    EntryNo         varchar(20) comment '入库单号',
    EntryOrderID    varchar(30) comment '入库id',
    EntryStatus     varchar(30) comment '入库状态',
    EntryType       varchar(5) comment '入库类型',
    ExpectTime      varchar(20) comment '',
    FailQty         varchar(5) comment '不合格数量',
    IsForecast      varchar(5) comment '',
    ModifyTime      varchar(20) comment '上架时间',
    ModifyUser      varchar(20) comment '用户',
    Name            varchar(30) comment '仓库',
    PickupTime      varchar(20) comment '',
    PlanQty         varchar(5) comment '预约入库数量',
    RN              varchar(5) comment '',
    ReceiptTime     varchar(20) comment '到仓时间',
    Remark          varchar(200) comment '备注',
    ShelvesQty      varchar(5) comment '合格数量',
    StockID         varchar(5) comment '收货id',
    StockRemark     varchar(200) comment '收货备注',
    TrackingNo      varchar(20) comment '跟踪号',
    Weight          varchar(5) comment '收货重量',
    sCOUNT          varchar(5) comment 'SKU数量',
    primary key (dt, EntryNo)
) comment ='亚豹海外仓-入库单列表-张致富';
"""
ods_scg_wld_yabao_inbound_order_list_i_d_field_list = [
    'dt',
    'ActualBoxNumber',
    'ActualQty',
    'ApproveStatus',
    'ApproveTime',
    'ApproveUser',
    'BoxNumber',
    'Code',
    'CreateTime',
    'CreateUser',
    'CustomerID',
    'DeliveryStyle',
    'EnName',
    'EntryNo',
    'EntryOrderID',
    'EntryStatus',
    'EntryType',
    'ExpectTime',
    'FailQty',
    'IsForecast',
    'ModifyTime',
    'ModifyUser',
    'Name',
    'PickupTime',
    'PlanQty',
    'RN',
    'ReceiptTime',
    'Remark',
    'ShelvesQty',
    'StockID',
    'StockRemark',
    'TrackingNo',
    'Weight',
    'sCOUNT',
]

ods_scg_wld_yabao_inbound_order_detail_table = "ods_prod.ods_scg_wld_yabao_inbound_order_detail_i_d"

ods_scg_wld_yabao_inbound_order_detail_i_d = """
create table if not exists ods_prod.ods_scg_wld_yabao_inbound_order_detail_i_d
(
    dt                 varchar(10) comment '创建时间',
    ActualQty          varchar(10) comment '已上架数量',
    BoxPcs             varchar(10) comment '',
    BoxQty             varchar(10) comment '箱数',
    BoxQuantity        varchar(10) comment '单箱重量(KG)',
    CartonNo           varchar(10) comment '箱号',
    CartonSize         varchar(30) comment '纸箱尺寸',
    CnName             varchar(20) comment '中文名称',
    ConfirmQty         varchar(5) comment '',
    CreateTime         varchar(20) comment '创建日期',
    CreateUser         varchar(30) comment '创建人',
    EnName             varchar(30) comment '英文名称',
    EntryOrderDetailID varchar(10) comment '入库详情id',
    EntryOrderID       varchar(10) comment '入库id',
    FailQty            varchar(5) comment '不合格数量',
    GoodsCode          varchar(30) comment '条形码',
    GoodsID            varchar(5) comment '条形id',
    InstructFile       varchar(20) comment '',
    IsCheck            varchar(5) comment '用户',
    IsFee              varchar(5) comment '',
    IsShelves          varchar(5) comment '',
    ModifyTime         varchar(20) comment '上架时间',
    ModifyUser         varchar(20) comment '用户',
    PlanQty            varchar(5) comment '预约入库数量',
    RN                 varchar(5) comment '',
    Remark             varchar(200) comment '备注',
    SKU                varchar(30) comment 'SKU',
    SKUNumber          varchar(10) comment '',
    ShelvesQty         varchar(5) comment '合格数量',
    ShelvesTime        varchar(20) comment '',
    ShelvesUser        varchar(20) comment '',
    SingleWeight       varchar(5) comment '',
    primary key (dt, EntryOrderID, SKU)
) comment ='亚豹海外仓-入库单详情-张致富';
"""
ods_scg_wld_yabao_inbound_order_detail_i_d_field_list = [
    'dt',
    'ActualQty',
    'BoxPcs',
    'BoxQty',
    'BoxQuantity',
    'CartonNo',
    'CartonSize',
    'CnName',
    'ConfirmQty',
    'CreateTime',
    'CreateUser',
    'EnName',
    'EntryOrderDetailID',
    'EntryOrderID',
    'FailQty',
    'GoodsCode',
    'GoodsID',
    'InstructFile',
    'IsCheck',
    'IsFee',
    'IsShelves',
    'ModifyTime',
    'ModifyUser',
    'PlanQty',
    'RN',
    'Remark',
    'SKU',
    'SKUNumber',
    'ShelvesQty',
    'ShelvesTime',
    'ShelvesUser',
    'SingleWeight',
]
ods_scg_wld_yabao_bill_detail_table = "ods_prod.ods_scg_wld_yabao_bill_detail_i_d"

ods_scg_wld_yabao_bill_detail_i_d = """
create table if not exists ods_prod.ods_scg_wld_yabao_bill_detail_i_d
(
    dt              varchar(10) comment '创建时间',
    Balance         varchar(15) comment '余额',
    CreateTime      varchar(20) comment '创建日期',
    CsRefNo         varchar(200) comment '参考号',
    DCode           varchar(20) comment '国家',
    DeductionWeight varchar(10) comment '计费重量',
    ECode           varchar(20) comment '运输方式',
    IncomeMoney     varchar(10) comment '入账',
    OrderNo         varchar(30) comment '订单号',
    OutcomeMoney    varchar(10) comment '出账',
    RN              varchar(5) comment '',
    Remark          text comment '备注',
    SStyle          varchar(20) comment '类型',
    StockName       varchar(15) comment '仓库',
    Style           varchar(5) comment '类型id',
    TrackingNo      varchar(40) comment '跟踪号'
) comment ='亚豹海外仓-账单明细-张致富';
"""
ods_scg_wld_yabao_bill_detail_i_d_field_list = [
    'dt',
    'Balance',
    'CreateTime',
    'CsRefNo',
    'DCode',
    'DeductionWeight',
    'ECode',
    'IncomeMoney',
    'OrderNo',
    'OutcomeMoney',
    'RN',
    'Remark',
    'SStyle',
    'StockName',
    'Style',
    'TrackingNo',
]

# 酷麓海外仓
ods_scg_wld_kulu_inbound_warehouse_management_table = "ods_prod.ods_scg_wld_kulu_inbound_warehouse_management_i_d"

ods_scg_wld_kulu_inbound_warehouse_management_i_d = """
create table if not exists ods_prod.ods_scg_wld_kulu_inbound_warehouse_management_i_d
(
    dt                                varchar(10) comment '创建时间',
    actual_arrival_date               varchar(30) comment '实际到达日期',
    agent_spontaneous_head_status     varchar(5) comment '',
    agent_spontaneous_head_type       varchar(5) comment '',
    asn_status                        varchar(5) comment '',
    asn_type                          varchar(5) comment '',
    box_total                         varchar(5) comment '总箱数',
    bulk_cargo_type                   varchar(10) comment '',
    bulk_cargo_type_piece             varchar(10) comment '',
    business_type                     varchar(10) comment '',
    conta_id                          varchar(10) comment '',
    conta_model                       varchar(10) comment '',
    conta_wt                          varchar(10) comment '',
    contact_phone                     varchar(20) comment '',
    contacter                         varchar(10) comment '',
    container_type                    varchar(10) comment '',
    contract_no                       varchar(10) comment '',
    create_original                   varchar(10) comment '',
    customer_code                     varchar(10) comment '产品代码',
    customer_id                       varchar(10) comment '',
    customer_type                     varchar(10) comment '',
    customer_type_title               varchar(20) comment '报关类型',
    putaway_qty                       varchar(10) comment 'sku入库数量',
    received_qty                      varchar(10) comment 'sku接收数量',
    receiving_qty                     varchar(10) comment 'sku数量',
    transfer_qty                      varchar(10) comment '',
    entiry_code                       varchar(10) comment '',
    expected_date                     varchar(20) comment '预计到达日期',
    form_type                         varchar(10) comment '',
    haveconta                         varchar(10) comment '',
    ie_port                           varchar(10) comment '',
    income_status                     varchar(10) comment '',
    income_time                       varchar(20) comment '',
    income_type                       varchar(10) comment '',
    income_type_title                 varchar(10) comment '交货方式',
    incoming_order_goods_type         varchar(10) comment '',
    insurance_type                    varchar(10) comment '',
    insurance_value                   varchar(10) comment '',
    is_box_label                      varchar(10) comment '',
    is_cloud                          varchar(10) comment '',
    is_dmc                            varchar(10) comment '',
    is_insurance                      varchar(10) comment '',
    is_save_inventory_code            varchar(10) comment '',
    is_show_box_spec                  varchar(10) comment '',
    notification_return_date          varchar(20) comment '通知换柜日期',
    pack_no                           varchar(10) comment '',
    pallet_cnt                        varchar(10) comment '',
    pallet_num                        varchar(10) comment '',
    pd_first_putaway_time             varchar(20) comment '目的仓上架完成时间',
    platform                          varchar(10) comment '',
    po_code                           varchar(10) comment '',
    receiving_abnormal_confirm        varchar(10) comment '',
    receiving_add_time                varchar(20) comment '创建时间',
    receiving_add_user                varchar(10) comment '',
    receiving_business_type           varchar(10) comment '',
    receiving_code                    varchar(30) comment '入库单号',
    receiving_description             varchar(80) comment '',
    receiving_exception               varchar(10) comment '',
    receiving_exception_handle        varchar(10) comment '',
    receiving_id                      varchar(10) comment '',
    receiving_lanshou_status          varchar(10) comment '',
    receiving_letter                  varchar(10) comment '',
    receiving_remark                  varchar(10) comment '',
    receiving_source_type             varchar(10) comment '',
    receiving_status                  varchar(10) comment '',
    receiving_status_title            varchar(10) comment '状态',
    receiving_transfer_status         varchar(10) comment '',
    receiving_type                    varchar(10) comment '',
    receiving_type_title              varchar(10) comment '入库单类型',
    receiving_update_time             varchar(20) comment '更新时间',
    receiving_update_user             varchar(10) comment '',
    refercence_form_id                varchar(10) comment '',
    reference_id                      varchar(10) comment '',
    reference_no                      varchar(10) comment '',
    region_0                          varchar(10) comment '',
    region_1                          varchar(10) comment '',
    region_2                          varchar(10) comment '',
    ship_type                         varchar(10) comment '',
    shipment_id                       varchar(10) comment '',
    shipping_method                   varchar(10) comment '',
    sku_species                       varchar(10) comment 'sku种类',
    sku_total                         varchar(10) comment 'sku总数',
    sm_code                           varchar(10) comment '',
    spontaneous_head_cheng_type       varchar(10) comment '',
    stock_type                        varchar(10) comment '',
    street                            varchar(10) comment '',
    supplier_id                       varchar(10) comment '',
    sync_customs_status               varchar(10) comment '',
    sync_customs_sub_status           varchar(10) comment '',
    sync_customs_time                 varchar(20) comment '',
    tax_type                          varchar(10) comment '',
    tracking_number                   varchar(10) comment '',
    trade_mode                        varchar(10) comment '',
    traf_mode                         varchar(10) comment '',
    traf_name                         varchar(10) comment '',
    trans_mode                        varchar(10) comment '',
    transit_type                      varchar(10) comment '',
    transit_type_title                varchar(10) comment '',
    transit_warehouse_code            varchar(10) comment '',
    transit_warehouse_id              varchar(10) comment '',
    unusually_sign                    varchar(10) comment '',
    unusually_status                  varchar(10) comment '',
    vat_tax_code                      varchar(10) comment '',
    verify_status                     varchar(10) comment '',
    warehouse_code                    varchar(10) comment '',
    warehouse_id                      varchar(10) comment '',
    warehouse_receiving_complete_time varchar(20) comment '目的仓收货完成时间',
    warehouse_receiving_time          varchar(20) comment '目的仓收货时间',
    warehouse_shelf_time              varchar(20) comment '目的仓上架完成时间',
    wms_qty_confirm                   varchar(10) comment '',
    wms_receiving_remark              varchar(10) comment '',
    wrap_type                         varchar(10) comment '',
    primary key (dt, receiving_code)
) comment ='酷麓海外仓-入库单管理-张致富';
"""
ods_scg_wld_kulu_inbound_warehouse_management_i_d_field_list = [
    'dt',
    'actual_arrival_date',
    'agent_spontaneous_head_status',
    'agent_spontaneous_head_type',
    'asn_status',
    'asn_type',
    'box_total',
    'bulk_cargo_type',
    'bulk_cargo_type_piece',
    'business_type',
    'conta_id',
    'conta_model',
    'conta_wt',
    'contact_phone',
    'contacter',
    'container_type',
    'contract_no',
    'create_original',
    'customer_code',
    'customer_id',
    'customer_type',
    'customer_type_title',
    'putaway_qty',
    'received_qty',
    'receiving_qty',
    'transfer_qty',
    'entiry_code',
    'expected_date',
    'form_type',
    'haveconta',
    'ie_port',
    'income_status',
    'income_time',
    'income_type',
    'income_type_title',
    'incoming_order_goods_type',
    'insurance_type',
    'insurance_value',
    'is_box_label',
    'is_cloud',
    'is_dmc',
    'is_insurance',
    'is_save_inventory_code',
    'is_show_box_spec',
    'notification_return_date',
    'pack_no',
    'pallet_cnt',
    'pallet_num',
    'pd_first_putaway_time',
    'platform',
    'po_code',
    'receiving_abnormal_confirm',
    'receiving_add_time',
    'receiving_add_user',
    'receiving_business_type',
    'receiving_code',
    'receiving_description',
    'receiving_exception',
    'receiving_exception_handle',
    'receiving_id',
    'receiving_lanshou_status',
    'receiving_letter',
    'receiving_remark',
    'receiving_source_type',
    'receiving_status',
    'receiving_status_title',
    'receiving_transfer_status',
    'receiving_type',
    'receiving_type_title',
    'receiving_update_time',
    'receiving_update_user',
    'refercence_form_id',
    'reference_id',
    'reference_no',
    'region_0',
    'region_1',
    'region_2',
    'ship_type',
    'shipment_id',
    'shipping_method',
    'sku_species',
    'sku_total',
    'sm_code',
    'spontaneous_head_cheng_type',
    'stock_type',
    'street',
    'supplier_id',
    'sync_customs_status',
    'sync_customs_sub_status',
    'sync_customs_time',
    'tax_type',
    'tracking_number',
    'trade_mode',
    'traf_mode',
    'traf_name',
    'trans_mode',
    'transit_type',
    'transit_type_title',
    'transit_warehouse_code',
    'transit_warehouse_id',
    'unusually_sign',
    'unusually_status',
    'vat_tax_code',
    'verify_status',
    'warehouse_code',
    'warehouse_id',
    'warehouse_receiving_complete_time',
    'warehouse_receiving_time',
    'warehouse_shelf_time',
    'wms_qty_confirm',
    'wms_receiving_remark',
    'wrap_type',
]

ods_scg_wld_kulu_sale_order_management_table = "ods_prod.ods_scg_wld_kulu_sale_order_management_i_d"

ods_scg_wld_kulu_sale_order_management_i_d = """
create table if not exists ods_prod.ods_scg_wld_kulu_sale_order_management_i_d
(
    dt                              varchar(10) comment '创建时间',
    abnormal_reason                 varchar(30) comment '',
    abnormal_type                   varchar(5) comment '',
    add_user                        varchar(5) comment '',
    amountpaid                      varchar(10) comment '',
    buyer_id                        varchar(5) comment '',
    buyer_mail                      varchar(5) comment '',
    buyer_name                      varchar(10) comment '',
    cancel_status                   varchar(10) comment '',
    cancel_status_title             varchar(10) comment '',
    carrier_code                    varchar(10) comment '',
    carrier_name                    varchar(10) comment '',
    channel_code                    varchar(10) comment '',
    company_code                    varchar(20) comment '',
    consignee_city                  varchar(20) comment '',
    consignee_company               varchar(10) comment '',
    consignee_country               varchar(10) comment '',
    consignee_country_code          varchar(10) comment '',
    consignee_country_name          varchar(10) comment '',
    consignee_county                varchar(10) comment '',
    consignee_district              varchar(10) comment '',
    consignee_doorplate             varchar(20) comment '',
    consignee_email                 varchar(50) comment '收件人邮箱',
    consignee_license               varchar(10) comment '',
    consignee_name                  varchar(50) comment '收件人',
    consignee_phone                 varchar(20) comment '收件人电话',
    consignee_phone2                varchar(20) comment '',
    consignee_postal_code           varchar(20) comment '',
    consignee_state                 varchar(10) comment '',
    consignee_street1               varchar(30) comment '',
    consignee_street2               varchar(10) comment '',
    consignee_street3               varchar(10) comment '',
    create_method                   varchar(20) comment '',
    create_type                     varchar(10) comment '',
    currency                        varchar(10) comment '币种',
    currencyAmount                  varchar(10) comment '费用',
    customer_id                     varchar(10) comment '',
    date_create                     varchar(20) comment '创建时间',
    date_create_platform            varchar(20) comment '',
    date_last_modify                varchar(20) comment '',
    date_paid_int                   varchar(10) comment '',
    date_paid_platform              varchar(10) comment '',
    date_pickup                     varchar(10) comment '',
    date_release                    varchar(20) comment '审核时间',
    date_warehouse_pack_time        varchar(20) comment '打包时间',
    date_warehouse_pack_time_zone   varchar(20) comment '',
    date_warehouse_shipping         varchar(20) comment '出库时间',
    date_warehouse_shipping_zone    varchar(20) comment '',
    delivery_fee                    varchar(10) comment '费用',
    delivery_method                 varchar(10) comment '',
    ebay_case_type                  varchar(10) comment '',
    finalvaluefee                   varchar(10) comment '',
    fulfillment_channel             varchar(10) comment '',
    has_buyer_note                  varchar(10) comment '',
    has_export                      varchar(10) comment '',
    has_pickup                      varchar(10) comment '',
    has_print_pickup_label          varchar(10) comment '',
    insurance_value                 varchar(10) comment '',
    is_attachment                   varchar(10) comment '',
    is_cloud                        varchar(10) comment '',
    is_cut_off                      varchar(10) comment '',
    is_insurance                    varchar(10) comment '',
    is_merge                        varchar(10) comment '',
    is_oda                          varchar(10) comment '',
    is_one_piece                    varchar(10) comment '',
    is_only_logistics               varchar(10) comment '',
    is_order_cod                    varchar(10) comment '',
    is_residential                  varchar(10) comment '',
    is_returns                      varchar(10) comment '',
    is_signature                    varchar(20) comment '',
    is_sync_erp                     varchar(10) comment '',
    is_vip                          varchar(10) comment '',
    large_order                     varchar(10) comment '',
    leave_comment                   varchar(10) comment '',
    lifting_cabinet                 varchar(10) comment '',
    lp_code                         varchar(10) comment '',
    mp_code                         varchar(10) comment '',
    no_tracking_number              varchar(10) comment '',
    oda_type                        varchar(10) comment '',
    op_record_id                    varchar(10) comment '',
    op_ref_item_id                  varchar(10) comment '',
    open_get_label_button           varchar(10) comment '',
    operator_id                     varchar(10) comment '',
    operator_note                   varchar(10) comment '',
    orderCode                       varchar(10) comment '',
    orderSourceCode                 varchar(10) comment '',
    order_age_limit                 varchar(10) comment '',
    order_asn                       varchar(10) comment '',
    order_business_type             varchar(10) comment '',
    order_cod_currency              varchar(20) comment '',
    order_delivery_method           varchar(10) comment '',
    order_desc                      varchar(10) comment '',
    order_id                        varchar(10) comment '',
    OrderID                         varchar(30) comment '订单号',
    product_sku                     varchar(30) comment '产品sku',
    op_quantity                     varchar(10) comment '产品数量',
    order_refund                    varchar(10) comment '',
    order_status                    varchar(10) comment '状态',
    order_tracking                  varchar(10) comment '',
    order_type                      varchar(10) comment '订单类型',
    order_type_title                varchar(10) comment '',
    order_weight                    varchar(10) comment '签出重',
    org_refrence_no_platform        varchar(10) comment '',
    ot_id                           varchar(10) comment '',
    out_type                        varchar(10) comment '',
    package_order_code              varchar(10) comment '',
    platform                        varchar(10) comment '',
    platform_fee                    varchar(10) comment '',
    platform_shop                   varchar(10) comment '',
    print_status                    varchar(10) comment '',
    process_again                   varchar(10) comment '',
    product_count                   varchar(10) comment '',
    receiving_code                  varchar(10) comment '',
    refrence_no                     varchar(30) comment '参考编号',
    refrence_no_platform            varchar(30) comment '订单号',
    refrence_no_sys                 varchar(30) comment '',
    refrence_no_warehouse           varchar(30) comment '',
    seller_id                       varchar(10) comment '',
    service_provider                varchar(10) comment '',
    service_status                  varchar(10) comment '',
    shared_sign                     varchar(10) comment '',
    ship_fee                        varchar(10) comment '',
    ship_service_level              varchar(10) comment '',
    shipment_service_level_category varchar(10) comment '',
    shipping_address_id             varchar(10) comment '',
    shipping_method                 varchar(20) comment '运输方式',
    shipping_method_no              varchar(30) comment '跟踪号',
    shipping_method_platform        varchar(10) comment '',
    site                            varchar(10) comment '',
    sub_status                      varchar(10) comment '',
    subtotal                        varchar(10) comment '',
    sync_status                     varchar(10) comment '',
    sync_time                       varchar(20) comment '',
    sys_tips                        varchar(10) comment '',
    third_part_order_no             varchar(10) comment '',
    user_account                    varchar(10) comment '',
    warehouse_code                  varchar(10) comment '',
    warehouse_id                    varchar(10) comment '',
    primary key (dt, refrence_no_sys,product_sku)
) comment ='酷麓海外仓-订单管理-张致富';
"""
ods_scg_wld_kulu_sale_order_management_i_d_field_list = [
    'dt',
    'abnormal_reason',
    'abnormal_type',
    'add_user',
    'amountpaid',
    'buyer_id',
    'buyer_mail',
    'buyer_name',
    'cancel_status',
    'cancel_status_title',
    'carrier_code',
    'carrier_name',
    'channel_code',
    'company_code',
    'consignee_city',
    'consignee_company',
    'consignee_country',
    'consignee_country_code',
    'consignee_country_name',
    'consignee_county',
    'consignee_district',
    'consignee_doorplate',
    'consignee_email',
    'consignee_license',
    'consignee_name',
    'consignee_phone',
    'consignee_phone2',
    'consignee_postal_code',
    'consignee_state',
    'consignee_street1',
    'consignee_street2',
    'consignee_street3',
    'create_method',
    'create_type',
    'currency',
    'currencyAmount',
    'customer_id',
    'date_create',
    'date_create_platform',
    'date_last_modify',
    'date_paid_int',
    'date_paid_platform',
    'date_pickup',
    'date_release',
    'date_warehouse_pack_time',
    'date_warehouse_pack_time_zone',
    'date_warehouse_shipping',
    'date_warehouse_shipping_zone',
    'delivery_fee',
    'delivery_method',
    'ebay_case_type',
    'finalvaluefee',
    'fulfillment_channel',
    'has_buyer_note',
    'has_export',
    'has_pickup',
    'has_print_pickup_label',
    'insurance_value',
    'is_attachment',
    'is_cloud',
    'is_cut_off',
    'is_insurance',
    'is_merge',
    'is_oda',
    'is_one_piece',
    'is_only_logistics',
    'is_order_cod',
    'is_residential',
    'is_returns',
    'is_signature',
    'is_sync_erp',
    'is_vip',
    'large_order',
    'leave_comment',
    'lifting_cabinet',
    'lp_code',
    'mp_code',
    'no_tracking_number',
    'oda_type',
    'op_record_id',
    'op_ref_item_id',
    'open_get_label_button',
    'operator_id',
    'operator_note',
    'orderCode',
    'orderSourceCode',
    'order_age_limit',
    'order_asn',
    'order_business_type',
    'order_cod_currency',
    'order_delivery_method',
    'order_desc',
    'order_id',
    'OrderID',
    'product_sku',
    'op_quantity',
    'order_refund',
    'order_status',
    'order_tracking',
    'order_type',
    'order_type_title',
    'order_weight',
    'org_refrence_no_platform',
    'ot_id',
    'out_type',
    'package_order_code',
    'platform',
    'platform_fee',
    'platform_shop',
    'print_status',
    'process_again',
    'product_count',
    'receiving_code',
    'refrence_no',
    'refrence_no_platform',
    'refrence_no_sys',
    'refrence_no_warehouse',
    'seller_id',
    'service_provider',
    'service_status',
    'shared_sign',
    'ship_fee',
    'ship_service_level',
    'shipment_service_level_category',
    'shipping_address_id',
    'shipping_method',
    'shipping_method_no',
    'shipping_method_platform',
    'site',
    'sub_status',
    'subtotal',
    'sync_status',
    'sync_time',
    'sys_tips',
    'third_part_order_no',
    'user_account',
    'warehouse_code',
    'warehouse_id',
]

ods_scg_wld_kulu_expense_bill_management_table = "ods_prod.ods_scg_wld_kulu_expense_bill_management_i_d"

ods_scg_wld_kulu_expense_bill_management_i_d = """
create table if not exists ods_prod.ods_scg_wld_kulu_expense_bill_management_i_d
(
    dt                   varchar(10) comment '计费时间',
    attachments          varchar(30) comment '',
    bb_charge_weight     varchar(30) comment '',
    bb_id                varchar(10) comment '',
    bb_refer_code        varchar(30) comment '单号',
    bb_reference_no      varchar(30) comment '',
    bb_service_number    varchar(30) comment '',
    bcb_id               varchar(10) comment '',
    bcb_writeoff_sign    varchar(10) comment '',
    bi_amount            varchar(10) comment '结算金额',
    bi_chargeable_time   varchar(20) comment '计费时间',
    bi_id                varchar(10) comment '',
    bi_note              varchar(10) comment '',
    bi_org_amount        varchar(10) comment '计费规则币种金额',
    bi_status            varchar(5) comment '',
    bi_update_time       varchar(20) comment '',
    cost_formula         varchar(200) comment '',
    cost_formula_detail  varchar(600) comment '',
    create_type          varchar(10) comment '',
    currency_code        varchar(10) comment '',
    currency_rate        varchar(10) comment '',
    customer_code        varchar(10) comment '',
    customer_currency    varchar(10) comment '',
    ds_code              varchar(10) comment '业务类型',
    ft_code              varchar(10) comment '费用类型',
    obj_id               varchar(20) comment '',
    order_code           varchar(20) comment '',
    order_id             varchar(20) comment '',
    platform             varchar(20) comment '',
    platform_shop        varchar(20) comment '',
    reference_no         varchar(30) comment '参考号',
    settle_currency_code varchar(10) comment '',
    shipping_method      varchar(50) comment '运输方式',
    sm_code              varchar(50) comment '',
    so_weight            varchar(10) comment '',
    warehouse_id         varchar(10) comment '仓库',
    primary key (dt, bb_refer_code, ft_code)
) comment ='酷麓海外仓-费用账单-张致富';
"""
ods_scg_wld_kulu_expense_bill_management_i_d_field_list = [
    'dt',
    'attachments',
    'bb_charge_weight',
    'bb_id',
    'bb_refer_code',
    'bb_reference_no',
    'bb_service_number',
    'bcb_id',
    'bcb_writeoff_sign',
    'bi_amount',
    'bi_chargeable_time',
    'bi_id',
    'bi_note',
    'bi_org_amount',
    'bi_status',
    'bi_update_time',
    'cost_formula',
    'cost_formula_detail',
    'create_type',
    'currency_code',
    'currency_rate',
    'customer_code',
    'customer_currency',
    'ds_code',
    'ft_code',
    'obj_id',
    'order_code',
    'order_id',
    'platform',
    'platform_shop',
    'reference_no',
    'settle_currency_code',
    'shipping_method',
    'sm_code',
    'so_weight',
    'warehouse_id',
]

# 澳得亚海外仓
ods_scg_wld_oms_sale_outbound_order_table = "ods_prod.ods_scg_wld_oms_sale_outbound_order_i_d"

ods_scg_wld_oms_sale_outbound_order_i_d = """
create table if not exists ods_prod.ods_scg_wld_oms_sale_outbound_order_i_d
(
    dt                    varchar(10) comment '创建时间',
    actualWeight          varchar(10) comment '包裹重量',
    addressOne            varchar(100) comment '',
    addressTwo            varchar(100) comment '',
    adjustNo              varchar(100) comment '',
    agentId               varchar(30) comment '',
    agentSubIng           varchar(100) comment '',
    appendixList          varchar(30) comment '',
    billItems             json comment '费用',
    billingFlag           varchar(10) comment '',
    canceledTime          varchar(20) comment '',
    channelGroupFlag      varchar(10) comment '',
    channelType           varchar(10) comment '',
    cityCode              varchar(10) comment '',
    cityName              varchar(80) comment '城市名称',
    companyName           varchar(40) comment '公司名称',
    costBillTotal         varchar(15) comment '金额',
    countryRegionCode     varchar(20) comment '',
    countryRegionName     varchar(40) comment '国家、地区',
    createBy              varchar(40) comment '',
    createTime            varchar(20) comment '',
    currencyCode          varchar(10) comment '币种',
    currencyUnit          varchar(10) comment '',
    customerCode          varchar(10) comment '',
    deleted               varchar(10) comment '',
    deliveredTime         varchar(20) comment '',
    email                 varchar(80) comment '邮箱',
    enableLabelDownload   varchar(20) comment '',
    exceptionDesc         varchar(60) comment '',
    exceptionDescPage     varchar(60) comment '',
    exceptionTime         varchar(30) comment '',
    expectWeight          varchar(10) comment '',
    expectedTime          varchar(20) comment '',
    expressCount          varchar(10) comment '',
    expressList           json comment '',
    fbaReferNo            varchar(10) comment '',
    fbaShipmentId         varchar(10) comment '',
    forecastTime          varchar(30) comment '',
    houseNum              varchar(10) comment '',
    insureMoney           varchar(10) comment '',
    interceptTime         varchar(10) comment '',
    isAdjust              varchar(10) comment '',
    labelCancelResult     varchar(10) comment '',
    labelCancelResultDesc varchar(10) comment '',
    labelCancelResultName varchar(10) comment '',
    labelCancelTime       varchar(20) comment '',
    lastEvent             varchar(400) comment '',
    lastTrackingTime      varchar(20) comment '',
    logisticsCarrier      varchar(10) comment '',
    logisticsChannel      varchar(30) comment '',
    logisticsChannelName  varchar(30) comment '',
    logisticsProduct      varchar(10) comment '',
    logisticsProductName  varchar(10) comment '',
    messageList           varchar(10) comment '',
    needRelabel           varchar(10) comment '',
    orderCreateTime       varchar(20) comment '创建时间',
    orderExtensionInfoBO  varchar(100) comment '',
    orderSource           varchar(10) comment '',
    orderType             varchar(10) comment '',
    orderTypeName         varchar(10) comment '',
    outboundOrderNo       varchar(20) comment '出库单号',
    outboundTime          varchar(20) comment '出库时间',
    packageList           varchar(10) comment '',
    packageTime           varchar(10) comment '',
    pallets               varchar(10) comment '',
    platformOrderNo       varchar(30) comment '平台单号',
    postCode              varchar(30) comment '邮编',
    prosessingTime        varchar(20) comment '提交时间',
    provinceCode          varchar(10) comment '',
    provinceName          varchar(40) comment '',
    receiptTime           varchar(20) comment '',
    receiver              varchar(100) comment '收件人',
    referOrderNo          varchar(30) comment '参考单号',
    relatedReturnOrder    varchar(10) comment '',
    remark                varchar(300) comment '',
    salesPlatform         varchar(10) comment '',
    signatureService      varchar(10) comment '',
    skuKind               varchar(10) comment '',
    skuQtySum             varchar(10) comment 'sku数量',
    source                varchar(10) comment '',
    status                varchar(10) comment '状态',
    statusName            varchar(10) comment '状态名',
    storeName             varchar(40) comment '店铺名',
    subOrderType          varchar(10) comment '',
    subOrderTypeName      varchar(10) comment '',
    substate              varchar(10) comment '',
    substateName          varchar(10) comment '',
    taxNum                varchar(10) comment '',
    telephone             varchar(20) comment '电话',
    telephoneRequired     varchar(10) comment '',
    tenantCode            varchar(10) comment '',
    totalQuantity         varchar(10) comment '',
    trackNo               varchar(30) comment '物流跟踪号',
    transitDay            varchar(10) comment '',
    transitStatus         varchar(10) comment '',
    unread                varchar(10) comment '',
    updateBy              varchar(30) comment '',
    updateTime            varchar(20) comment '',
    vasList               varchar(10) comment '',
    weightUnit            varchar(10) comment '',
    whCode                varchar(10) comment '仓库编码',
    whName                varchar(20) comment '仓库',
    primary key (dt, outboundOrderNo)
) comment ='澳得亚海外仓-一件代发出库-张致富'
    partition by key (dt) partitions 3;
"""
ods_scg_wld_oms_sale_outbound_order_i_d_field_list = [
    'dt',
    'actualWeight',
    'addressOne',
    'addressTwo',
    'adjustNo',
    'agentId',
    'agentSubIng',
    'appendixList',
    'billItems',
    'billingFlag',
    'canceledTime',
    'channelGroupFlag',
    'channelType',
    'cityCode',
    'cityName',
    'companyName',
    'costBillTotal',
    'countryRegionCode',
    'countryRegionName',
    'createBy',
    'createTime',
    'currencyCode',
    'currencyUnit',
    'customerCode',
    'deleted',
    'deliveredTime',
    'email',
    'enableLabelDownload',
    'exceptionDesc',
    'exceptionDescPage',
    'exceptionTime',
    'expectWeight',
    'expectedTime',
    'expressCount',
    'expressList',
    'fbaReferNo',
    'fbaShipmentId',
    'forecastTime',
    'houseNum',
    'insureMoney',
    'interceptTime',
    'isAdjust',
    'labelCancelResult',
    'labelCancelResultDesc',
    'labelCancelResultName',
    'labelCancelTime',
    'lastEvent',
    'lastTrackingTime',
    'logisticsCarrier',
    'logisticsChannel',
    'logisticsChannelName',
    'logisticsProduct',
    'logisticsProductName',
    'messageList',
    'needRelabel',
    'orderCreateTime',
    'orderExtensionInfoBO',
    'orderSource',
    'orderType',
    'orderTypeName',
    'outboundOrderNo',
    'outboundTime',
    'packageList',
    'packageTime',
    'pallets',
    'platformOrderNo',
    'postCode',
    'prosessingTime',
    'provinceCode',
    'provinceName',
    'receiptTime',
    'receiver',
    'referOrderNo',
    'relatedReturnOrder',
    'remark',
    'salesPlatform',
    'signatureService',
    'skuKind',
    'skuQtySum',
    'source',
    'status',
    'statusName',
    'storeName',
    'subOrderType',
    'subOrderTypeName',
    'substate',
    'substateName',
    'taxNum',
    'telephone',
    'telephoneRequired',
    'tenantCode',
    'totalQuantity',
    'trackNo',
    'transitDay',
    'transitStatus',
    'unread',
    'updateBy',
    'updateTime',
    'vasList',
    'weightUnit',
    'whCode',
    'whName',
]

ods_scg_wld_oms_sale_outbound_order_detail_table = "ods_prod.ods_scg_wld_oms_sale_outbound_order_detail_i_d"

ods_scg_wld_oms_sale_outbound_order_detail_i_d = """
create table if not exists ods_prod.ods_scg_wld_oms_sale_outbound_order_detail_i_d
(
    dt                varchar(10) comment '创建时间',
    outboundOrderNo   varchar(20) comment '出库单号',
    availableAmount   varchar(10) comment '',
    createBy          varchar(10) comment '',
    createTime        varchar(20) comment '',
    currencyCode      varchar(10) comment '',
    declarePrice      varchar(10) comment '',
    deleted           varchar(10) comment '',
    fnsku             varchar(20) comment '',
    newCode           varchar(20) comment '',
    newCodeFileKey    varchar(20) comment '',
    newCodeFileName   varchar(20) comment '',
    newCodeMaintained varchar(20) comment '',
    productAliasName  varchar(30) comment '',
    productName       varchar(30) comment '',
    quantity          varchar(10) comment '销售数量',
    realQuantity      varchar(10) comment '销售数量',
    remark            varchar(200) comment '',
    sku               varchar(30) comment 'SKU',
    skuId             varchar(20) comment '',
    updateBy          varchar(20) comment '',
    updateTime        varchar(20) comment '',
    primary key (dt, outboundOrderNo, sku)
) comment ='澳得亚海外仓-一件代发出库详情-张致富'
    partition by key (dt) partitions 3;
"""
ods_scg_wld_oms_sale_outbound_order_detail_i_d_field_list = [
    'dt',
    'outboundOrderNo',
    'availableAmount',
    'createBy',
    'createTime',
    'currencyCode',
    'declarePrice',
    'deleted',
    'fnsku',
    'newCode',
    'newCodeFileKey',
    'newCodeFileName',
    'newCodeMaintained',
    'productAliasName',
    'productName',
    'quantity',
    'realQuantity',
    'remark',
    'sku',
    'skuId',
    'updateBy',
    'updateTime',
]

ods_scg_wld_oms_cost_business_flow_table = "ods_prod.ods_scg_wld_oms_cost_business_flow_i_d"

ods_scg_wld_oms_cost_business_flow_i_d = """
create table if not exists ods_prod.ods_scg_wld_oms_cost_business_flow_i_d
(
    dt               varchar(10) comment '创建时间',
    adjustmentStatus varchar(10) comment '调整状态',
    billStatus       varchar(10) comment '出账状态(1.未出账、2.已出账)',
    billType         varchar(10) comment '出账类型',
    channelCode      varchar(30) comment '渠道编码',
    channelGroupCode varchar(30) comment '',
    channelGroupFlag varchar(30) comment '',
    channelGroupName varchar(30) comment '',
    channelName      varchar(30) comment '渠道名',
    chargeWeight     varchar(20) comment '',
    chargeWeightBs   varchar(20) comment '',
    costNo           varchar(40) comment '费用编码',
    costStatus       varchar(10) comment '计费状态(1.未计费、2.已计费、3.计费异常、4.重新计费中、5.计费中)',
    costTime         varchar(20) comment '计费时间',
    costTotal        varchar(10) comment '金额',
    createTime       varchar(20) comment '创建时间',
    currencyCode     varchar(8) comment '币种',
    customerCode     varchar(20) comment '客户编码',
    customerName     varchar(40) comment '公司名称',
    expressNo        varchar(40) comment '物流跟踪号',
    logisticsTotal   varchar(10) comment '',
    moduleType       varchar(3) comment '业务类型(1.入库、2.出库、5.工单、6.仓租、7.其他)',
    operateTotal     varchar(10) comment '金额',
    orderInStatus    varchar(10) comment '订单状态',
    orderNo          varchar(30) comment 'OMS单据号',
    orderOutStatus   varchar(10) comment '订单出库状态',
    preWeight        varchar(10) comment '',
    preWeightBs      varchar(10) comment '',
    relChannelCode   varchar(10) comment '',
    relChannelName   varchar(10) comment '',
    relateBillNo     varchar(10) comment '',
    remark           varchar(200) comment '',
    statisticDate    varchar(20) comment '',
    volumeWeight     varchar(10) comment '',
    volumeWeightBs   varchar(10) comment '',
    weight           varchar(10) comment '',
    weightBs         varchar(10) comment '',
    weightUnit       varchar(10) comment '',
    whCode           varchar(10) comment '仓库编码',
    whName           varchar(20) comment '仓库名称',
    zone             varchar(20) comment ''
) comment ='澳得亚海外仓-业务流水-张致富';
"""
ods_scg_wld_oms_cost_business_flow_i_d_field_list = [
    'dt',
    'adjustmentStatus',
    'billStatus',
    'billType',
    'channelCode',
    'channelGroupCode',
    'channelGroupFlag',
    'channelGroupName',
    'channelName',
    'chargeWeight',
    'chargeWeightBs',
    'costNo',
    'costStatus',
    'costTime',
    'costTotal',
    'createTime',
    'currencyCode',
    'customerCode',
    'customerName',
    'expressNo',
    'logisticsTotal',
    'moduleType',
    'operateTotal',
    'orderInStatus',
    'orderNo',
    'orderOutStatus',
    'preWeight',
    'preWeightBs',
    'relChannelCode',
    'relChannelName',
    'relateBillNo',
    'remark',
    'statisticDate',
    'volumeWeight',
    'volumeWeightBs',
    'weight',
    'weightBs',
    'weightUnit',
    'whCode',
    'whName',
    'zone',
]

ods_scg_wld_kulu_inbound_warehouse_management_detail_table = "ods_prod.ods_scg_wld_kulu_inbound_warehouse_management_detail_i_d"

ods_scg_wld_kulu_inbound_warehouse_management_detail_i_d = """
create table if not exists ods_prod.ods_scg_wld_kulu_inbound_warehouse_management_detail_i_d
(
    dt                            varchar(10) comment '更新时间',
    Product_img                   varchar(80) comment '产品图片',
    batch_number                  varchar(30) comment '',
    box_label                     varchar(30) comment '',
    box_no                        varchar(10) comment '',
    box_number                    varchar(10) comment '',
    box_spec                      varchar(10) comment '',
    customer_box_number           varchar(10) comment '',
    exception_process_instruction varchar(10) comment '',
    insured_amount                varchar(10) comment '产品单价',
    inventory_type                varchar(10) comment '',
    is_need_dev_desc              varchar(10) comment '',
    is_need_dev_photo             varchar(10) comment '',
    is_priority                   varchar(10) comment '',
    is_qc                         varchar(5) comment '',
    line_weight                   varchar(20) comment '重量',
    map_status                    varchar(20) comment '',
    package_type                  varchar(20) comment '',
    product_barcode               varchar(30) comment '产品代码',
    product_date                  varchar(10) comment '',
    product_id                    varchar(10) comment '',
    product_package_type          varchar(10) comment '',
    product_price                 varchar(10) comment '',
    product_sku                   varchar(20) comment 'SKU',
    product_title                 varchar(20) comment '颜色尺码',
    rd_add_time                   varchar(20) comment '',
    rd_associated_barcode         varchar(20) comment '',
    rd_id                         varchar(20) comment '',
    rd_note                       varchar(20) comment '',
    rd_put_qty_lc                 varchar(20) comment '',
    rd_putaway_qty                varchar(10) comment '',
    rd_received_qty               varchar(10) comment '',
    rd_receiving_qty              varchar(10) comment '送货数',
    rd_status                     varchar(10) comment '',
    rd_transfer_qty               varchar(10) comment '',
    rd_transfer_status            varchar(10) comment '',
    rd_update_time                varchar(20) comment '',
    rdc_id                        varchar(10) comment '',
    receiving_code                varchar(30) comment '入库单号',
    receiving_exception           varchar(10) comment '',
    receiving_exception_handle    varchar(10) comment '',
    receiving_id                  varchar(10) comment '',
    receiving_line_no             varchar(10) comment '',
    sm_code                       varchar(10) comment '',
    supplier_id                   varchar(10) comment '',
    valid_date                    varchar(10) comment '',
    value_added_type              varchar(10) comment '',
    primary key (dt, product_barcode, receiving_code)
) comment ='酷麓海外仓-入库单详情-张致富';
"""
ods_scg_wld_kulu_inbound_warehouse_management_detail_i_d_field_list = [
    'dt',
    'Product_img',
    'batch_number',
    'box_label',
    'box_no',
    'box_number',
    'box_spec',
    'customer_box_number',
    'exception_process_instruction',
    'insured_amount',
    'inventory_type',
    'is_need_dev_desc',
    'is_need_dev_photo',
    'is_priority',
    'is_qc',
    'line_weight',
    'map_status',
    'package_type',
    'product_barcode',
    'product_date',
    'product_id',
    'product_package_type',
    'product_price',
    'product_sku',
    'product_title',
    'rd_add_time',
    'rd_associated_barcode',
    'rd_id',
    'rd_note',
    'rd_put_qty_lc',
    'rd_putaway_qty',
    'rd_received_qty',
    'rd_receiving_qty',
    'rd_status',
    'rd_transfer_qty',
    'rd_transfer_status',
    'rd_update_time',
    'rdc_id',
    'receiving_code',
    'receiving_exception',
    'receiving_exception_handle',
    'receiving_id',
    'receiving_line_no',
    'sm_code',
    'supplier_id',
    'valid_date',
    'value_added_type',
]

ods_scg_wld_oms_warehouse_inbound_order_table = "ods_prod.ods_scg_wld_oms_warehouse_inbound_order_i_d"

ods_scg_wld_oms_warehouse_inbound_order_i_d = """
create table if not exists ods_prod.ods_scg_wld_oms_warehouse_inbound_order_i_d
(
    dt              varchar(10) comment '创建时间',
    agentOrder      varchar(20) comment '',
    agentType       varchar(10) comment '',
    arrivalMode     varchar(10) comment '',
    billItems       json comment '费用详情',
    billingFlag     varchar(10) comment '',
    boxQuantity     varchar(5) comment '箱数',
    canceledTime    varchar(20) comment '取消时间',
    costBillTotal   varchar(20) comment '费用',
    currencyCode    varchar(10) comment '币种',
    exceptionDesc   varchar(20) comment '',
    expectedDate    varchar(20) comment '',
    id              varchar(20) comment '',
    inboundOrderNo  varchar(30) comment '入库单号',
    inboundType     varchar(5) comment '入库单类型',
    inboundTypeName varchar(20) comment '入库单类型',
    orderCreateTime varchar(20) comment '创建时间',
    quantity        varchar(10) comment '数量',
    sku             varchar(30) comment 'SKU',
    pushWmsTime     varchar(20) comment '提交时间',
    receivedEndTime varchar(20) comment '收货时间',
    referOrderNo    varchar(20) comment '',
    shelfEndTime    varchar(20) comment '上架时间',
    skuQtySum       varchar(20) comment '产品数量',
    status          varchar(5) comment '状态(0.草稿1.待入库2.收货中3.已收货4.已上架5.已取消)',
    tenantCode      varchar(20) comment '',
    trackingNo      varchar(20) comment '',
    unread          varchar(20) comment '',
    whCode          varchar(20) comment '仓库编码',
    whName          varchar(20) comment '仓库名',
    primary key (dt, inboundOrderNo, sku)
) comment ='澳得亚海外仓-入库单-张致富'
    partition by key (dt) partitions 3;
"""
ods_scg_wld_oms_warehouse_inbound_order_i_d_field_list = [
    'dt',
    'agentOrder',
    'agentType',
    'arrivalMode',
    'billItems',
    'billingFlag',
    'boxQuantity',
    'canceledTime',
    'costBillTotal',
    'currencyCode',
    'exceptionDesc',
    'expectedDate',
    'id',
    'inboundOrderNo',
    'inboundType',
    'inboundTypeName',
    'orderCreateTime',
    'quantity',
    'sku',
    'pushWmsTime',
    'receivedEndTime',
    'referOrderNo',
    'shelfEndTime',
    'skuQtySum',
    'status',
    'tenantCode',
    'trackingNo',
    'unread',
    'whCode',
    'whName',
]

# 酷麓海外仓库存
ods_scg_wld_kulu_inv_management_table = "ods_prod.ods_scg_wld_kulu_inv_management_a_h"
ods_scg_wld_kulu_inv_management_a_h = """
create table if not exists ods_prod.ods_scg_wld_kulu_inv_management_a_h
(
    buyer_id            varchar(50) not null comment '买家ID',
    contain_battery     varchar(50) not null comment '是否含电池',
    goods_value         varchar(10) not null comment '商品货值',
    item_ean            varchar(50) not null comment '商品EAN码',
    pc_id               varchar(50) not null comment '产品分类ID',
    pce_id              varchar(50) not null comment '产品分类扩展ID',
    pcse_id             varchar(50) not null comment '产品分类扩展子项ID	',
    pi_hold             varchar(50) not null comment '库存冻结数量',
    pi_id               varchar(50) not null comment '库存记录ID',
    pi_no_stock         varchar(10) not null comment '无库存数量',
    pi_onway            varchar(10) not null comment '在途库存数量',
    pi_pending          varchar(10) not null comment '待处理库存数量',
    pi_reserved         varchar(10) not null comment '预留库存数量',
    pi_right_number     varchar(10) not null comment '库存正确数量',
    pi_sellable         varchar(10) not null comment '可售库存数量',
    pi_shared           varchar(10) not null comment '共享库存数量',
    pi_shipped          varchar(10) not null comment '已发货库存数量',
    pi_unconfirmed      varchar(10) not null comment '未确认库存数量',
    pi_unsellable       varchar(10) not null comment '不可售库存数量',
    pi_update_time      varchar(50) not null comment '库存更新时间',
    pi_warning_qty      varchar(10) not null comment '库存预警数量',
    product_barcode     varchar(50) not null comment '商品条码',
    product_brand       varchar(50) not null comment '商品品牌',
    product_height      varchar(50) not null comment '商品高度',
    product_id          varchar(50) not null comment '商品ID',
    product_information varchar(500) not null comment '商品信息',
    product_length      varchar(10) not null comment '商品长度',
    product_material    varchar(50) not null comment '商品材质',
    product_model       varchar(50) not null comment '商品型号',
    product_sales_value varchar(50) not null comment '商品销售价值',
    product_sku         varchar(50) not null comment '商品SKU',
    product_title       varchar(50) not null comment '商品标题',
    product_title_en    varchar(50) not null comment '商品英文标题',
    product_unit        varchar(50) not null comment '商品单位',
    product_weight      varchar(10) not null comment '商品重量',
    product_width       varchar(10) not null comment '商品宽度',
    reference_no        varchar(50) not null comment '参考编号',
    src                 varchar(150) not null comment '数据来源',
    warehouse_id        varchar(50) not null comment '仓库ID',
    primary key (product_sku)
) comment '酷麓海外仓-库存管理-张致富'
    partition by key (product_sku) partitions 3;
"""
ods_scg_wld_kulu_inv_management_list = [
    "buyer_id",
    "contain_battery",
    "goods_value",
    "item_ean",
    "pc_id",
    "pce_id",
    "pcse_id",
    "pi_hold",
    "pi_id",
    "pi_no_stock",
    "pi_onway",
    "pi_pending",
    "pi_reserved",
    "pi_right_number",
    "pi_sellable",
    "pi_shared",
    "pi_shipped",
    "pi_unconfirmed",
    "pi_unsellable",
    "pi_update_time",
    "pi_warning_qty",
    "product_barcode",
    "product_brand",
    "product_height",
    "product_id",
    "product_information",
    "product_length",
    "product_material",
    "product_model",
    "product_sales_value",
    "product_sku",
    "product_title",
    "product_title_en",
    "product_unit",
    "product_weight",
    "product_width",
    "reference_no",
    "src",
    "warehouse_id"
]

# 澳得亚库存
ods_scg_wld_oms_warehouse_inv_table = "ods_prod.ods_scg_wld_oms_warehouse_inv_a_h"
ods_scg_wld_oms_warehouse_inv_a_h = """
create table if not exists ods_prod.ods_scg_wld_oms_warehouse_inv_a_h
(
    available_amount varchar(10)  not null comment '可用库存',
    full_path_name   varchar(50)  not null comment '全路径名称',
    lock_amount      varchar(10)  not null comment '锁定库存',
    product_name     varchar(250) not null comment '商品名称',
    product_pic_vo   varchar(250) not null comment '商品图片信息',
    sku              varchar(50)  not null comment 'sku',
    stock_type       varchar(10)  not null comment '库存类型',
    stock_type_name  varchar(50)  not null comment '库存类型名称',
    total_amount     varchar(10)  not null comment '总库存',
    transport_amount varchar(10)  not null comment '在途库存',
    wh_code          varchar(10)  not null comment '仓库编码',
    wh_name          varchar(50)  not null comment '仓库名称',
    primary key (sku)
) comment '澳得亚海外仓-产品库存-张致富'
    partition by key (sku) partitions 3;
"""
ods_scg_wld_oms_warehouse_inv_list = [
    "available_amount",
    "full_path_name",
    "lock_amount",
    "product_name",
    "product_pic_vo",
    "sku",
    "stock_type",
    "stock_type_name",
    "total_amount",
    "transport_amount",
    "wh_code",
    "wh_name",
]
